mwaskom/seaborn

seaborn/matrix.py

When setting vmin/vmax and row/col_colors in clustermap, the row/col_colors are affected (I set vmax=0.5 here):
This pull request should fix that.

fixing issue where setting vmin/vmax affects row/col_colors

---

doc/releases/v0.6.0.txt
seaborn/axisgrid.py
seaborn/distributions.py
seaborn/tests/test_axisgrid.py

Previously, `add_legend` was passing a list of handles for the plots that had been drawn and the list of all hue levels to the matplotlib legend code. Because matplotlib just zipped these and didn't raise
when they were of differenet lengths, this meant that sometimes the right colors but wrong labels were used.
This isn't globablly optimal, because I think the behavior we want is to show the hue levels that could have existed in the plot (because they are in `hue_order` but don't, because they weren't in the DataFrame.
However, doing that is a bit tricky because we'll have to make a proxy artist, you can't just pass `None` or something similar as a handle.
This fixes the bug identified in https://github.com/mwaskom/seaborn/issues/361#issuecomment-71140105. @shoyer, this does make the …

Fix bug in Grid legends

---

seaborn/distributions.py

Also added documention default setting ('box')

Fixed inconsistent plurals ('sticks'->'stick'). 

---

doc/tutorial/dataset_exploration.ipynb

Replaced `:link:` with `:ref:` in [tutorial/dataset_exploration](http://web.stanford.edu/~mwaskom/software/seaborn/tutorial/dataset_exploration.html)
Old | New
-----|-------

Fix broken reference in dataset_exploration.ipynb

---

.travis.yml

There seems to be problems with IPython 3 and the testing workflow right now.
https://github.com/mwaskom/seaborn/pull/462#issuecomment-77439356

Use IPython 2.X for testing

---

doc/tutorial/axis_grids.ipynb
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

I force-pushed #436 and now I can't reopen that issue. 
Anyway, I thought about this some more and here's a stab at handling old versions of MPL and instances when `col_wrap` is used. the TODO list still applies:
Here's a rough example:
```python
from io import StringIO
import pandas
import matplotlib.pyplot as plt
import seaborn
datafile = StringIO("""\
location,date,parameter,matrix,units,res
SHP-99-31C,2007-10-17 00:00:00,Iron,WG,ug/L,44000.0
SHP-99-31C,2007-10-17 00:00:00,Arsenic,WG,ug/L,292.1
SHP-99-31C,2009-10-01 00:00:00,Oxidation Reduction Potential,WG,mV,-84.0
SHP-99-31C,2009-10-01 00:00:00,pH,WG,SU,6.57
SHP-99-31C,2009-10-01 00:00:00,Arsenic,WG,ug/L,223.5
SHP-99-31C,2009-10-01 00:00:00,Iron,WG,ug/L,26000.0
SHP-99-31C,2010-10-13 00:00:00,Arsenic,WG,ug/L,239.4 …
```

Add gridspec_kws to FacetGrid

---

doc/releases/v0.6.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fix bug in accessing side marginal axes with `col_wrap`, closes #464
Raise a better error when `row` and `col_wrap` are used together, closes #465

Fix two FacetGrid problems

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

There is an issue with heatmap annotations when when there are masked values in the data. Formatting fails for these masked values. 
Discussed in #375.
http://nbviewer.ipython.org/github/JWarmenhoven/ipython_notebooks/blob/master/Seaborn_heatmap_issue.ipynb

Skip annotating masked values in heatmaps

---

seaborn/axisgrid.py

Current version requires that the user pass `vertical=False` for the plotting to work correctly.

Fix kwarg issue with plot_marginals

---

doc/releases/v0.6.0.txt
seaborn/matrix.py
seaborn/tests/test_matrix.py

The main change here is to reorganize the mask in `clustermap` using the dendrograms, which fixes the bug in #512.
This also automatically adds cells with missing values in `heatmap` (and hence) `clustermap` to the mask matrix, thus addressing the issue in #375 (yikes that's old).
Also adds some helpful validation of the mask to make sure it's the right shape and that the semantic information matches that in `data` if a pandas object is used.

Better handling of masks in heatmap and clustermap

---

seaborn/categorical.py

Fixes at least the props side of #536, by updating artists' properties after restyling if the props kwargs are there. Thus even if a props kwarg is present, it will only override seaborn's styling if that's actually what the user intends.
This does not fix the sym kwarg. The best way I could see to do so would involve importing _process_plot_format from matplotlib.axes._base, and I'm not sure if it's worth it, as flyerprops allows the same settings to be made in a more reliable way.

Modified boxplot to take into account flierprops and other props kwargs. 

---

doc/releases/v0.6.0.txt
seaborn/distributions.py

This should help avoid confusing issues with certain datasets that cause the reference rule to return ridiculous values. It also in general avoids drawing too many bars, which usually isn't helpful and just slows things down. The ceiling is not applied when a specific number of bins is requested.
Fixes #503

Add a ceiling to the default number of bins used in distplot

---

doc/releases/v0.6.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

This fixes #472.
This also changes the default `hue_order` to use the same `category_order`
rules as elsewhere in seaborn (cf #361).

Fix hue_order in PairGrid

---

doc/releases/v0.6.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_utils.py
seaborn/utils.py

`FacetGrid` now uses `utils.categorical_order` to determine default order for the `row`, `color`, and `hue` variables. This means that all categorical ordering in seaborn should follow the same rules. Please open an issue if you run into something that doesn't.
Closes #361

Extend new categorical ordering rules to FacetGrid

---

doc/releases/v0.6.0.txt
seaborn/matrix.py
seaborn/tests/test_matrix.py

- Changed the default `linewidths` to 0 so that large matrices don't have a confusing white-out from the cell lines. Ideally this would have been accomplished with an adaptive linewidth, but for reasonably sized matrices the smallest lines that could be drawn still messed up the plots in, at least, the notebook. Closes #445.
- Added the ability to pass an integer to `xticklabels` and `yticklabels` which will plot every `n` label to help with larger matrices.
- Fixed a bug where specified ticklabel arrays were not being reordered to reflect the clustering in `clustermap`. Closes #550.

Some changes to help heatmap and clustermap plot large matrices

---

doc/api.rst
doc/releases/v0.6.0.txt
seaborn/palettes.py
seaborn/rcmod.py
seaborn/tests/test_categorical.py
seaborn/tests/test_palettes.py

Several changes wrapped up here:
This function will reach into matplotlib and change the interpretation of matplotlib color codes (i.e. `"b"`, "`g"`) to match the colors from the seaborn palettes. This makes it easier to generate attractive figures when calling matplotlib functions directly. As this is borderline abuse of the matplotlib API, this doesn't currently happen by default when importing seaborn. It's possible that will change in the future. You can also pass `color_codes=True` to `set()` or `set_palette()` to do this in one step.
Closes #293
This addresses a surprising issue that comes up when you do something like
```python
len(color_palette(color_palette("Blues", 8)))
```
Now, the length of the current color cycle or input palette is respected. This makes the code messier and …

Changes to seaborn color handling

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fix a bug introduced in #547 (that caused PairGrid to crash on missing data).

Fix bug in PairGrid missing data handling

---

doc/releases/v0.6.0.txt
seaborn/tests/test_utils.py
seaborn/utils.py

This PR introduces a couple extra arguments to the ``load_dataset`` utility; it allows datasets to optionally be cached locally for use without a network connection.
I think the doc string is pretty self explanatory, but let me know if it needs clarification!

ENH: allow local cacheing of datasets

---

seaborn/utils.py

Avoid a crash at the cost of having overlapping ticklabels in some plots when using the OSX backend.
This is a replacement for #546 and addresses the issues in #545

Avoid crash in clustermap with matplotlib OSX backend

---

doc/releases/v0.6.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

This should keep the titles tighter to the axes when the figure
layout changes, such as adding a legend. This PR therefore fixes #303.
Also added a background to the text, which should prevent the issue
where adding multiple titles "stacks" the row titles (#509).
Also changed the default `savefig` `bbox_inches` to "tight" in Grid objects, so these texts won't get clipped when saving.

Draw margin titles with ax.annotate instead of f.text

---

seaborn/tests/test_categorical.py

Prevent the tests below from failing with very close values:
======================================================================
FAIL: seaborn.tests.test_categorical.TestCategoricalStatPlotter.test_nested_stats_with_missing_data
----------------------------------------------------------------------
[...]
Items are not equal:
ACTUAL: -0.018721526986487352
DESIRED: -0.018721526986487342
======================================================================
FAIL: seaborn.tests.test_categorical.TestCategoricalStatPlotter.test_single_layer_stats_with_missing_data
----------------------------------------------------------------------
[...]
AssertionError:
Items are not equal:
ACTUAL: 0.082012970747837352
DESIRED: 0.08201297074783731

Convert two tests to almost_equal variant

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

When kind is "count" for factorplot, raise ValueError if both x and y
are given.  Otherwise, x_ and _y will not be defined, leading to an
UnboundLocalError.

factorplot: Extend input check when kind="count"

---

doc/releases/v0.6.1.txt
seaborn/tests/test_axisgrid.py
seaborn/tests/test_utils.py
seaborn/utils.py

Adds an additional rule when determining category order in categorical plots.
Now, when numeric variables are used in a categorical role, the default
behavior is to sort the unique levels of the variable (i.e they will be in
proper numerical order). This can still be overriden by the appropriate
``{*_}order`` parameter, and variables with a ``category`` dtype will still
follow the category order even if the levels are strictly numerical.
Closes #626

Sort numerical category levels by default

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

To reproduce the problem this PR tries to fix, create a virtualenv without fastcluster and run [the code in this clustermap example](http://stanford.edu/~mwaskom/software/seaborn/examples/structured_heatmap.html). The rows and columns will be sorted in a different way than what is shown on that page.
When fastcluster is not installed, `_calculate_linkage_scipy` is used to
compute linkages. It contains an erroneous call to squareform().
distance.pdist() already returns a condensed distance matrix that is
required as input for the linkage() function. Converting it to a matrix
with squareform() is possible and linkage() will accept the resulting
matrix, but consider it to be a list of vectors of observations and run
distance.pdist() again on it. Thus, we get a linkage based on distances …

Compute linkage correctly when fastcluster is not installed

---

seaborn/rcmod.py
seaborn/tests/test_rcmod.py

Resolves #635. 
`font.size` was not being set by `rcmod`, which meant that text generated by `plt.text` and, e.g. tick labels in scientific notation were not scaled by `font_scale`. This is addressed by using matplotlib's default `font.size: 12` and scaling accordingly.

Add font.size to plotting context

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

This PR changes the behaviour of `xticklabels=False` (also `yticklabels=False`).
Instead of creating a list of empty tick labels (as it did before), it now just operates on an empty list.
This has the effect that `axis_ticklabels_overlap` does not do the expensive overlap calculation downstream. And thus the code runs faster.
For instance, try out the following code snippet:
```python
import fastcluster
import pandas as pd
import seaborn
ROWS, COLS = 1000, 10
np.random.seed(10)
random_data = np.random.randn(ROWS, COLS)
random_data = pd.DataFrame(random_data, 
index=['Row {}'.format(i) for i in range(ROWS)], 
columns=['Column {}'.format(i) for i in range(COLS)])
row_linkage = fastcluster.complete(random_data)
col_linkage = fastcluster.complete(random_data.T) …
```

Do not create heatmap labels, when labels are false

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Instead of plotting the dendrogram lines one by one using standard `ax.plot()`, this PR makes use  of the `LineCollection` object from `matplotlib` to draw them all at once.
This has the effect of significantly speeding up the time needed to draw the clustermap.
For instance, the following script:
```python
import fastcluster
import pandas as pd
import seaborn
from matplotlib import pyplot as plt
ROWS, COLS = 10000, 10
np.random.seed(10)
random_data = np.random.randn(ROWS, COLS)
random_data[ROWS/5: 2*ROWS/5, :] *= 10
random_data = pd.DataFrame(random_data, 
index=['Row {}'.format(i) for i in range(ROWS)], 
columns=['Column {}'.format(i) for i in range(COLS)])
row_linkage = fastcluster.complete(random_data)
col_linkage = fastcluster.complete(random_data.T) …
```

Use `LineCollection` when plotting dendrograms.

---

seaborn/tests/__init__.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py
seaborn/tests/test_linearmodels.py
seaborn/tests/test_matrix.py
seaborn/tests/test_miscplot.py
seaborn/tests/test_rcmod.py
seaborn/tests/test_utils.py

Closes #694.
After this we have:
```
~/dev/seaborn/seaborn/tests $ grep "plt.close" *.py | wc
98     196    4323
```
So `plt.close` shows up 98 times rather than 241. There are still so many because some tests call `plt.close` several times within one test method. Those can stay.
These tests are now more robust, since the `tearDown` method is called regardless of whether the test causes an unexpected exception.

use teardown method in PlotTestCase for most tests

---

seaborn/matrix.py

This PR actually does something I should have done in PR #683 that is already merged.
After PR #685 was merged, I ran the profiler again and noticed that quite peculiarly most of the time is now spent setting `yticks` when plotting a large number of rows. I never thought this would be the bottleneck, but disabling the ticks completely, when no ticklabels are given, brings down the runtime of the same test script as given in #685 to 5.7s (from around 30s, and from around 60s before dendrogram fix...). 
What is even better, `fastcluster` is now the biggest bottleneck of that example, not plotting!
As it should be! Woo-hoo!
Not really sure how I missed this when pushing #683. Anyway, it is an easy fix, and all tests seem to pass, so have yet  another PR (sorry for such a pile-up)!
Again, the …

Do not draw ticks at all if ticklabels are disabled

---

matplotlibrc
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/palettes.py
seaborn/rcmod.py
seaborn/tests/test_linearmodels.py
seaborn/tests/test_palettes.py
seaborn/timeseries.py
seaborn/utils.py

Closes https://github.com/mwaskom/seaborn/issues/711 and #732 
One oddity here is if a user has modified their `axes.prop_cycler` to be a cycler that doesn't include the `color` key. In this case we just fall back to `axes.color_cycle` and they'll get the warning. I actually think the changes I made to pandas missed this possibility and will just break :shrug:.
For Travis, want me to modify one of the `testing/deps_modern`? https://anaconda.org/conda-forge/matplotlib/files has RC1... not sure about a more up to date version.
I've got a couple (seemingly unrelated) failures to cleanup too. They fail for me on master so I'm not sure if that's another mpl 1.5 thing or what. Not sure if I'll get to that any time soon.
For the record, those failures are
``` …
```

COMPAT: compat with mpl 1.5 color cycle

---

seaborn/matrix.py

This fixes white lines appearing in the rendered PDF. See #373 .
Rendered PDF before :
Rendered PDF after :

Pass 'rasterized' to colorbar in sns.heatmap

---

seaborn/distributions.py

I get an error if I try to use jointplot.  
np.ceil returns a float, which causes  np.histogram(x[i], bins, weights=w[i], **hist_kwargs) to throw an error.
This is probably because I am using numpy version 1.11.0.dev0+cbc14f0 and not whatever version seaborn is built for.  In any case this is a simple fix and should help with future compatibility.

Force number of bins to be an integer.

---

seaborn/axisgrid.py

Using the cached `size` property on an `ndarray` must be faster than converting the array to a list, and it's more obvious what's going on to boot.
I can't imagine this makes much difference, but it might speed up plotting large datasets.

PERF: Speed up test for empty facet (trivial)

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

Avoid the problem where matplotlib thinks a stripplot with observations should be colormapped by passing hex-valued colors.
Closes #753

Avoid scatter issues

---

doc/releases/v0.7.0.txt
seaborn/categorical.py

- Avoids blue outliers by setting the `markerfacecolor` property rather than `color`
- Avoids a strange bug where some properties would revert to default when setting others through property dictionaries
closes #794; closes #787

Workarounds for matplotlib boxplot issues

---

seaborn/linearmodels.py
seaborn/tests/test_linearmodels.py

Avoids problem where matplotlib interprets rgb colors with three scatter
points as a variable to be colormapped.
Closes #802

Pass hex colors to regression scatterplot

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

This commit fixes Issue #830. Currently, ```mesh.get_facecolors()``` returns only the color code for one cell in the grid, but calling ```mesh.update_scalarmappable()``` changes this so that the color information is shown for all cells.

Update mesh colors before drawing annotations

---

seaborn/matrix.py
seaborn/tests/test_utils.py
seaborn/utils.py

Currently when annotating heatmaps the color of the text annotation is either white or gray based upon a contrast calculation. This pull request contains an improved contrast calculation to address an issue when using the viridis heatmap.
Currently the luminance is calculated by conversion to HSL and extraction of the luminance term, which is simply [the average of the highest and lowest RGB values](http://www.niwa.nu/2013/05/math-behind-colorspace-conversions-rgb-hsl/). This is then compared to a 50% cutoff to decide when to use white or gray text.
I am proposing adherence to the WC3 standards for [luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef) and [optimal contrast](https://www.w3.org/TR/WCAG20/#relativeluminancedef). Importantly these take into account how people view …

Change luminance calculations for Annotation color choice

---

examples/custom_map_diag_hist.py
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

This change gives the ability to pass in a specific histtype to map_diag to override the default behavior. The default barstacked behavior is retained if no histtype is passed into the function. This feature gives added functionality to map_diag without having to write a custom hist function just to use a different histtype. 
As a side note I wonder if barstacked is the best default behavior, barstacked has the annoying behavior that when passing in an array of samples the histograms are normalized to the total sample size instead of each histogram being independently normalized. Thus distributions with larger numbers of samples are larger in the resulting histogram. For my use cases this seems backwards, since a point of normalization is to compare distribution shape independent of …

Ability to override histtype when plotting PairGrid histograms

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Includes the proposed changes from #441 for supporting dataframe row_colors and col_colors in cluster map and using the column names as labels in the resulting plot. The current implementation allows supplying colors as dataframes, in which case columns as used as labels, or as a (named) series, in which case the name of the series is used as label (if the name is not None). 
The current implementation also matches the index of row_colors and col_colors to the data index/columns, to ensure that the order of the colors is coherent with the data. This may break current behaviour, but I personally feel that it is a welcome addition, as it ensures that your colors correspond properly with your data (this has bitten me before) and makes good use of the index/column annotation to do so. I do …

Support dataframes as col/row_colors in clustermap and use columns as annotation

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Small adjustments to #877. I discovered a small typo in checking for col_label_colors, which resulted in column color labels not being drawn if no row_label_colors were given. I also changed preprocess_colors to ensure that labels are now a simple list instead of a pandas Index object. Finally, I added some documentation of clustermap to reflect the addition of the Series/Dataframe functionality.
Sorry for the late changes, I didn't expect the pull request to be accepted that quickly after the first revision!

Fix missing labels in clustermap col_colors when row_colors not given

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

I think this fixes the end cap addition to barplot and scatterplot confidence intervals. Let me know what you think. It should pass all the automated tests. Let me know if there is anything wrong. I've attached some images, along with the python script I used to generate them. This should show you what the different parameters look like for different capsize and conf_lw. Major thanks to jat255 who did the initial work on this. This is my very first contribution to an open source project that is not my own. Let me know if there is anything else that needs to be done as far as style and/or code cleanup.
```python
##LINEPLOTS
g=None
sns.set(style="whitegrid")
df = sns.load_dataset("exercise")
g = sns.factorplot(x="time", y="pulse", hue="kind", col="diet", data=df, …
```

End caps on barplot confidence intervals #606 update

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

The `annot=True` flag in `sns.heatmap()` is very helpful:
```python
np.random.seed(314)
values = np.random.randint(low=0, high=1e6, size=20).reshape(4, 5)
values[2, 3] += 1000000
sns.heatmap(values, annot=True)
```
But sometimes I want to plot the percentages as the heatmap, but annotate with the original values. This is especially when some of the percentages are very low but I'd still like the raw value to tell them apart.
```python
percentages = 100*values/values.sum()
sns.heatmap(percentages, annot=True, annot_data=values, vmin=0, vmax=100)
```
This PR adds the keyword argument `annot_data=None` and allows the user to pass a dataframe/numpy array to use as the annotation. It doesn't check for whether the `annot_data` and `data` are the same …

Heatmap annotate values with other dataframe

---

seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/linearmodels.py
seaborn/matrix.py
seaborn/miscplot.py
seaborn/palettes.py
seaborn/rcmod.py
seaborn/tests/test_palettes.py
seaborn/timeseries.py
seaborn/utils.py
seaborn/widgets.py

Add explicit `__all__` declarations in seaborn modules to avoid importing 
With this change, `python -c 'import seaborn; print(len(dir(seaborn)))` shows 85 objects in contrast to 143 before the change.
It's possible that this could break some code if people are using objects in the top level namespace that aren't really part of the public API (in terms of what is documented and used in examples), but those functions still exist they just need to be explicitly imported.
Closes #904

Clean up top-level seaborn namespace

---

doc/_static/style.css

Title says all, simply some CSS that fixes the anchor link to doc pages

Fix header interference in doc linking, fixes #610

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Calculates correct number of subplots to draw when unused categories are present
The test confirms the fix solves the ValueError.
It also asserts that the number of axes drawn by FacetGrid should be equal to the number of categories in `.cat.categories`, not the number of unique values that are present in the series.

Fix #929: FacetGrid with unused categories

---

doc/releases/v0.8.0.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

A lot of people got confused by this and it didn't end up being that hard to change. Now this is possible:
```python
sns.boxplot(x="day", y="total_bill", hue="weekend", data=tips, dodge=False)
```

Allow use of hue without nesting bars/boxes/violins

---

seaborn/tests/test_categorical.py

while indexing hue_vals
debian <= jessie and ubuntu <= 15.10 were failing this test

BF(TST): explicitly request .values for sorter to stay compatible with older numpys

---

doc/sphinxext/plot_generator.py

This is a quick fix for #1039. This implements `execfile` in terms of `six.exec_` which should work on Python 2 and 3 alike. There are no tests for this part of the code, but I verified that docs build cleanly on Python 2 and 3 with this.
As an aside, I noticed that installing the docs requires quite a bit of extra packages (numpydoc, numexpr, ...). Is there a requirements file that describes what additional packages are needed to build the docs?

Use six.exec_ to mimic execfile on Python 3

---

README.md

Couldn't find the dev docs on the github pages, so I deleted those few lines.
#958

DOCS: update docs links and remove dev docs link

---

seaborn/external/husl.py

this fixes a bug that popped up when I was trying to use the `husl` module. Basically it's converting numbers to a scale of 255 and then calling `np.round`, but they're left as floats. This means that when they are converted to something like hex with `%02x`, it was returning an error because it required an int, not a float. This PR just explicitly turns RGB values into `int` after calling `np.round`.

fixing husl int bug

---

seaborn/tests/test_axisgrid.py

Matplotlib changed the axisbg parameter in 2.0. Test the projection instead (which is probably more useful).
Fixes #1098 
Fixes # #1025

Update tests for matplotlib 2.0 change

---

seaborn/utils.py

I edited a comment on load_dataset() in seaborn/utils.py, correcting the default path. A very small pull request, but the incorrect default data path caused me some confusion while I was trying to debug an issue with retrieving the iris data set behind a firewall.

Fixed documentation issue on load_dataset

---

doc/installing.rst
seaborn/tests/test_palettes.py

I suspect Travis failures involve some change in colormap generation in matplotlib 2.0.
Also closes #1101

Fix palette test

---

seaborn/axisgrid.py
seaborn/categorical.py
seaborn/matrix.py

Replaced str function calls with utils.to_utf8 to avoid unicode errors when labels had unicode in them. Tested with python 2.7.

Replace str with to_utf8 methods

---

seaborn/widgets.py

Ignore the `ShimWarning` raised by IPython when importing widgets from IPython instead of ipywidgets. This warning only confuses the user - "I didn't import `IPython.html`!" - and the dev already knows that he's using a deprecated API.
Fixes #892, #874.

Ignore warnings when importing widgets

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

This PR changes the way swarmplot checks for point overlaps.
The way it currently works:
1. Swarmplot tries placing each of the swarm points one-by one.
2. Each time finding all the points the newly-placed point could be overlapping (i.e. points that are within one diameter from the point [NB: I suspect code uses "diameter" when it actually means "radius" but it doesn't matter here]).
3. Then it proposes new locations for points to be to the left/right of these points.
4. The algorithm then loops through all of these proposed points and check if they overlap with any of the previously found neighbours. If they do, these points are removed (leaving only non-overlapping points).
5. The algorithm then selects the middle-most point of the remaining points and places the new point there. …

`sns.swarmplot` that scales better

---

seaborn/linearmodels.py
seaborn/tests/test_linearmodels.py

Instead, return an array of nans as yhat which will propogate through to no regression plot (when the data have a perfect separation) or no error bands (when at least one bootstrap sample has a perfect separation).
Arguably the nans should be pruned from at least the bootstraps, but this seems like a good way to indicate "something isn't quite right with the confidence intervals".

Don't fail on PerfectSeparationError in regplot logistic regression

---

doc/releases/v0.8.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

I think this is of somewhat dubious informational value but many people seem quite keen on it (#312) and it's reasonably compatible with the API for `heatmap` (though I still dislike how many arguments to `kdeplot` depend on the form of the input).

Add optional colorbar for bivariate KDE plots

---

seaborn/tests/test_categorical.py

Matplotlib apparently changed how barplot patches are defined so that they start at 0 and have a signed height instead of starting at the minimum value and having a positive height.
Fair enough, but that broke some seaborn tests. This PR updates the tests.

Fix test failures on matplotlib 2.0.2

---

seaborn/matrix.py

Remove 'robust' from kwargs before plotting clustermap colors  (#1173)
Don't label clustermap colors when Series has no name (#1177)

Small changes to clustermap

---

doc/releases/v0.8.0.txt
seaborn/categorical.py
seaborn/linearmodels.py
seaborn/tests/test_categorical.py
seaborn/tests/test_linearmodels.py
seaborn/timeseries.py

It's now possible to do `ci="sd"` in functions that draw error bars and the error bars will show the standard deviation of observations instead of boostrapped confidence intervals.
A little semantically confused, but better than adding new keyword arguments.

Show standard deviation of observations in error bars

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Will now show annotations on all cells regardless of what value
x/yticklabels take. Fixes #837.

Don't depend on ticks for heatmap annotations

---

doc/installing.rst
doc/releases/v0.8.0.txt
doc/tutorial/aesthetics.ipynb
seaborn/__init__.py
seaborn/apionly.py
seaborn/rcmod.py

In recognition of the substantial improvements in the matplotlib style defaults in 2.0, importing seaborn will no longer change the rcParams. It is now necessary to explicitly invoke ``sns.set()`` to get the default gray grid style. Correspondingly, the ``seaborn.apionly`` module has been deprecated.
Additionally, this PR updates a couple of style defaults for better compatibility with matplotlib 2.0+.

Don't set seaborn style on import

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Allows setting the `color` kwarg in `map_diag`, which then overrides seaborn's attempt to set the colors via the palette.
Example:
``` py
#1
g = sns.PairGrid(data)
g.map_diag(plt.hist, color=color)
#2
g.map_diag(sns.distplot, color=color)
```
The first (`plt.hist`) was possible before by giving `facecolor=color`; the second (`sns.distplot`) wasn't possible AFAIK.

Force color of plot in grid diagonal

---

seaborn/matrix.py

Trying to solve https://github.com/mwaskom/seaborn/issues/909, do linkage calculation in one step rather than two because of a weird compatibility issue with `scipy` 0.17 (https://github.com/scipy/scipy/issues/6180)

Use one-step linkage calculation with both scipy and fastcluster

---

seaborn/categorical.py

My dataset had less than two hue levels, and the resultant error message was confusing. Hopefully, this helps.

Better error message when using 'split' with less than 2 hues.

---

seaborn/axisgrid.py

There was a bug that FacetGrid.add_legend() with legend_out=True did not
work when the backend was "GUI"-based ones such as Qt5Agg and
NbAgg (checked with matplotlib 2.0.2).  Note that it was working
correctly with Agg backend.  This is likely because pyplot.draw calls
canvas.draw_idle() which may not force re-draw [1].
[1] https://github.com/matplotlib/matplotlib/blob/v2.0.2/lib/matplotlib/pyplot.py#L691
You can check the bug with the following script.
```python
def plot_with_backend(backend):
import matplotlib as mpl
mpl.use(backend)
tips = sns.load_dataset('tips')
g = sns.lmplot('total_bill', 'tip', tips, hue='smoker', fit_reg=False)
g.savefig(backend + '.png')
plot_with_backend('Qt5Agg')
```
Before this patch, it produces:
After this patch, it produces:

Fix legend_out with GUI backend

---

seaborn/axisgrid.py

added a check for the `data` argument in the pairplot function . Raises a `TypeError` if it is not a `DataFrame` . 
Fixes issue #1067

type check for pairplot

---

doc/releases/v0.8.1.txt
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/tests/test_axisgrid.py

It is risky to pass a categorical plotting function into `FacetGrid.map()` without providing order information. If category levels are not consistently present across all facets, the plot order and/or labeling is likely to be incorrect. `sns.factorplot` exists in part to handle this bookkeeping for people, but I still see lots of questions about unexpected behavior when using `sns.FacetGrid` directly. This change tries to predict when users are doing something risky and fire a warning to inform them.

Add warning in FacetGrid when drawing categorical plots

---

seaborn/distributions.py

fixes a "kenel" vs "kernel" typo

DOC: Fix typo in distplot docstring

---

doc/api.rst
doc/releases/v0.9.0.txt
examples/different_scatter_variables.py
examples/scatterplot_sizes.py
seaborn/basic.py
seaborn/tests/test_basic.py

This PR adds a scatterplot function that can set the color, size, and marker of the points based on semantic variables. Simple obvious example:
```python
sns.scatterplot(
x="total_bill", y="tip",
hue="sex", style="smoker", size="size",
data=tips,
)
```
More examples to come.
Possible functionality to be added in future development:
- Jittering
- Automatic point opacity for large datasets
- Aggregation and estimation similar to `lineplot`
Ultimately, this should also replace the underlying scatter plotter in `regplot` (and therefore `lmplot`), and perhaps more pressingly, should be used by default in `pairplot` and `jointplot`.
In principle the API here will work fine in `FacetGrid` but, similar to the case with the categorical plots, the ordering and limits for the various semantic …

Add scatterplot function

---

seaborn/regression.py

Fix typo in regplot x_ci parameter docs

---

seaborn/basic.py
seaborn/tests/test_basic.py

Adds the `err_kws` parameter; also renames `errstyle` to `err_style` for consistency.

Allow control over the error representation in lineplot

---

doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Also changes the `pairplot` defaults:
```python
sns.pairplot(iris, hue="species")
```

Remove special-cased stacked diagonal histograms in PairGrid

---

doc/releases/v0.9.0.txt
seaborn/basic.py
seaborn/palettes.py
seaborn/tests/test_basic.py
seaborn/tests/test_palettes.py

e.g.
```python
sns.palplot(sns.color_palette("cube:.1,-.2,hue=1,dark=.3"))
```
This means it can be used in any seaborn function with a `palette` kwarg:
```python
sns.boxplot(x="subject", y="signal",
palette="cube:.1,-.2,hue=1,dark=.3",
data=fmri)
```
Needs:

Allow interface to cubehelix through color_palette

---

doc/releases/v0.9.0.txt
doc/tutorial/color_palettes.ipynb
seaborn/palettes.py
seaborn/rcmod.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_palettes.py
seaborn/tests/test_rcmod.py

This PR changes the named seaborn color palettes (i.e. "deep", "muted", "pastel", "bright", "dark", and "colorblind"). It expands them to 10 colors that correspond to the 10 colors in the new matplotlib default palette ("tab10").
The old palettes can be used by appending "6" to the name (e.g. "muted6").
There's also a new image in the tutorial docs showing off all the color palettes with some information about how they're related:
(If of interest, I've also generated this image while simulating [various forms of color deficiency](https://gist.github.com/mwaskom/b35f6ebc2d4b340b4f64a4e28e778486).)
Additionally, a few colors in the non-default seaborn palettes have been tweaked for better aesthetics/consistency/colorblind accessibility.
The other change here is that calling …

Update color palettes to 10 colors

---

doc/releases/v0.9.0.txt
seaborn/basic.py
seaborn/palettes.py
seaborn/tests/test_basic.py
seaborn/tests/test_palettes.py

These enhancements clean up some open issues in `scatterplot`/`lineplot`:
- Renamed `{hue,size}_limits` to `{hue,size}_norm` and allowed them to accept and use a matplotlib `Normalize` object. There is some support for using the LogTicker to generate brief legend ticks (but see https://github.com/matplotlib/matplotlib/issues/11518); other kinds of normalization are not associated with other ticks, but are less likely to be used.
- Binary data (i.e. data with only 0s or 1s) is treated as categorical by default instead of getting the ends of the default numeric colormap and weird legend "ticks"
- Raise on getting a mixture of  filled and unfilled markers, otherwise the unfilled markers will be drawn with the edgecolor (white by default, causing them to appear invisible).
- Changed the …

Additional enhancements to basic plots

---

doc/conf.py
doc/introduction.ipynb

Adds intersphinx to the documentation configuration. 
Also: changes to the introduction notebook to link to MPL and Pandas documentation.

Intersphinx

---

seaborn/basic.py
seaborn/tests/test_basic.py

This PR adds invisible artists to the axes that can be used as subtitles in a legend for a plot with multiple semantics:
The downside is that the subtitles are stuck in the right column with other labels. See planned enhancements in #1440, but I'm also interested in other, better long-term solutions. (First-class support for sectioned legends in matplotlib would be ideal).
Closes #1440

First approach to relational plot legends

---

doc/api.rst
doc/introduction.ipynb
doc/releases/v0.3.0.txt
doc/releases/v0.3.1.txt
doc/releases/v0.4.0.txt
doc/releases/v0.6.0.txt
doc/releases/v0.7.1.txt
doc/releases/v0.9.0.txt
doc/tutorial/axis_grids.ipynb
doc/tutorial/categorical.ipynb
doc/tutorial/relational.ipynb
examples/grouped_barplot.py
examples/large_distributions.py
examples/pointplot_anova.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/relational.py
seaborn/tests/test_categorical.py

Moderately disruptive but well-intentioned changes herein:
First:
I've decided to abandon the original R-inflected name for `factorplot` and change it to `catplot`, which better corresponds to the appropriate terminology in pandas (and the terminology that is used more broadly in seaborn).
Along with a better name, it gives the opportunity for a less-disruptive approach to changing the default kind to "strip", which is a much better place to start with categorical plotting. (Originally factorplot *only* drew what are now called point plots, and it kept that default when it was expanded to a more general interface to categorical plots).
The other part of the change is to make `jitter=True` the default in `stripplot`. I found myself setting this 98% of the time I made a stripplot, which is …

Rename factorplot to catplot and change the default plot kind to strip

---

doc/_static/style.css

I added the [css from the jupyter-notebook](https://github.com/jupyter/notebook/blob/c8841b68c4c0739bbee1291e0214771f24194079/notebook/static/notebook/less/renderedhtml.less#L59-L90) to style the tables in the documentation. I modified it slightly to left-align instead of center (to be consistent with what you had previously) and removed a couple of references to `@rendered_html_border_color`.

Format doc tables similar to the Jupyter Notebook

---

doc/index.rst

Clicking the introduction, installation and API links on the front page causes the section heading to be hidden under the navbar. Linking to the page with `:doc:` instead of the specific heading with `:ref:` does not have this problem. The example gallery and tutorial links were working fine with `:ref:` so I didn't touch those.

Reference with :doc: to avoid hiding titles under the navbar

---

doc/_static/style.css

Minor suggestion. Reduce the padding between the navbar and section headings so that it is more similar to how close top level headings are to the navbar.

Reduce navbar padding to resemble top level links

---

seaborn/regression.py

The proposed change in this PR is to replace a call to `plt.plot()` with `ax.plot()` in `_RegressionPlotter` in regression.py. The reason for the change is to solve problems that emerge when `regplot()` is used to plot data on a figure with multiple axes. (See issue #1568) 
A side effect of this change is that multiple calls to `regplot`, each on a different axes, will now be plotted in the same colour by default, as opposed to each using different colours, as is the case now. However, using the same colour will also be more consistent with `lmplot`.
The behaviour of `regplot` when not using multiple subfigures, or not specifying an `ax` is unchanged.

fixing regplot to work with multiple subplots

---

seaborn/relational.py

To fix the issue I was seeing on #1515, I added a check that overrides the variable type returned by `_semantic_type()` if the data is a Pandas categorical type. I agree that it makes sense to convert numeric strings into numbers since, as you said in #1515,
>it is not uncommon in pandas (i.e. the data library most commonly used with seaborn) to have numeric data stored with an object datatype, for example if you have integers and missing data.
but I can't think of a case where a series would be a categorical variable if the user didn't explicitly do that. Please let me know if I'm mistaken.
Let me know if you're open to a change like this, and I can look into adding necessary tests for this.

[WIP] Add check for categorical hue variable (fixes #1515)

---

seaborn/matrix.py

The Tick.label property will be deprecated and begin warning in a
future version of Matplotlib.  Explicitly using the correct property
will avoid this.
See https://github.com/matplotlib/matplotlib/pull/10088 and
https://github.com/matplotlib/matplotlib/pull/13631

MNT: tweak access to tick label to avoid warning

---

seaborn/axisgrid.py

Issue #1598 describes a bug where using ``g.set_xticklabels(rotation=rotation)`` on an FacetGrid that has ``row`` faceting (with ``sharex=True``) makes the xtick labels (that are on the bottom row only) disappear. This is due to local variable overriding with the xtick labels from hidden empty labels introduced by #1384 and is fixed by this PR:
See the conversation in #1313 regarding the possibility of adding a rotation function to the FacetGrid API. 
Fixes #1598 
Fixes #1743

Fix grid ticklabels rotation

---

examples/jitter_stripplot.py
seaborn/categorical.py

PR #1490 made ``jitter=True`` the default for ``stripplot()``. This PR incorporates the change into the docs and examples.

Update stripplot docs and examples with jitter=True default

---

seaborn/categorical.py

Categorical plots use a private ``matplotlib.legend`` field for setting the legend title size when ``hue`` is used. The proposed PR uses the public API to do so.

Remove access to private legend field

---

seaborn/distributions.py

In documentation of "distplot", argument "fit", Fix typing error : "an grid" --> "a grid"

Fix doc typing error : "an grid" --> "a grid"

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

Horizontal boxenplots log warnings from ``matplotlib`` due to incorrect color input to scatterplot of the outliers (see #1629 ). The proposed PR makes horizontal plots color usage equal to vertical plots. 
Fixes #1629

Fix horizontal boxenplot warning

---

seaborn/tests/test_utils.py
seaborn/utils.py

Matplotlib 3.1.0 introduced deprecation warnings to ``tick1On`` and ``tick2On``. The proposed PR fixes these (and also fixes a typo in the test method's name).

Handle matplotlib 3.1.0 tick1On/tick2On deprecation warnings

---

seaborn/distributions.py

Distplot bins documentation is misleading. If Freedman-Diaconis rule gives a value greater than 50, 50 will be used as the bin size.

Fix documentation on distplot bins

---

doc/releases/v0.9.1.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py
seaborn/tests/test_matrix.py

The approach here is to fire a warning and add an empty line artist to the axes rather than let the statistical machinery barf when the input data are singular. This will keep `pairplot` from being non-functional, although the warnings might be confusing or annoying. Perhaps best considered a stop-gap measure. Another option might be to plot a delta function at the singular value. But that's kind of wrong, because really the delta function should be convolved with the kernel. But then *that* would be very misleading about what's going on too. So I guess I've convinced myself this is best for now.
Fixes #1502
Fixes #1699

Don't error on singular data in kdeplot

---

doc/api.rst
doc/releases/v0.9.1.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

A number of small enhancements are combined here:
- Added the ``corner`` option to :class:`PairGrid` and :func:`pairplot` to make a grid with only the lower triangle of bivariate axes. (I don't believe there is an open issue about this but there's a [popular SO question](https://stackoverflow.com/questions/34087126/plot-lower-triangle-in-a-seaborn-pairgrid).)
```python
iris = sns.load_dataset("iris")
g = sns.pairplot(iris, height=1.5, corner=True)
```
- Generalized the idea of "diagonal" axes in :class:`PairGrid` to any axes that share an x and y variable. (Closes #1125)
```python
iris = sns.load_dataset("iris").drop("species", axis=1)
g = sns.PairGrid(iris, height=1.5, x_vars=iris.columns, y_vars=iris.columns[:3])
g.map_diag(sns.kdeplot)
g.map_offdiag(sns.scatterplot)
```
- In …

Enhancements and fixes to PairGrid

---

seaborn/rcmod.py
seaborn/tests/test_rcmod.py

Running ``sns.set(palette=pal)`` with ``pal`` created through ``color_palette()`` fails without specifying ``color_codes=False``(#1546 ). The proposed PR uses ``color_codes=False`` in case of a non-string palette input.
Fixes #1546

Avoid mapping color codes for non-string palettes in sns.set()

---

.travis.yml
setup.py

In addition to ``python=3.8`` CI support, this PR also adds ``conda-forge`` channel when resolving dependencies (removed by [previous commit](https://github.com/mwaskom/seaborn/commit/24542c79aafd6d59795204cd7ceeb1a5c5192053)) - this ensured ``matplotlib=3.1.2`` support as well (still not available through the ``defaults`` conda channel).

Support Python3.8

---

seaborn/palettes.py

The default colors in `set_color_codes()` (used for `palette = "reset"`) uses the wrong color code for m (magenta) and instead duplicates yellow. Fixing this only requires changing the RGB numbers for the array entry associated with magenta.

Fix default color codes.

---

seaborn/relational.py
seaborn/tests/test_relational.py

Providing dict/list ``sizes`` input on numeric column for ``scatterplot`` fails on missing ``norm`` at the time of legend drawing. This PR treats numeric size variable as categorical if dict/list ``sizes`` input is provided and so the ``norm`` lookup is avoided. This is consistent with the current ``hue`` treatment for dict/list palette input. 
Fixes #1570

Treat scatter size variable as categorical on list/dict sizes input

---

seaborn/relational.py
seaborn/tests/test_relational.py

The current behavior of relational plots considers binary values as categorical for ``hue`` or ``size`` purposes, but only if both 0 (or ``False``) and 1 (or ``True``) values present in the data (see #1722). This PR makes relational plots consider single-valued binary data in the ``hue`` and ``size`` columns of relational plots as categorical.
Fixes #1722

 Consider binary hue data with one unique value categorical (#1722)

---

seaborn/relational.py
seaborn/tests/test_relational.py

Issue #1693 describes a bug where providing ``hue`` (or ``style``) with a pandas column of type ``np.datetime64`` to scatterplot results in no points plotted. This PR fixes both ``hue`` and ``style``.

Support numpy datetime64 datatype in scatter hue/style (fixes #1693)

---

doc/releases/v0.9.1.txt
seaborn/regression.py
seaborn/tests/test_regression.py

- Check dimensionality of input and error out when net vectors
- Don't crash when partialling variables are passed as pandas series

Two small fixes in regplot

---

seaborn/relational.py
seaborn/tests/test_relational.py
seaborn/tests/test_utils.py
seaborn/utils.py

Issues #1653 and #1703 describe relational plots legend entries that look affected by some floating point calculations. This is due to non-rounded values returned by matplotlib's ``ticker`` used for obtaining the hue/size legend entries. The proposed PR fixes this behavior by using matplotlib formatters on the obtained tick values to get a nice string representation.
Fixes #1653 
Fixes #1703

Format numeric legend entries in relational plots

---

doc/releases/v0.9.1.txt
seaborn/palettes.py
seaborn/relational.py
seaborn/tests/test_palettes.py
seaborn/tests/test_relational.py

e.g. 
```python
sns.lineplot(x=[0, 1, 0, 1], y=[0, 1, 1, 2], hue=[0, 0, 2, 2], palette="deep")
```
Also added some more information to the relational plot docstrings about what's going on here.
Addresses #1653 and others

Allow named categorical palette to force interpretation of hue variable in relational plots

---

seaborn/axisgrid.py

This fixes #1561  , and handles both cases where ``Grid.add_legend(loc="location")`` is provided where the grid was either initialized with ``legend_out=True`` (currently the default) or ``legend_out=False``.

Don't fail on 'loc' kwarg for Grid.add_legend()

---

seaborn/relational.py
seaborn/tests/test_relational.py

Follow-up fix to #1515. (#1905 avoided the error but lead to some cases where the plot would appear with no data. Oops).
The problem was that relplot internally sets up  the palette dictionary and then passes it to the axes-level  functions, causing them to treat the variable as categorical. (The palette is always made and used internally, but this is a good heuristic for avoiding the numeric mapping). The solution is to treat the presence of `hue_norm` or `size_norm` as a signal that the respective semantic variable should be treated as numeric, superseding the inference related to the palette.

Allow presence of norm to force numeric interpretation of hue/size

---

.travis.yml

The proposed PR allows for conda4.8 to install and run, including tests on python3.5. Builds for python3 are also faster by ~15% by downloading the proper miniconda. The only test mode that requires conda4.6.14 is python2.7 with pinned dependencies.

MNT: Fix Travis-CI tests with latest conda

---

seaborn/categorical.py
seaborn/regression.py

* corrected a few links under catplot examples in boxplot and pointplot
* corrected residplot "see also" link to jointplot
* added some cross-refs to catplot ("see also") 
* added kwargs description for stripplot, as this is directly shown in the code examples below. Notably, several categorical plots accept kwargs in their signature but it is not described below them, perhaps because they don't use the kwargs input - this may needs to be looked at (examples: boxenplot, violinplot, pointplot).

DOC: Fix broken/misleading links and add catplot cross-refs

---

doc/releases/v0.9.1.txt
seaborn/algorithms.py
seaborn/categorical.py
seaborn/regression.py
seaborn/relational.py
seaborn/tests/test_algorithms.py
seaborn/tests/test_categorical.py
seaborn/tests/test_regression.py
seaborn/tests/test_relational.py

Alternative to #1925 that exposes a seed argument on a per-function basis and has no global state.
Closes #1924

Expose RNG seed where bootstrapping is used

---

doc/releases/v0.9.1.txt
seaborn/matrix.py
seaborn/tests/test_matrix.py

- Adds more control over the layout of the grid and improves how the default layout scales with different sizes/shapes of the figure. This follows up on the work done in #1393, but it changes the parameterization to work in terms of ratios instead of inches. It also lets row/col ratios be specified independently. And it adds a parameter for the location of the colorbar (#1598).
- Fixes a bug where the annotation array was not clustered to match the heatmap (#1752) 
- Avoids printing the fastcluser ImportError when an exception is raised from within scipy clustering, which confused people who don't read entire stacktraces and lead to errant bug reports (#1370)
Needs
Fixes #437
Closes #891
Closes #1393
Fixes #1752 
Closes #1753

Improvements and fixes to clustermap

---

seaborn/axisgrid.py
seaborn/distributions.py
seaborn/matrix.py
seaborn/regression.py
seaborn/tests/test_axisgrid.py

Some plotting functions alter input dicts. Example:
```python
import seaborn as sns; sns.set(color_codes=True)
tips = sns.load_dataset("tips")
empty_dict={}
g = sns.jointplot(x="total_bill", y="tip", data=tips, joint_kws=empty_dict)
print(empty_dict) 
>>> {'color': (0.2980392156862745, 0.4470588235294118, 0.6901960784313725)}
```
The proposed PR makes sure the original dict input for such functions remains unaltered by shallow copying these dictionaries.

Avoid altering input dicts

---

doc/releases/v0.9.1.txt
examples/pair_grid_with_kde.py
seaborn/axisgrid.py
seaborn/distributions.py
seaborn/tests/test_distributions.py

This adds onto #1777, but simplifies the error checking. Disallowing color= and colors= breaks in a Grid context (hence the failing tests in #1777), and the other checks just duplicate what happens in matplotlib. It also adds a test that would have failed before the change.
I also updated a couple of examples and changed a few issues in the examples that I caught while doing so.
Closes #1777 
Fixes #1748

Allow colors= in bivariate kdeplot

---

setup.cfg

setup.cfg contains information relevant to the creation of the wheel distribution (when running `python setup.py bdist_wheel`).
* `universal = 1` means create a universal wheel, i.e. one that is not only "pure Python" but matches both Python 2 and 3 versions. Currently the [wheel on PyPI](https://pypi.org/project/seaborn/#files) is for Python 3 only although this package is compatible with both versions.
* `license_file` is the directive for including the license file in the "dist-info" folder inside the wheel (the manifest makes the license included in the sdist, but not the wheel).

Add setup.cfg for the wheel distribution

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

This enables use of tight_layout within clustermap. Ideally most plots will
now have everything in the figure and looking nice out of the box. It uses
a somewhat hacky approach that should be revisted as constrained_layout matures.
e.g., here is what a QT window looks like for the following code, with no other adjustments:
```python
iris = sns.load_dataset("iris").drop("species", axis=1)
g = sns.clustermap(iris,
col_cluster=False,
yticklabels=False,
figsize=(7, 6),
dendrogram_ratio=(.15, .12),
cbar_pos=(.3, .95, .55, .04),
cbar_kws={"orientation": "horizontal",
"label": "Measurement (mm)"})
```
Also updates the docs a little bit and adds a rule where cbar_pos=None implies
that no colorbar will be drawn.

More improvements to clustergrid layout

---

seaborn/miscplot.py

I really like this easter egg :-)
However, when you suggest someone to use `dogplot` instead of `catplot`, they will receive a `TypeError` explaining that they provided too many arguments. This kind of spoils the fun. What about making it more tolerant?

Make dogplot more tolerant

---

seaborn/algorithms.py

`np.array.take` requires that the index be the platform integer type (`int32` for 32bit and `int64` for 64bit), but `np.random.RandomState.randint` returns an `int64` on any platform by default.  This makes sure it returns the right type of integer for the current platform.
Fixes mwaskom#1950

Use the correct platform integer type

---

seaborn/regression.py

The docstring for `truncate` is out of date given the new default is `True`

DOC: update truncate parameter string to reflect new default

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

When ``heatmap`` is fed with both ``cmap`` and ``center`` arguments, it creates a new colormap but the props of the input cmap are not copied (colors for under/over/bad values). The proposed PR copies the props of the input cmap to the new cmap internally used within the heatmapper. 
Fixes #1729

Copy props from old cmap when creating new cmap in heatmap

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Masked cells are ignored from heatmap annotations and are not color-mapped, however they currently participate in cmap limits calculation. This is not documented, and seems surprising to some users (#1622 , #1617). Furthermore, Matplotlib's ``pcolormesh`` (used by heatmap) does not use masked cells in cmap limits calculation. This PR makes data limits calculation ignore masked cells. 
Fixes #1617 
Fixes #1622

FIX: Ignore masked cells when finding heatmap data limits

---

doc/sphinxext/gallery_generator.py
seaborn/algorithms.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/matrix.py
seaborn/miscplot.py
seaborn/palettes.py
seaborn/rcmod.py
seaborn/regression.py
seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_palettes.py
seaborn/tests/test_rcmod.py
seaborn/tests/test_regression.py
seaborn/tests/test_relational.py
seaborn/tests/test_utils.py
seaborn/utils.py
seaborn/widgets.py

With the update of minimal supported versions, some code paths may be removed. This PR removes such code paths for unsupported ``pandas``, ``matplotlib`` and ``scipy`` versions. It also modifies some tests to ensure ``pandas==1.0.0`` compatibility. 
Fixes #1942

MNT: Remove unused code paths

---

seaborn/tests/test_palettes.py
seaborn/tests/test_utils.py
seaborn/utils.py

* No longer fail when the global property cycler has no color configured- ~~use "k" instead (as matplotlib does)~~ use "0.15" instead ("dark gray" as set in ``sns.set()``)
* Improved ``get_color_cycle`` docstring and added tests
Fixes #1977

FIX: avoid error when prop_cycle has no color

---

doc/releases/v0.10.1.txt
seaborn/tests/test_utils.py
seaborn/utils.py

Avoid error in despine when axis has matplotlib categories

---

doc/tutorial/color_palettes.ipynb

As a result of https://github.com/axismaps/colorbrewer/issues/28 URL https://colorbrewer2.org/ is working now :tada: so here's one last update regarding https. Best! :beers: 
Related to:
- issue #1984
- pull request #1985

Make remaining links use https:// (issue #1984, follow-up to #1985)

---

seaborn/axisgrid.py

It gets populated when `legend_out` is `True`, but not when it is `False`.
This patch fixes this consistency problem.

Fix `add_legend` to always populate `_legend`

---

doc/releases/v0.9.1.txt

varaible -> variable
diffent -> different
passig -> passing

Added fix for minor typos in 0.9.1 release notes

---

seaborn/axisgrid.py
seaborn/categorical.py
seaborn/rcmod.py
seaborn/tests/test_categorical.py

`legend.fontsize` rcparam is a part of seaborn context. However the legend title isn't, and the title font size is taken as 85% of `axes.labelsize` rcparam. `legend.title_fontsize` rcparam [has been added](https://github.com/matplotlib/matplotlib/pull/11172) in 
`matplotlib==3.0`. This PR incorporates `legend.title_fontsize` rcparam into seaborn, for both plotting functions and rcmod context (which was set to 12, one point above `legend.fontsize` which currently equals 11). 
The change, if accepted, affects categorical plots, `lmplot` and `pairplot` but not relational plots, as they currently use an empty handle to draw a title-like line.

ENH: Handle`legend.title_fontsize` rcparam

---

doc/releases/v0.10.1.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #1990
Related to https://github.com/statsmodels/statsmodels/issues/5419
This PR takes the same approach to making kdeplot robust to statistical corner cases as when the variance of the data is 0.
The current behavior is to warn and plot an empty line only when statsmodels raises a `RuntimeError` *and* the IQR of the data is 0. Therefore, we shouldn't ignore other unrelated `RuntimeError` instances, and if the statsmodels behavior changes in the future not to throw an error, the code won't take this path. The test for this behavior tries to anticipate a change in statsmodels by asserting that a warning appears only when the statsmodels bandwidth selection raises.
This PR also removes a conditional that added compatibility for an older, no-longer supported version of scipy.

Avoid seeing an error from statsmodels in kdeplot when data IQR == 0

---

doc/releases/v0.11.0.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Currently set to warn when > 2% of the points overlap; with a little playing
around, this seemed like where the distribution started to get obscured.
But it is ad hoc.

Add explicit warning in swarmplot about gutters

---

doc/releases/v0.11.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

- Add the `FacetGrid.axes_dict` attribute which allows name access to the axes.
- Calling `FacetGrid.set_axis_labels` will turn off the labels on the interior of the grid in addition to setting the ones on the exterior.

Make FacetGrid a bit more convenient

---

.gitignore
doc/releases/v0.11.0.txt
seaborn/_decorators.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/matrix.py
seaborn/regression.py
seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_decorators.py
seaborn/tests/test_distributions.py
seaborn/tests/test_regression.py
seaborn/tests/test_utils.py
seaborn/utils.py

This PR is a major and long-desired change that leverages Python 3 functionality to require most parameters to be defined with keyword arguments.
Most of the functions in the seaborn plotting API have a signature that looks roughly like:
```python
def plot(x, y, [semantic_vars, ...], data=None, [other_params, ...], **passthrough_kwargs):
...
```
Where `semantic_vars` are `hue`, `style`, etc.
This PR will enforce that ~~`data` and all subsequent params~~ most parameters, aside from those that specify data positions, be specified with explicit keyword arguments.
The motivation for requiring keyword arguments is that, when functions have long signatures, one would like to order the parameters in ways that are more meaningful than chronology. This is very much the case in seaborn, where a …

Require keyword arguments for most parameters

---

doc/releases/v0.11.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

The distribution plots (`distplot`, `kdeplot`, and `rugplot`) are the oldest functions in seaborn and predated the common API, so their input parameters had unusual names.
This PR deprecates the old names and replaces them with `x` and `y` like in other functions.
Ultimately, there will be a full refactoring of these functions to accept input data like all the other seaborn plotters, either as vectors or names that index into a data object. This is the first step of that process.

Standardize parameter names in distributions module

---

doc/releases/v0.11.0.txt
doc/requirements.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

The matplotlib `tight_layout` algorithm ignores figure-level legends, which causes problems with `FacetGrid` and `PairGrid` if you need to tighten the layout after adding the legend:
```python
mpg = sns.load_dataset("mpg")
g = sns.relplot(
x="horsepower",
y="mpg",
size="weight",
sizes=(40, 400),
alpha=0.5,
height=6,
data=mpg,
)
g.fig.tight_layout()
```
This PR adds a `tight_layout` method on the `Grid` class that keeps the axes from overlapping with the legend:
```python
g = sns.relplot(
x="horsepower",
y="mpg",
size="weight",
sizes=(40, 400),
alpha=0.5,
height=6,
data=mpg,
)
g.tight_layout()
```

Add tight_layout method on FacetGrid and PairGrid

---

doc/releases/v0.11.0.txt
seaborn/core.py
seaborn/relational.py
seaborn/tests/test_core.py
seaborn/tests/test_relational.py

The relational plots raise an error when the number of levels on the `style` semantic exceeds the number of dash or marker styles provided. There are only 8 default markers and 6 default dashes.
This is especially surprising with wide-form data, where the style semantic is used implicitly.
See https://github.com/mwaskom/seaborn/issues/1513 for more discussion.
The challenge is that there is no idea approach. Either you a) error, b) cycle, or c) generate markers/dashes that are difficult to visually discriminate.
The errors are annoying, and in some situations, perplexing. I am opposed to having semantic attributes cycle; I don't believe that happens anywhere in seaborn. So we have to do our best to generate discriminable mappings.
This PR implements programatic generation of arbitrarily …

Programmatically define arbitrarily large style mappings

---

doc/releases/v0.11.0.txt
seaborn/relational.py
seaborn/tests/test_relational.py

`scatterplot` defaults to a thin white edge around each point; but for small points, this can dominate the points themselves.
This PR changes the default behavior to scale the line widths based on the actual sizes of the points that are drawn.
Here's an example using `diamonds`:
<details><summary>Open to see code</summary>
```python
import pandas as pd
import seaborn as sns; sns.set()
import matplotlib as mpl
import matplotlib.pyplot as plt
diamonds = sns.load_dataset("diamonds")
f, ax = plt.subplots(figsize=(6.5, 6.5))
clarity_ranking = ["I1", "SI2", "SI1", "VS2", "VS1", "VVS2", "VVS1", "IF"]
sns.scatterplot(x="carat", y="price",
hue="clarity", size="depth",
palette="ch:r=-.2,d=.3_r",
hue_order=clarity_ranking,
sizes=(1, 8),
rasterized=True,
data=diamonds, ax=ax)
``` …

Scale the default scatterplot edge width by the point radius

---

doc/releases/v0.11.0.txt
seaborn/relational.py
seaborn/tests/test_relational.py

Stricter input checks in matplotlib caused this to start failing; now it should work again.
```python
x = y = [1, 2, 3]
s = [100, 200, 300]
c = sns.color_palette("bright", 3)
style = "a", "b", "c"
sns.scatterplot(x=x, y=y, s=s, c=c, style=style)
```

Allow vectors for c= or s= in scatterplot

---

doc/releases/v0.11.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

<details><summary>Open to see code</summary>
```python
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, row="sex", col="time", margin_titles=True)
g.map(sns.kdeplot, "total_bill")
g.set_titles(col_template="{col_name}", row_template="{row_name}")
```
</details>
New behavior:
Previous behavior:

Improve FacetGrid margin titles to not show previous texts

---

doc/releases/v0.11.0.txt
doc/tutorial/axis_grids.ipynb
doc/tutorial/categorical.ipynb
doc/tutorial/color_palettes.ipynb
doc/tutorial/distributions.ipynb
doc/tutorial/regression.ipynb
doc/tutorial/relational.ipynb
examples/cubehelix_palette.py
examples/distplot_options.py
examples/hexbin_marginals.py
examples/joint_kde.py
examples/marginal_ticks.py
examples/regression_marginals.py
examples/residplot.py
seaborn/_decorators.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/regression.py
seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_decorators.py
seaborn/tests/test_distributions.py
seaborn/tests/test_regression.py
seaborn/tests/test_relational.py

In #2052, a warning was added that keyword-only arguments would be enforced for all parameters except `x` and `y` (or `data`, for those functions where `data` is the first parameter).
Thinking further, and based on the work in #2071 to improve wide-form data handling, I think it makes sense to require explicit keywords arguments for *all* semantics. Then, the parameters can be rearranged so that `data` comes first in every function. This has several benefits:
- every function will have the same basic signature
- easier to pipe pandas dataframes into seaborn plots
- calling `func(data)` will do something useful for almost any kind of `data`, which is not true if `x` is the first parameter.
Fixes #2066

Require keyword arguments almost everywhere

---

doc/installing.rst
doc/releases/v0.11.0.txt
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/conftest.py
seaborn/core.py
seaborn/relational.py
seaborn/tests/test_categorical.py
seaborn/tests/test_core.py
seaborn/tests/test_relational.py
seaborn/utils.py
setup.py
testing/deps_pinned.txt

This PR refactors the code that infers the type of a variable in `plot_data`. It also changes the way that seaborn handles object-typed data.
Seaborn has traditionally distinguished between two variable types: numeric and categorical. The standard way of discriminating was to ask whether a vector could be coerced to a float dtype without error.
The idea is that seaborn is trying to duck-type here: we don't care about data storage, just what we can do with the data (for instance, whether we can use a quantitative color map). The typing API in pandas treats object-typed data (including Python lists) as non-numeric, but it's not uncommon to end up with a Series that has an object dtype despite being full of numbers.
One consequence of this approach is that numbers explicitly represented as …

Centralize and modify variable type inference

---

doc/releases/v0.11.0.txt
seaborn/relational.py
seaborn/tests/test_relational.py

Improve lineplot handling of mpl kwargs

---

doc/conf.py
examples/multiple_joint_kde.py

This PR contains two small fixes to seaborn docs:
* Update kdeplot example to use keyword-only arguments, avoiding a warning
* Update intersphinx path to new numpy docs location

DOC: small fixes

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

`heatmap` on integer data and a mask fails when calculating cmap limits (#2102). This bug was introduced by #1956 so should work on any version prior to 0.10.1 (I tested on 0.9.0 and it works there). This PR fixes the issue by casting the data input to float before filling with `np.nan`.
Fixes #2102

FIX: don't fail on heatmap with int data and mask

---

doc/releases/v0.11.0.txt
seaborn/_core.py
seaborn/conftest.py
seaborn/relational.py
seaborn/tests/test_core.py
seaborn/tests/test_relational.py

Fixes #2130
Also addresses the `lineplot` example in https://github.com/mwaskom/seaborn/issues/2056; lineplot can now have a datetime (or categorical) `y` variable and aggregate across it.
Eventually, a similar approach can be used in all the categorical plots. (But it will take more refactoring).
This ran into some issues with an old conflict between pandas and matplotlib, summarized here and in various linked issues: https://github.com/matplotlib/matplotlib/issues/9610
Pre pandas 1.0 (I think?), they registered their own datetime converters, but those converters are less powerful than what matplotlib added in 2.2 (and what seaborn needs to make e.g. `comp_data` work).
I think seaborn wants to avoid mucking with the matplotlib converter registry, which unfortunately means that users on …

Improve support for datetime (and categorical) data in relational plots

---

seaborn/utils.py

When `fig` and `ax` are both specified, `ax` is ignored and all axes in `fig` are despined. Took me a while to figure out, so I clarified the documentation.
I think in this case it would be better to despine `ax` and ignore `fig`, but I realize this is undesirable as it might break some code out there.
I also thought of adding an explicit warning, would this be excessive? For example:
```
elif fig is not None:
axes = fig.axes
if ax is not None:
warnings.warn('ax parameter ignored when fig is specified')
```

Clarified documentation of despine

---

doc/api.rst
doc/docstrings/ecdfplot.ipynb
doc/docstrings/histplot.ipynb
doc/releases/v0.11.0.txt
seaborn/_docstrings.py
seaborn/_statistics.py
seaborn/distributions.py
seaborn/tests/test_distributions.py
seaborn/tests/test_statistics.py

This PR adds a new function in the distributions module, `ecdfplot`.
Simple example:
```python
sns.ecdfplot(diamonds, x="price", hue="cut")
```
There's some motivation for it in #1536 
There was an initial attempt in #1621, but the overhaul to the distributions module made it unfortunately impossible to pull those commits into the history
There's really not too much to the implementation.
We could add more semantics than just `hue` fairly easily, but because the other distribution plots don't support them well, I have deferred for the moment. They can always be added later.
We could also do a bivariate ECDF plot. But I am not sure this is very useful. The main advantage of the ECDF over histogram/kde is that it lends itself better to comparing distributions. But that is less true in the …

Add ecdfplot function

---

seaborn/categorical.py
seaborn/miscplot.py
seaborn/tests/test_matrix.py

Matplotlib 3.3.0rc1 has been released and results with several failing tests. This PR addresses some of them:
* FixedLocator now requires that `set_ticklabels()` inputs are equal to the number of ticks ([https://github.com/matplotlib/matplotlib/pull/17266](https://github.com/matplotlib/matplotlib/pull/17266)). This is an issue for `palplot` as well as categorical plots using unnamed groups, and fails several smoke tests and documentation examples. The proposed changes pass empty ticklabels in such cases (e.g. `[""]` instead of `[]`).
* `ax.get_aspect()` now returns `1` instead of `"equal"` when aspect was set to `"equal"` ([https://github.com/matplotlib/matplotlib/pull/16012](https://github.com/matplotlib/matplotlib/pull/16012)). "equal" aspect input is still valid. This affects matrix …

MNT: fix some failures with matplotlib=3.3.0rc1

---

.travis.yml
Makefile
ci/cache_test_datasets.py
ci/utils.txt

pytest is capable of running multiple CPUs in parallel if `pytest-xdist` plugin is installed. This should improve tests speed on multi-core systems. Each Travis-CI process has 2 CPUs available and currently only one is utilized. This PR introduces multi-core testing, hopefully improving local and CI tests speed. On my 6-core system, the full test suit is completed in less than 60 seconds, compared to ~330 seconds using a single core.
To overcome race conditions on datasets pulls, I added a script to cache test datasets before actual running test suits. 
I also removed unnecessary qt pulls from non-interactive travis builds; this reduced ~1m from such travis builds.

TST: Increase testing speed by utilizing multiple cores

---

doc/conf.py
doc/releases/v0.11.0.txt
doc/requirements.txt

This PR adds the ability to easily link to GitHub issues, PRs and users (e.g. for release notes), to easily provide broader context and credit. This is achieved by adding `sphinx-issues` extension (as done in scikit-learn, see [here](https://github.com/sloria/sphinx-issues)). Rules examples:
- ``:issue:`2062` `` links to #2062 
- ``:issue:`2052,2081` `` will link to both issues
- ``:pr:`2151` `` links to PR #2151
- ``:user:`MaozGelbart` `` links to user @MaozGelbart 
It can also link to other repos: ``:issue:`user/repo#12345` `` 
This PR also removes what seems like an unnecessary matplotlib import from sphinx conf file ('agg' is already the default backend in modern matplotlibs)
Closes #2062

DOC: enable Sphinx rules for linking to GitHub issues, PRs and users

---

examples/faceted_lineplot.py

in the faceted lineplot example, the number of lines used for palette definition should not be a magic number. Instead, it should be derived from from the dataset itself via len(). This makes it easier to understand the example without knowledge of the underlying dataset.

remove magic number in examples

---

README.md
doc/README.md

This PR makes it easier for users to understand how to test seaborn and/or build the docs (mostly making [https://github.com/mwaskom/seaborn/issues/2117#issuecomment-637499230](https://github.com/mwaskom/seaborn/issues/2117#issuecomment-637499230) more visible).

Elaborate on how to test seaborn and build the docs

---

seaborn/_core.py
seaborn/distributions.py
seaborn/relational.py
seaborn/tests/test_core.py

Previously this would fail:
```python
flights = sns.load_dataset("flights")
flights_wide = flights.pivot("year", "month", "passengers")
sns.lineplot(data=flights_wide)
```
Also changes the (internal) wide structure spec to use `@columns`, `@index`, `@values` to decrease chance of collisions with actual dataframe keys.

Support wide data with categorical columns

---

doc/releases/v0.11.0.txt
seaborn/axisgrid.py

This parameter is somewhat of a relic from the days when seaborn and matplotlib had spotty missing-data handling. I'm not currently aware of any functions that fail when they get data with missing values, but dropping na by default can cause problems (e.g. see #2143). On balance, I think this change is likely to have minimal negative consequences, but will help on more edge cases than it will hurt.
Closes #2143

Change dropna default to False in axisgrid.py

---

seaborn/_core.py
seaborn/categorical.py
seaborn/conftest.py
seaborn/tests/test_core.py
seaborn/tests/test_distributions.py

- Adds an error message when assigning semantics with wide-form data
- Improves the error message when mixing a `DataFrame` and non-`Series` vector and the lengths don't match
- Improves the error message when a key cannot be parsed with long-form data
Closes #2082

Improve variable assignment feedback

---

pytest.ini
seaborn/_core.py
seaborn/algorithms.py
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_core.py
seaborn/tests/test_distributions.py

Mostly related to changes in numpy (warning on creating a ragged array without explicit object dtype) and matplotlib (warning on setting ticklabels without setting ticks).

Address various warnings raised within the tests

---

doc/releases/v0.11.0.txt
doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Deprecated in 0.9 and removed now as it conflicts with the legend that ``hue`` mapping requires.

Remove deprecated JointGrid annotation code

---

seaborn/_core.py
seaborn/relational.py
seaborn/tests/test_core.py

This will prevent relational plots from overwriting existing axis labels:
```python
f, ax = plt.subplots()
ax.set(xlabel="Price ($)", ylabel="Carat")
sns.scatterplot(data=diamonds.sample(frac=.1), x="price", y="carat")
```

Use core axis labeling method in relational plots

---

doc/releases/v0.11.0.txt
doc/tutorial/color_palettes.ipynb
seaborn/palettes.py
seaborn/tests/test_palettes.py

Add a rich HTML representation of color palette objects

---

doc/tutorial/distributions.ipynb
examples/layered_bivariate_plot.py
seaborn/distributions.py

I think the contrast properties of a light-to-dark ramp are somewhat less desirable than dark-to-light, but it's a bit more intuitive and, decisively, is more internally consistent with the old defaults. So it wins out.
Fixes #2211

Reverse direction of default distributions sequential colormap

---

doc/docstrings/PairGrid.ipynb
doc/docstrings/pairplot.ipynb
doc/tools/extract_examples.py
seaborn/axisgrid.py
seaborn/distributions.py
seaborn/tests/test_axisgrid.py

The main enhancement here is that `PairGrid` will pass `hue` down to the axes-level functions if they accept it, giving better visuals and more flexibility.
A few other things were cleaned up:
- Added `kind="kde"` and `kind="hist"` in `pairplot`
- Added public access to the `PairGrid` (and `FacetGrid`) legend object
- Made it possible to pass only one of `x_vars` and `y_vars`
- No longer pass `color` or `label` in `PairGrid` when not using `hue` (fixes #1301)
- No longer cast pandas data to a numpy array before plotting on the diagonal (fixes #1663)
- Converted `PairGrid` and `pairplot` API examples to notebooks and updated them
These changes need to be noted in the release notes, using the `docs_cleanup` branch to avoid a merge conflict.
Closes #2198

Delegate hue in PairGrid to plotting functions

---

examples/many_pairwise_correlations.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/matrix.py
seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_matrix.py

The next minor numpy version (1.20) [deprecated](https://github.com/numpy/numpy/pull/14882) the usage of numpy types that are just aliases to python builtin types. This includes `np.bool`, `np.int`, `np.float` and others. This PR replaces these occurrences with the native types to avoid deprecation warnings on future numpy versions. I changed `np.object` to `np.object_` and not the builtin type since it resulted with slight differences in the relevant test suit (`test_matrix.py`).

MAINT: avoid deprecation warnings with future numpy releases

---

doc/releases/v0.11.1.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fixes #2260
```python
g = sns.pairplot(data=iris, hue="species", y_vars='sepal_width')
```

Fix PairGrid with non-square grid and non-marginal diagonal axes

---

seaborn/tests/test_relational.py

There are some `scatterplot` tests which compare wrong collection against expected paths and colors. The reason the tests have passed so far is that `colors_equal` and `paths_equal` use `zip` to compare arrays elements but in the case of unequal array length `zip` iterates over the first `min(m,n)` elements, so if the first `min(m,n)` elements are all equal it returns `True`. 
This PR tests colors and paths using the correct collections; moves to test color arrays equality using matplotlib's `same_color` function (introduced in matplotlib 2.2); and fixes the behavior of `paths_equal`.

TST: fix colors and paths comparison in relational tests

---

seaborn/categorical.py

Fixes #2285 . Prior to this change, the `linewidth` argument is only used to frame the legend elements and is not applied to boxes and medians.

Fix: use linewidth in boxenplot elements

---

seaborn/regression.py
seaborn/tests/test_regression.py

`lmplot` de facto requires a `data` keyword argument. Currently, not specifying it throws the following error.
```
TypeError: NoneType is not suscriptatble
```
This patch improves the error message as
```
TypeError: Missing required keyword argument `data`.
```

throw a meaningful error message in lmplot in case  kwarg is missing

---

seaborn/matrix.py

Fixes #2319 the `clustermap` function was not catching False as it should have been.

Fix: do not annotate clustermap w/ annot=False

---

doc/conf.py
seaborn/matrix.py
seaborn/tests/test_matrix.py

Closes #1550 . With this PR, an appropriate `TypeError` is raised if one of `{row/col}_colors` are pandas data types but the data isn't, where indices can't be matched. Also contains small changes to some matrix docstrings.

Error if row/col colors are indexed but data isn't

---

doc/tutorial/distributions.ipynb

Hi! I caught a typo in the Sphinx syntax of this page: https://seaborn.pydata.org/tutorial/distributions.html
This PR fixes the missing colon, which will make the reference render.
I also fixed one other rST syntax error, there was a missing space that prevented the Sphinx double-backtick code block from rendering correctly.
Thanks for the wonderful package. 😄

Fix jointplot reference syntax in distributions tutorial.

---

seaborn/axisgrid.py

better checks for `sharey` and `sharex` in `axesgrid.py`
closes #2346

better checks for `sharey` and `sharex` in `axesgrid.py`

---

.travis.yml
ci/utils.txt
pytest.ini
seaborn/conftest.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_matrix.py
seaborn/tests/test_miscplot.py
seaborn/tests/test_palettes.py
seaborn/tests/test_rcmod.py
seaborn/tests/test_regression.py
setup.py

This PR drops the obsolete `nose` package, and rewrites all nose-style tests as modern `pytest`-style tests. Most changes are simple translations of nose asserts to their equivalent pytest `assert` expressions. In a few places pytest parameterization was utilized as well. I did my best to keep the changes to the minimum, but I also changed a few variable names occasionally and removed subclassing from object when I encountered such cases (leftovers from py2-style code).
This PR also adds python==3.9 to the CI tests matrix.

MAINT: Drop nose and test on python==3.9

---

seaborn/relational.py
seaborn/tests/test_relational.py
seaborn/utils.py

Fixes #2272
This now drops NA internally (basically restoring the previous behavior) so that NAs don't propagate and erase the confidence intervals. It also uses `np.nanpercentile` which better matches the previous behavior, which used the (apparently NA aware) `scipy.stats.percentileofscore`.
A related issue I would like to address here is #1552, but on a first stab I ran into some complexities and that may need to be handled separately with more thought.
Ideally the aggregation could use pandas NA-aware mean when `estimator="mean"` and then we would need to do less NA bookkeeping. But the bootstrapping algorithm converts data to numpy arrays because sampling with replacement is about an order of magnitude slower with pandas objects. One possibility would be to use `np.nanmean` if the …

Fix NA propagation in lineplot

---

seaborn/_core.py
seaborn/tests/test_core.py

Fixes #2317, with small changes to the docstring of `variable_type`.

FIX: Infer categorical dtypes before boolean resolution

---

doc/releases/v0.11.1.txt
seaborn/_core.py
seaborn/tests/test_core.py

The variable processing refactor made long-form argument processing more strict, allowing only string(y) types as keys to the `data` object. While this is basically what was documented, many functions previously worked properly with numeric arguments or even tuples (i.e. as keys for multi-index columns).
This PR makes the processing of named variables with long-form data more flexible.
It introduces a couple minor ambiguities, e.g. when `data` is present and a variable is specified with a number or a tuple, the variable could be interpreted as a key for `data` or as a data value itself (preferring the former). But I think in most cases, the expected behavior it to interpret it as a key.
~Needs tests, but I wanted to get CI going.~
Fixes #2279
Fixes #2263
Wide-form data objects with …

Add/restore functionality to long-form data processing

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Currently providing `row_colors` or `col_colors` as categoricals is impossible and clustermap raises upon such input (see #1872). With this PR, pandas categorical input is converted to object-typed data structure before setting the color for nan data, in a way that supports categorical input.
Fixes #1872.

Allow clustermap row/col colors to be categorical

---

doc/releases/v0.11.1.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Most of the axisgrid objects (`FacetGrid`, `PairGrid`, `JointGrid`) were written before there were many axes-level seaborn functions and were originally designed to interface with `pyplot` functions. They make use of matplotlib global state to allow a generic interface for spreading a plot across multiple Axes instances. Because they control the state internally, this ends up not being a huge problem, but one potential source of issues would arise in the context of parallel execution (cf. #2380).
All seaborn-axes level functions accept `ax=` for explicit placement, so this PR special-cases seaborn functions to pass the relevant `Axes` around explicitly rather than setting and using the global state.
It would probably be fine to more generically pass `ax` explicitly when the function …

Reduce usage of global matplotlib state in axisgrid objects

---

doc/tutorial/color_palettes.ipynb

This pull request corrects a typo in the [color palette tutorial](https://seaborn.pydata.org/tutorial/color_palettes.html#perceptually-uniform-divering-palettes).
```diff
- Perceptually uniform divering palettes
+ Perceptually uniform diverging palettes
```

Corrects typo in the diverging palette doc sub-section title

---

.github/workflows/ci.yaml
README.md
ci/deps_pinned.txt
doc/installing.rst
doc/releases/v0.12.0.txt
doc/whatsnew.rst
seaborn/_statistics.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/rcmod.py
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py
seaborn/tests/test_matrix.py
seaborn/tests/test_rcmod.py
setup.py

Following NEP29 and upstream libraries

Raise minimal supported Python to 3.7 and bump requirements

---

seaborn/axisgrid.py
seaborn/matrix.py

The change in #2399 inadvertantly broke seaborn on the macosx mpl backend.
See https://github.com/matplotlib/matplotlib/issues/19197
This PR reverts that change until the issue can be sorted out.

Revert change to forced draw command

---

doc/docstrings/lineplot.ipynb
doc/releases/v0.12.0.txt
doc/tutorial.rst
doc/tutorial/error_bars.ipynb
doc/tutorial/relational.ipynb
seaborn/_core.py
seaborn/_statistics.py
seaborn/algorithms.py
seaborn/relational.py
seaborn/tests/test_algorithms.py
seaborn/tests/test_relational.py
seaborn/tests/test_statistics.py
seaborn/utils.py

This PR adds a new internal statistics object for doing aggregation with an estimator function and expands the flexibility of the error bars that operation can produce.
This implements and closes #2403. More logic is given there. Briefly, the new errorbars can be:
- "ci", for a bootstrap confidence interval of a given width (default 95)
- "pi", for a percentile interval of the data with a given width (default 95)
- "se", for +/- the standard error, scaled by a given factor (default 1)
- "sd", for +/- the standard deviation, scaled by a given factor (default 1)
- an arbitrary callable that maps a vector to a (min, max) interval
To Dos:
This (partly) addresses several longstanding issues. It won't fully address them until the logic is integrated into the other modules; doing so will happen …

Increase errorbar flexibility

---

doc/releases/v0.12.0.txt
seaborn/_core.py
seaborn/tests/test_core.py

This PR avoids passing `nan` through the matplotlib converters used to obtain a numeric/computable representation of the data (i.e. `VectorPlotter.comp_data`).
It also
- codifies that the converted columns in `comp_data` have a float dtype
- converts `inf` to `nan`, in line with what matplotlib does
Fixes #2295 
Additionally this will implicitly address #1971 once the regression plots are refactored to use `comp_data` internally. (@mojones, funny that you opened both issues).

Improve NA robustness in VectorPlotter.comp_data

---

seaborn/categorical.py

The docstring for the `whis` keyword in `boxplots` has an inaccurate description. That is, whiskers don't extend to 1.5*IQR, rather they extend to the furthest datum within 1.5*IQR. I propose a clearer wording.
Evidence for confusion caused by this inaccuracy can be found [here on Stackoverflow](https://stackoverflow.com/questions/49139299/whisker-is-defined-as-1-5-iqr-how-could-two-whikers-in-plot-from-python-seabor).

boxplot whis keyword docstring clarification

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

This PR solves the above issue.
Test added for when pandas >= 1.2.

Support Float64Dtype in boxenplot, related to #2434

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fix rugplot with datetime data

---

doc/releases/v0.12.0.txt
seaborn/_statistics.py
seaborn/tests/test_distributions.py

e.g.
```python
sns.histplot(
data=tips,
x="day", hue="time",
stat="percent", multiple="dodge", shrink=.8
)
```

Add percent-based normalization in histplot

---

doc/releases/v0.12.0.txt
doc/tutorial/distributions.ipynb
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #2452
Also simplifies the logic that disabled the `multiple` parameter when no hue was assigned (which caused the issue originally), instead allowing the default visual attributes to vary with multiple even if it has no effect on the position of the distributions.

Fix multiple resolution when hue variable has no name

---

seaborn/_docstrings.py

Don't fail when docstrings have been stripped by -OO mode

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #2476
The code for shifting the shrunken bars assumed that discrete binning
was in effect. This is probably the only situation where shrinking
really makes sense, but there was no prevention or warning of getting
an innacurate result when using it with continuous bins.
It works properly now:
```python
sns.histplot(data=tips, x="total_bill", binwidth=8)
sns.histplot(data=tips, x="total_bill", binwidth=8, shrink=.6)
```
```python
sns.histplot(data=tips, x="total_bill", binwidth=8, color=".6")
sns.histplot(data=tips, x="total_bill", hue="time", multiple="dodge", binwidth=8, shrink=.6)
```

Fix histplot shrink with non-discrete bins

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Avoids the issue in https://github.com/matplotlib/matplotlib/issues/19544
Matplotlib is going to revert the problematic release candidate behavior, but this PR should make seaborn robust to future such changes.
Also handles an issue where it looks like passing `tree_kwargs={"color": color}` will not work in matplotlib 3.4, due to some change in the resolution of `color`/`colors`.

Don't pass a set to ListedColormap in clustermap

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #2513
Fixes #2523
With test case from #2513:
```python
fig, axs = plt.subplots(ncols=3, nrows=2, figsize=(12,6))
vals = np.random.randn(1000)
sns.histplot(x=vals, log_scale=False, ax=axs[0, 0])
sns.histplot(x=10**vals, log_scale=True,ax=axs[1, 0])
vals = np.random.randn(10000)
sns.histplot(x=vals, log_scale=False, ax=axs[0, 1])
sns.histplot(x=10**vals, log_scale=True, ax=axs[1, 1])
vals = np.random.randn(1000000)
sns.histplot(x=vals, log_scale=False, ax=axs[0, 2])
sns.histplot(x=10**vals, log_scale=True, ax=axs[1, 2])
plt.tight_layout()
```
And #2523:
```python
f, axs = plt.subplots(2)
sns.histplot(y=[0, 1, 1], discrete=True, edgecolor="r", ax=axs[0])
sns.histplot(y=["a", "b", "b"], discrete=True, edgecolor="r", ax=axs[1])
```
Thanks @mgab for the very clear bug report!

Fix histplot auto line width with log scale or categorical y axis

---

.github/CONTRIBUTING.md
examples/jitter_stripplot.py

Coming from Twitter: https://twitter.com/michaelwaskom/status/1376595092014833667
This PR clarifies an example. Previously there was the magic number `.532`, which is now replaced by `.8 - .8/3` and an accompanying comment-explanation.
- 0.8 is the default width allotted to each category
- `0.8 - 0.8 /3` equals `.532` but will allow users to adjust the example to their need if they have different numbers of hues

DOC: Clarify how to derive dodge parameter value for aligning pointplot in stripplot

---

seaborn/_core.py
seaborn/axisgrid.py
seaborn/matrix.py
seaborn/palettes.py
seaborn/utils.py

Typos, non-existing parameters, and the fact that space before colon in
parameters is necessary for numpydoc to correctly parse the name and
type

DOC: misc fixes.

---

seaborn/distributions.py

Fixes #2555
* moves `binwidth`, `thin_bar_idx`, and `left_edge` calculation out of the loop since it's invariant over the iterations
* Only `set_linewidth` one per bar, instead of setting all bar's linewidth once per facet
I've run this on this branch, and on master
```python
import matplotlib as mpl
from setuptools_scm import get_version
print(get_version(root='..', relative_to=sns.__file__))
diamonds = sns.load_dataset("diamonds")
```
```python
%%timeit
g = sns.displot(diamonds, x="price", row="cut", col="color")
```
```python
g = sns.displot(diamonds, x="price", row="cut", col="color")
print({rect.get_linewidth() for rect in g.fig.findobj(mpl.patches.Rectangle)})
```
```
0.10.1.dev198+ga365acc
4.08 s ± 60.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) …
```

Reduce redundant computation in distplot linewidth

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py
seaborn/distributions.py
seaborn/tests/test_distributions.py

Set to False to silence the warning about zero variance datasets.
~One downside is that if you run into this in the `histplot(..., kde=True)` context the suggestion for how to disable it is incorrect (or at least unhelpful). Could potentially have `histplot` set this to False internally. In general I think I probably should have trusted my "non-deprecation-related warnings are almost always more annoying then helpful" intuition here.~
Most cases where `kdeplot` is called internally now have this set to `False`, as I think the warning makes most sense in the "hey, why is my single plot empty" context, not when one kde curve in a large pairplot (or etc.) has disappeared.
Closes #2499

Add warn_singular parameter in kdeplot

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py

This prevents matplotlib from doing a naive tight_layout operation that ignores the space the legend needs to occupy.
Closes #2496

Disable autolayout rcparam when constructing Facet/PairGrid

---

doc/conf.py

This is a little hacky, but including the thumbnail images in the build seems otherwise complicated because they are written into raw html source with an `<img>` tag, not using the sphinx image directive.
Fixes #2532

Create example_thumbs while running conf.py

---

doc/releases/v0.12.0.txt
seaborn/matrix.py

Closes #2484
With the case from that issue:
```python
m = ['January', 'February', 'March']
sns.heatmap(data=np.random.rand(3, 3), yticklabels=m, xticklabels=m)
```

Set heatmap yticklabel alignment while rotating

---

doc/releases/v0.12.0.txt
seaborn/regression.py
seaborn/tests/test_regression.py

This PR rolls together a couple small fixes to semi-related issues in `lmplot`.
I don't actually think there's an issue about this, but it's ugly and not intentional:
Old:
New:
This improves the code that scales the x axis to the data limits before plotting so that it does not interfere with `sharey=False` (fixes #2509)
Using the example case from that issue:
Fixes #2518.
Additionally, `sharex`/`sharey`/`legend_out` have been deprecated from the `lmplot` signature, but they can now be passed using this parameter dictionary.

Several fixes/improvements related to lmplot axis scaling

---

seaborn/_core.py
seaborn/categorical.py
seaborn/tests/test_categorical.py

Fixes #2516
With the example from that issue:
```python
ax = sns.stripplot(x=["A", "B", "C"], y=[1, 3, 2])
ax = sns.stripplot(x=["E", "F"], y=[5, 2])
```
This does make some assumptions about what matplotlib will be doing, namely that updating categorical unit data will add ticks to the matplotlib axis (even though it does not rescale the limits).
I also ran into a bunch of confusing issues when implementing this (apparently simple) fix. The internals relating to establishing/using the `var_levels` for categorical variables messy and confusing. I was able to get this working without rethinking/reimplementing everything, but I do think that doing so will ultimately be important for ongoing maintainability.

Use ticks to infer number of categorical levels on an axis

---

seaborn/_core.py
seaborn/tests/test_relational.py

Builds on #2579 with
- a test for the original bug
- the addition of a `size_range` attribute on the `SizeMapping` object, rather than accessing the `_default_size_range` attribute, which is regrettable and will ideally get refactored away somehow.

Fix size norm extrapolation

---

doc/docstrings/FacetGrid.ipynb
doc/releases/v0.12.0.txt
seaborn/axisgrid.py

A few small changes to make custom `FacetGrid` plotting a little easier:
- Disable the visibility of interior axis label objects (closes #2493)
- No longer remove axis labels after mapping a function (closes #2456)
- Use the `x` and `y` kwargs passed to `map_dataframe` for axis labels

Improve FacetGrid axis labeling

---

doc/.gitignore
doc/conf.py

As an alternative to creating the directory in conf.py
Cf #2572

Include empty example_thumbs directory in repository

---

doc/Makefile
doc/docstrings/histplot.ipynb
doc/docstrings/swarmplot.ipynb
doc/introduction.ipynb
doc/releases/v0.5.0.txt
doc/releases/v0.6.0.txt
doc/releases/v0.8.0.txt
doc/sphinxext/gallery_generator.py
doc/tutorial/color_palettes.ipynb
doc/tutorial/data_structure.ipynb
doc/tutorial/distributions.ipynb
doc/tutorial/function_overview.ipynb
seaborn/_core.py
seaborn/_statistics.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/external/kde.py
seaborn/matrix.py
seaborn/relational.py
seaborn/tests/test_algorithms.py
seaborn/tests/test_categorical.py
seaborn/tests/test_core.py
seaborn/tests/test_relational.py
seaborn/tests/test_utils.py

Found via `codespell -q 3 -L ans,hist,whis`

Fix various typos

---

doc/docstrings/FacetGrid.ipynb
doc/docstrings/JointGrid.ipynb
doc/releases/v0.12.0.txt
examples/kde_ridgeplot.py
examples/many_facets.py
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Closes #2249 &ndash; Adds new `JointGrid.refline()` method: 
```python
JointGrid.refline(self, *, x=None, y=None, joint=True, marginal=True, **line_kws)
```
Example usage:
```python
penguins = sns.load_dataset('penguins')
g = sns.jointplot(data=penguins, x='bill_length_mm', y='bill_depth_mm')
g.refline(y=16, linestyle='dashed', color='gray')
g.refline(x=45, marginal=False, linestyle='dotted', color='red')
g.refline(x=55, joint=False, linestyle='dashed', color='blue')
```
Needs:

JointGrid reference lines

---

seaborn/tests/test_utils.py
seaborn/utils.py

This should help reduce confusion following a relatively common beginner mistake. The current result is useless for solving the problem:
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-245-abe567917c1d> in <module>
----> 1 sns.load_dataset(tips)
~/code/seaborn/seaborn/utils.py in load_dataset(name, cache, data_home, **kws)
479                                   os.path.basename(full_path))
480         if not os.path.exists(cache_path):
--> 481             if name not in get_dataset_names():
482                 raise ValueError(f"'{name}' is not one of the example datasets.")
483             urlretrieve(full_path, cache_path) …
```

Try to provide more helpful error if load_dataset is given a DataFrame

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/relational.py
seaborn/tests/test_distributions.py
seaborn/tests/test_relational.py

Fixes #2622 
Context: `relplot` and `displot` no longer use the original approach of "set up a `FacetGrid`, map an axes-level function" such that the `FacetGrid` owns the data. This is because they can handle wide data and data passed directly as vectors, using the relevant module-level plotting class to parse the inputs. But as a consequence, the `.data` attribute on the `FacetGrid` that they return does not have all the columns that were passed into the function.
This  PR attempts to improve that situation by merging the input dataframe with the processed dataframe used internally (which handles, e.g. the transform from wide data or vectors that were passed directly to plot kwargs, often without names).
Because input data specification is so flexible, this is a little tricky, and there …

Fix FacetGrid.data on object returned from relplot and displot

---

doc/docstrings/histplot.ipynb
doc/releases/v0.11.2.txt
seaborn/_statistics.py
seaborn/tests/test_distributions.py

Follows #2461. This gives the same result as  but may be more intuitive for some people.

Add proportion-based normalization in histplot

---

seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_relational.py

Matplotlib added a warning when passing an `edgecolor` parameter with an unfilled `scatter` marker. See https://github.com/matplotlib/matplotlib/issues/17849 and subsequent matplotlib PR  for details.
seaborn wasn't doing anything wrong here, but on newer matplotlibs it will now spew warnings; this change avoids them.

Avoid scatter edgecolor warning

---

seaborn/axisgrid.py

These were oversights from #2583

Fix non-removed interior axis labels and diagonal legends in PairGrid

---

doc/docstrings/FacetGrid.ipynb
doc/introduction.ipynb
doc/releases/v0.11.2.txt
doc/tutorial/axis_grids.ipynb
doc/tutorial/relational.ipynb
examples/joint_histogram.py
examples/kde_ridgeplot.py
seaborn/axisgrid.py
seaborn/matrix.py
seaborn/tests/test_axisgrid.py

The advantage of this change is that you will be able to do
obj = sns.<func>()
obj.figure.<method>
regardless of whether `<func>` is figure-level or axes-level.
The `Grid.fig` methods are being soft-deprecated: discouraged in the
attribute documentation but not (currently) issuing a warning when used.

Add Grid.figure to (eventually) replace Grid.fig

---

doc/api.rst
doc/docstrings/move_legend.ipynb
doc/releases/v0.11.2.txt
seaborn/tests/test_utils.py
seaborn/utils.py

This addresses issues discussed in #2280, along with some of the issues in #2231
It is a somewhat hack-ish solution. Because matplotlib legends don't offer public
control over their location, this copies data from an existing legend to a new
object, and then removes the original legend. I am hopeful that there will be
upstream changes that make legend repositioning more natural, but this is
a reasonable stopgap measure to alleviate a common seaborn pain-point.
It is also in a sense more powerful than the name suggests, because it lets one
update other legend parameters, which is also not otherwise possible with
public methods on an existing legend object.
Example in action:
```python
ax = sns.histplot(penguins, x="bill_length_mm", hue="species")
sns.move_legend(ax, "lower center", …
```

Add a move_legend convenience function

---

licences/PACKAGING_LICENSE
seaborn/_core.py
seaborn/external/version.py
seaborn/tests/test_algorithms.py
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py
seaborn/tests/test_regression.py
seaborn/tests/test_relational.py
seaborn/tests/test_utils.py
seaborn/utils.py

Closes https://github.com/mwaskom/seaborn/issues/2466. Unlike https://github.com/mwaskom/seaborn/pull/2485, this chooses to make a vendored Version class much like Pandas did here https://github.com/pandas-dev/pandas/pull/41207.
I took out a bit of what was in the two `packaging` files since it seemed like seaborn only needs to use the `Version` class, but happy to put it back in!

Vendor the Version package, use it instead of distutils

---

doc/requirements.txt
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py

Update tests for compatability with matplotlib 3.5.0

---

setup.py

Small nitpick after #2396: Also update the runtime error to list Python 3.7 as minimal version

setup.py: Update runtime error to correct minimal Python version

---

seaborn/tests/test_categorical.py

As was noted in https://github.com/mwaskom/seaborn/issues/2663#issuecomment-937359794, the `test_box_colors` tests are broken because `zip` only iterates to the shortest input.
For `boxplot`, there are in fact 3 copies of the palette not 2 for the second test.
For `boxenplot`, it doesn't add `Patch` at all but `PatchCollection`, as can be seen in the related tests.

Fix box(en)plot colour tests

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py

Lets see if any tests will fail. It passed thru tests and linting on my own machine.
Fixes https://github.com/mwaskom/seaborn/issues/2702

Add default FacetGrid titles on initialization instead of after plotting

---

.github/workflows/ci.yaml
doc/requirements.txt
licences/PACKAGING_LICENSE
seaborn/_core.py
seaborn/_statistics.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/external/version.py
seaborn/rcmod.py
seaborn/tests/test_algorithms.py
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py
seaborn/tests/test_rcmod.py
seaborn/tests/test_regression.py
seaborn/tests/test_utils.py

Fixes #2724
Cherry-picked a0f7bf8 / #2659 as discussed in #2724

[v0.11] Vendor the Version package, use it instead of distutils

---

licences/APPDIRS_LICENSE
seaborn/external/appdirs.py
seaborn/utils.py

Fix https://github.com/mwaskom/seaborn/issues/1530

Standardize cache directory

---

.github/workflows/ci.yaml

A bit of maintenance on the CI:
- Allow to manually trigger a the CI from the GitHub UI ([workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch))
- Update the used actions to actions/checkout@v3, actions/setup-python@v3 and codecov/codecov-action@v2
- Cache pip dependencies ([docs](https://github.com/actions/setup-python#caching-packages-dependencies))
- Run more tests with Python 3.10
- Bit of cleanup

CI: Update used actions, cache pip deps, 3.10 tests

---

doc/conf.py
doc/sphinxext/gallery_generator.py
seaborn/_core.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/external/appdirs.py
seaborn/external/docscrape.py
seaborn/external/husl.py
seaborn/external/kde.py
seaborn/palettes.py
seaborn/rcmod.py
seaborn/relational.py
seaborn/tests/test_matrix.py

Reformats all the text from the old "%-formatted" and .format(...) format to the newer f-string format, as defined in [PEP 498](https://www.python.org/dev/peps/pep-0498/). This requires Python 3.6+.
[Flynt](https://github.com/ikamensh/flynt) 0.76 was used to reformat the strings. 45 f-strings were created in 13 files.
F-strings are in general more readable, concise and performant. See also: [PEP 498#Rationale](https://www.python.org/dev/peps/pep-0498/#rationale)
```
Running flynt v.0.76
Flynt run has finished. Stats:
Execution time:                            2.066s
Files checked:                             102
Files modified:                            13
Character count reduction:                 411 (0.03%)
Per expression type:
Old style (`%`) expressions attempted:     28/30 (93.3%) …
```

Use f-strings for string formatting

---

seaborn/conftest.py

Starting from Pandas 1.4.0, [pandas.Int64Index](https://pandas.pydata.org/docs/reference/api/pandas.Int64Index.html) is depreciated, this PR replaces 3 cases of them in _conftest.py_ with an even more appropriate [RangeIndex](https://pandas.pydata.org/docs/reference/api/pandas.RangeIndex.html#pandas.RangeIndex), which is more concise and faster.
The errors are [here](https://github.com/mwaskom/seaborn/runs/6380973404?check_suite_focus=true#step:6:81) in the latest CI run on the master branch, and gone in the [CI run](https://github.com/mwaskom/seaborn/runs/6423254991?check_suite_focus=true) of this PR.

conftest.py: Fix Pandas deprecation warnings

---

doc/docstrings/stripplot.ipynb
doc/docstrings/swarmplot.ipynb
doc/releases/v0.12.0.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Potentially just bikeshedding, but feels maybe a bit more natural to affirmatively ask for the new behavior than to disable the old behavior.
Usage example:
```python
planets = sns.load_dataset("planets")
sns.stripplot(data=planets, x="year", y="mass", native_scale=True)
sns.lineplot(data=planets, x="year", y="mass")
```

Rename fixed_scale to native_scale and invert boolean

---

seaborn/distributions.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_distributions.py

This diff removes the docstring for `displot`, replacing it with a more verbose message about deprecation. I've also [written up a guide](https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751) to translating code from `distplot` to `histplot`/`displot` and now link to that from the docstring and warning message.

Deprecate distplot more agressively with guide to updating

---

seaborn/distributions.py
seaborn/tests/test_distributions.py

With the modernization of the distribution plots in v0.11.0, a bunch of parameters were deprecated (began issuing warnings) from `kdeplot` and `rugplot` to bring their API in line with the rest of seaborn. Now that we enforce keyword arguments, the deprecated parameters can be taken out of the signature, with backwards compatibility handled by popping them off of the `kwargs`.
I've also updated the warnings, making a few more clear, changing the class from `FutureWarning` to `UserWarning`, and specifying the version in which they will be fully removed.

Remove deprecated parameters from signatures and improve warnings

---

doc/conf.py
doc/sphinxext/gallery_generator.py
doc/tools/set_nb_kernels.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/external/appdirs.py
seaborn/external/docscrape.py
seaborn/external/kde.py
seaborn/matrix.py
seaborn/regression.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_distributions.py
seaborn/tests/test_utils.py

This PR updates the Python code with Python 3.7+, removing old, depreciated and redundant code. The biggest advantage is increased readability of the code. [pyupgrade](https://github.com/asottile/pyupgrade) 2.32.1 was used with `--py37-plus`.
This includes:
- f-string formatting of strings ([PEP 498](https://www.python.org/dev/peps/pep-0498/), Python 3.6+)
- utf-8 encoding is now the default ([PEP 3120](https://www.python.org/dev/peps/pep-3120/), Python 3.0+)
- Replace list comprehensions by Generator Expressions ([PEP 289](https://www.python.org/dev/peps/pep-0289/), Python 2.4+)
- Replace `yield` loop by `yield from` ([PEP 380](https://www.python.org/dev/peps/pep-0380/), Python 3.3+)
- Replace the IOError alias by OSError ([PEP 3151](https://www.python.org/dev/peps/pep-3151/), Python …

Pyupgrade 3.7: Update syntax with Python 3.7+ features

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #2655
With the example from that issue:
```python
f, axs = plt.subplots(2, 2, constrained_layout=True, figsize=(7, 6))
params = dict(x=[1, 2, 3], weights=[1, 2, 2], discrete=True)
sns.histplot(**params, ax=axs.flat[0])
sns.histplot(**params, hue=["a", "b", "b"], ax=axs.flat[1])
sns.histplot(**params, hue=["a", "b", "b"], stat="proportion", ax=axs.flat[2])
sns.histplot(**params, hue=["a", "b", "b"], stat="proportion", common_norm=False, ax=axs.flat[3])
```

Fix histplot/kdeplot normalization with weights

---

doc/releases/v0.12.0.txt
seaborn/_statistics.py
seaborn/axisgrid.py
seaborn/regression.py
seaborn/tests/test_statistics.py

Fixes #2721
Fixes #2785 
These actually ended up being slightly distinct issues, although they can be fixes in the same block of code.

Fix histplot binwidth edgecases

---

seaborn/_core/plot.py
seaborn/_core/properties.py
seaborn/_marks/basic.py
seaborn/_marks/scatter.py
seaborn/tests/_marks/test_scatter.py

I'm not totally certain what the best approach to missing data is; this will drop missing data after stats and scaling. I don't think seaborn needs explicit functionality for considering "missing" a valid category (it is just as easy to do `df.fillna("missing")`) but there may be times when it is desired to have missing data represented with (invisible) artists.
For now, that's not externally parametrize, but it is possible for a specific `Mark` to implement that behavior.

Drop missing data centrally while allowing marks to disable

---

doc/releases/v0.12.0.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Fixes #2742
With the example from that issue:
```python
N = 30
np.random.seed(3)
data = np.random.normal(size=(N,))
df = pd.DataFrame({'Before': data,
'After': data + 1})
df_long = pd.melt(df, value_vars=['Before', 'After'])
ax = sns.violinplot(x='variable', y='value', data=df_long, hue='variable', split=True, inner='box', cut=1)
```

Fix inner box with unpaired split violins

---

seaborn/_core/plot.py
seaborn/_marks/base.py
seaborn/tests/_core/test_plot.py

I'm not totally satisfied with this, but mutating the layer dict
(the other option) doesn't seem much cleaner.
The result is proper behavior here:
```python
so.Plot(tips, y="total_bill").add(so.Bar(), so.Hist())
```

Fix inferred y orientation with computed x variable

---

seaborn/_core/moves.py
seaborn/_core/plot.py
seaborn/objects.py
seaborn/tests/_core/test_moves.py

A simple `Move` operation (slightly stretching the functionality beyond "reduce over-plotting") that does a divisive normalization by an arbitrary function.:
```python
so.Plot(penguins, "bill_length_mm").add(so.Bar(), so.Hist(), so.Norm())
```
The function and grouping are flexible, and it can be chained with other moves in interesting ways:
```python
(
so.Plot(tips, x="day", y="total_bill", color="sex")
.add(so.Bar(), so.Hist(), [so.Norm("sum", by=["x"]), so.Stack()])
)
```
There is also some flexibility to the domain across where the normalizer is computed:
```python
(
so.Plot(gapminder, "year", "lifeExp", color="continent")
.add(so.Line(), so.Agg(), so.Norm(where="x == 1977"))
)
```

Add Norm move class

---

seaborn/categorical.py
seaborn/relational.py
seaborn/tests/test_categorical.py

This ties up some loose ends from #2413 and #2447, which allowed them to apply a continuous mapping to the hue variable without upgrading the legend machinery to properly show a colorbar-like legend. Now that works as expected:
```python
sns.catplot(diamonds, x="cut", y="price", hue="carat", jitter=.4, s=5)
```
The solution is a bit of a shortcut, simply making `_CategoricalPlotterNew` subclass `_RelationalPlotter`, where the relevant method for creating legend artists lives. Probably that method should be moved down to the base class level to keep a cleaner division between the modules (but also, the `distributions` module has a different approach altogether). Legends remain a mess.

Improve legend for categorical scatterplots

---

seaborn/categorical.py
tests/test_categorical.py

Revert unnecessary (and broken) backwards compat in catplot

---

seaborn/_oldcore.py
seaborn/categorical.py
tests/test_categorical.py
tests/test_core.py

Fixes #2835 
- Fixes a simple bug introduced in the refactor (#2429) where `catplot(..., kind="swarm")` would only have points in the final axes swarmed.
- Fixes a bug where `catplot()` with either scatterplot option was using the color cycle for each categorical level.
- Added a warning and some backwards compatibility for cases where `palette=` is passed without `hue=` in the refactored categorical scatterplots. I thought I had done this during the refactor, but apparently not. While we are changing the default behavior, it seems reasonable to honor this explicit ask for multiple colors with a warning / smoother deprecation.

Address issues with new categorical scatterplots

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
seaborn/relational.py
tests/test_relational.py

- Suppress internal names for anonymous vector objects from appearing as axis labels (fixes #2712)
- Support anonymous vector objects as faceting variables (fixes #2624)

Improve support for nonstandard data representation in relplot

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py
tests/test_axisgrid.py

Fixes #2590.
With reprex from that issue:
```python
iris = sns.load_dataset("iris")
g = sns.PairGrid(iris, y_vars=["sepal_length","sepal_width"], x_vars=["petal_length","petal_width"])
g.map(sns.scatterplot, hue=iris["species"])
g.map(sns.regplot, scatter=False)
```

Fix PairGrid with hue passed in map method

---

doc/releases/v0.12.0.txt
seaborn/_oldcore.py
tests/test_relational.py

Fixes #2590
With simpler example from that issue (as the problem didn't really have anything to do with `PairGrid`:
```python
sns.scatterplot(
data=iris,
x="sepal_length", y="sepal_width",
hue="species", hue_order=["setosa", "versicolor"],
)
```

Fix hue_order as a subset in scatterplot

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
tests/test_distributions.py

Closes #2819 by adding a test and fixes #2820

Fix histplot dodge bar widths with log scale

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py
tests/test_axisgrid.py

Closes #2772. Because `PairGrid.map_diag` has logic to disable the y axis visibility when `corner=True`, there's no reason to remove the y axis label when setting up the plot.

Don't remove top left ylabel from corner pairplot with normal diagonal

---

doc/releases/v0.12.0.txt
seaborn/regression.py
tests/test_regression.py

Closes https://github.com/mwaskom/seaborn/pull/2540 by adding a test. Closes #2538.
```python
sns.regplot(
tips, x="size", y="total_bill",
x_estimator=np.mean, scatter_kws={"alpha": .5}
)
```

Inherit errorbar alpha from scatter points in regplot

---

doc/docstrings/lineplot.ipynb
doc/releases/v0.12.0.txt
seaborn/relational.py
tests/test_relational.py

This builds on #1744 (thanks to @matzegoebel), handling a merge conflict with some abstractions that made the implementation a little simpler and changing the parameter name to "orient" to align with the objects interface.
Example:
```python
sns.lineplot(fmri, x="signal", y="timepoint", orient="y")
```
Closes #1744.

Implement orient= in lineplot for sorting / aggregating on the y axis

---

seaborn/relational.py
seaborn/utils.py
tests/test_relational.py
tests/test_utils.py

When originally implemented, `scatterplot` had some placeholder parameters for functionality that was originally planned. But that functionality (jittering, aggregation) will be redundant with the categorical plots once they support `native_scale=True`. And because we now enforce keyword arguments, it's no longer necessary to have placeholders that anticipate a future signature ... if we do plan to add these back in the future, they can simply be inserted in a sensible location in the parameter list.

Housekeeping on relational plot parameters

---

seaborn/_oldcore.py
tests/test_axisgrid.py
tests/test_core.py

Closes #2662 
This makes the current behavior of functions that use the old core machinery consistent with the objects interface, so there should be a smooth transition once they are refactored.

Downgrade exception on mapping list length mismatch to warning

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
tests/test_distributions.py

I don't recall if there was any rationale for this originally, but I cannot think of one now!
Fixes #2582

Relax restriction on element type for discrete histplot

---

doc/releases/v0.12.0.txt
seaborn/categorical.py
tests/test_categorical.py

Closes #2508, see also #1878, #824
```python
sns.barplot(tips, x="size", y="tip", hue="sex", width=.4)
```

Add width parameter to barplot

---

seaborn/axisgrid.py
tests/test_axisgrid.py

- Warn/ignore when `ax` is passed as kwarg (closes #2666)
- Set the joint axes to be active (closes #2511)

Minor jointplot user-friendliness

---

seaborn/_core/plot.py
tests/_core/test_plot.py

This was a bit of a holdover hack. The solution is not great, but at least it's not technically illegal.
Also fixes legend to now show `None` as a title for anonymous semantic variables.

Remove private attribute access in compound legend

---

pytest.ini
seaborn/_core/plot.py
seaborn/_core/properties.py
seaborn/_core/scales.py
seaborn/_marks/base.py
seaborn/_stats/histograms.py
tests/_core/test_plot.py
tests/_core/test_scales.py
tests/test_categorical.py

e.g.
```python
(
so.Plot(tips, "total_bill")
.add(so.Bar(), so.Hist())
.scale(x=so.Continuous().label(like="${x:.0f}"))
)
```
```python
(
so.Plot(planets, "distance")
.add(so.Bar(), so.Hist())
.scale(x=so.Continuous().label(unit="pc"))
)
```
This also makes log transformed scales default to a log formatter (closes #2840)
```python
(
so.Plot(planets, "distance")
.add(so.Bar(), so.Hist())
.scale(x="log")
)
```
This also shortens the `transform` `Scale` parameter to `trans`, as testing revealed that typing out `transform` is a little cumbersome.

Add Scale.label interface for formatting ticks

---

doc/releases/v0.12.0.txt

Commit 533b6005bf1e8d85616fc10be9460b6afca7d791 removed the option to pass additional keyword arguments to `pointplot`. This PR adds this API change to the v0.12.0 release notes.

Mention pointplot additional kwargs removal in the release notes

---

seaborn/_marks/bars.py
tests/_marks/test_bars.py

A few tweaks here:
- Skip bars with 0 height
- Add sticky edges to clamp the axis limits at the bottom of the bar
- Clip the bar artist to avoid edges extending beyond the bar extent
The third tweak is the most interesting think here, although I am somewhat concerned it will cause problems in the future and I am thinking of it as an experimental solution for now. The idea is to avoid the effect that you get at the interface of dodged or stacked bars with nontrivial edge widths:
```python
so.Plot(tips, "time", color="sex").add(so.Bar(edgewidth=5, fill=False), so.Hist(), so.Dodge())
```
Old:
New:
One aspect of the implementation that I don't love is the need to double the internal linewidth and half the dashes (when present). That could cause some unpleasant surprises when working with the …

Improve visual appearance of Bar mark

---

seaborn/_marks/bars.py
seaborn/_marks/base.py
seaborn/_marks/scatter.py
seaborn/objects.py
tests/_marks/test_bars.py
tests/_marks/test_base.py

Similar to how we have `Line`/`Lines`, the `Bars` mark uses a `PatchCollection` for more efficient drawing. (Unlike with `Lines`, we don't need to reduce the mappable properties). This can have a substantial effect:
```python
x = np.linspace(-3, 3, 1000)
y = np.exp(-(x ** 2))
%time so.Plot(x, y, color=x).add(so.Bar()).save(io.BytesIO())
%time so.Plot(x, y, color=x).add(so.Bars()).save(io.BytesIO())
```
```
CPU times: user 2.66 s, sys: 20.3 ms, total: 2.68 s
Wall time: 1.65 s
CPU times: user 918 ms, sys: 12.3 ms, total: 930 ms
Wall time: 397 ms
```
The default property values for `Bars` are also a little different: `width` is set to 1, edges use the `patch.linecolor` rc parameter, and edge widths are automatically set using the same approach in `histplot` to scale down for a dense plot. …

Add Bars for more efficient bar plots and improve Bar as well

---

seaborn/_marks/area.py
tests/_marks/test_area.py

Previously `Area` generated `PolyCollection` artists to match what `ax.fill_between` does, but I don't think it would be very common to need to extra speed you get with that for this type of mark, and the `Polygon` patch artist is easier to work with.
This PR also adds in (copies — blegh) the artist clipping and sticky edges previously applied to Bar marks (#2889).
Closes #2890

Change Area/Ribbon to generate Polygon patches and add clipping trick

---

seaborn/_core/plot.py
tests/_core/test_plot.py

I still feel slightly non-committal about this having its own distinct method, but I think this is probably the most straightforward approach.
This has the nice feature of accepting and converting various units, including on a Nominal scale:
```python
(
so.Plot(diamonds, "price", "clarity")
.add(so.Scatter(), move=so.Jitter(.8))
.limit(x=(0, 20000), y=["VS1", "SI2"])
)
```
Closes #2871

Add Plot.limit method

---

seaborn/_core/plot.py
seaborn/axisgrid.py

There are small typos in:
- seaborn/_core/plot.py
- seaborn/axisgrid.py
Fixes:
- Should read `transforms` rather than `tranforms`.
- Should read `joint` rather than `jount`.
- Should read `disabled` rather than `disabeled`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Another specific configuration method. Like `Plot.limit`, also subject to changes before release on the name (and on whether it should be a distinct function) but status quo bias is strong.
Accepts a string, a function, or `None`:
```
(
so.Plot(tips, "day", "total_bill", color="sex")
.add(so.Bar(), so.Agg(), so.Dodge())
.label(x=str.capitalize, y="Total bill ($)", color=None)
)
```
This API will entail a separation between the text of the labels and any other configuration of them, and I am not sure where other configuration should live as of the moment.

Add Plot.label method

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Store figsize in _figure_spec object

---

doc/releases/v0.12.0.txt
seaborn/rcmod.py
tests/test_rcmod.py

Matplotlib's default is now C0, so the facecolor should match the first
color in the cycle by default.
crossref: #2901

Don't modify patch.facecolor in set_palette

---

seaborn/_compat.py
seaborn/_core/plot.py
tests/_core/test_plot.py

- Refactors `_transform_coords` and `_setup_scales` into one method.
- Properly handles scale config for coordinate variables that are computed during the stat
- Properly handles scale config when only coordinate ranges are defined
Fixes #2908, fixes #2885

Make scale config apply to variables computed by the stat transform

---

seaborn/_core/plot.py
seaborn/_core/scales.py
seaborn/_marks/bars.py
seaborn/_marks/lines.py
seaborn/_stats/aggregation.py
seaborn/_stats/histograms.py
seaborn/objects.py
tests/_marks/test_lines.py
tests/_stats/test_aggregation.py

This PR adds a new mark and a new stat that together will add error bars to aggregations:
```python
(
so.Plot(diamonds, x="carat", y="clarity")
.add(so.Interval(), so.Est("mean", "sd"))
.add(so.Dot(), so.Agg())
)
```
The `Est` stay has the same basic API for error bar selection as we'll be rolling out for the functional interface in 0.12 (i.e., `ci`/`se`/`pi`/`sd`, with an optional scale/level parameter.
Note that is currently necessary to add two layers to get a dot + interval; see #2911 for some ideas there
This PR also addresses some wrinkles relating to matplotlib capstyles in both the interval mark and existing line marks.

Add Est stat and Interval mark to show error bars

---

seaborn/_core/plot.py
tests/_core/test_plot.py

See #2912 for an example of this not working properly.
Fixed:
```python
(
so.Plot(tips, "day", "total_bill", color="smoker")
.add(so.Bar(fill=False, edgewidth=2), so.Agg(), so.Dodge())
.add(so.Interval(linewidth=2), so.Est(), so.Dodge())
)
```

Fix dodging with interval marks

---

doc/whatsnew/v0.12.0.rst
seaborn/axisgrid.py
seaborn/utils.py

It's not necessary to use `rc_context` because we know exactly what parameter we want to change (although it does require implementing a custom context manager).
The only effect of this rcparam is to toggle the layout parameter of `plt.figure()` (actually `mpl.figure.Figure`), so really we could just pass a parameter there. But matplotlib is in the middle of a dance with the `tight_layout`/`layout` parameters, so handling the various forwards/backwards compatibility issues seems too complicated for now.
Fixes #2914
More context at https://github.com/matplotlib/matplotlib/issues/23298

Workaround for matplotlib rc_context issue

---

doc/whatsnew/v0.12.0.rst
seaborn/axisgrid.py
tests/test_axisgrid.py

These two methods accept an function that operates on a `Grid` object to do additional customization of the plot. The methods are very similar, but `apply` returns the `Grid` it is attached to while `pipe` returns the value from the passed function. The objective is to make it easier to do arbitrary customization without catching the return value and switching to an imperative programming style.
Example:
```python
def slopeline(grid, slope, **kwargs):
grid.ax.axline((0, 0), slope=slope, **kwargs)
(
sns.relplot(tips, x="total_bill", y="tip")
.apply(slopeline, slope=.2, color=".6")
.set_axis_labels("Total bill", "Tip")
)
```
Additionally, fixed two methods (`tight_layout` and `refline`) that were not returning self.

Add apply and pipe methods to Grid objects for fluent customization

---

doc/_docstrings/stripplot.ipynb
doc/_docstrings/swarmplot.ipynb
examples/jitter_stripplot.py
seaborn/categorical.py

The `legend` argument was added in #2828 but is not documented (it is mentioned in the release notes). This PR documents this argument, and uses it in the docstrings and one `stripplot` example.

Document the legend argument of categorical scatterplots

---

seaborn/_core/plot.py
tests/_core/test_plot.py
tests/_marks/test_lines.py

This PR adds a `Plot.theme` method for controlling the appearance of data-independent plot elements, using matplotlib rc parameters.
**This is a provisional approach for the initial release and will be improved over time.**
Currently, `Plot.theme` accepts one positional-only argument, which should be a dictionary of rc parameters. To use "seaborn themes", you can call the relevant functions in the `seaborn` namespace (`sns`):
```python
(
so.Plot(diamonds, "clarity")
.add(so.Bar(), so.Hist())
.theme({**sns.axes_style("whitegrid"), "patch.linewidth": 3})
)
```
This is a little clunky; I do expect that it will become possible to use "named' themes more directly, but I am not sure what that interface should look like yet.
This also makes the default theme *independent of other matplotlib rc …

Add rudimentary themeing support

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Following on #2919 to support titles. It expands the API in a few ways:
1. The `title=` parameter allows setting directly a title for a single-axes plot
```python
so.Plot().label(title="Here is a plot")
```
2. The `title=` parameter also can be passed a function that operates on the auto-titles in a faceting context
```python
so.Plot().facet(["a", "b"]).label(title=str.capitalize)
```
3. The `col=` or `row=` parameters accept a string that adds a prefix to facet titles:
```python
so.Plot().facet(["a", "b"], ["x", "y"]).label(col="Column", row="Row")
```
Note two relevant changes from the way titles work in `FacetGrid`:
- A label for the variable name is not added by default
- The order of the titles is `{col} | {row}`, corresponding to the change in the order of positional arguments …

Allow Plot.label to control title(s)

---

seaborn/_statistics.py
tests/test_statistics.py

Work around Series.agg non-aggregation behavior in EstimateAggregator

---

doc/whatsnew/v0.12.0.rst
seaborn/axisgrid.py
tests/test_axisgrid.py

Closes https://github.com/mwaskom/seaborn/issues/2491
`FacetGrid` and `PairGrid` now have a `tick_params()` method, which will iterate over each `Axes` in the grid and call its `tick_params()` method. Some examples:
```python
tips = sns.load_dataset('tips')
g = sns.FacetGrid(tips, col='time', row='sex')
g.map(sns.scatterplot, 'total_bill', 'tip')
g.tick_params(direction='in', length=6, width=2) # on both
g.tick_params(colors='blue', axis='x')
g.tick_params(colors='green', axis='y')
```
```python
penguins = sns.load_dataset('penguins')
g = sns.PairGrid(penguins, diag_sharey=False, corner=True)
g.map_lower(sns.scatterplot)
g.map_diag(sns.kdeplot)
g.tick_params(direction='in', length=6, width=2, color='blue')
```

Adding Grid.tick_params() method.

---

tests/test_categorical.py

I noticed that running the `test_categorical.py` file prints out a lot of `FutureWarnings` (see below for some examples), which aren't being checked for the in the tests themselves. Since the `ci` parameter is being deprecated in `barplot()` (https://github.com/mwaskom/seaborn/pull/2866), I updated these tests to use `errorbar` as indicated in the `FutureWarning`. There were also cases of `palette` being provided without `hue`, which I addressed as well.
```
tests/test_categorical.py::TestBarPlotter::test_unaligned_index
/Users/stefanie/seaborn/tests/test_categorical.py:2357: FutureWarning:
The `ci` parameter is deprecated. Use `errorbar='sd'` for the same effect.
cat.barplot(x=self.g, y=self.y, ci="sd", ax=ax1)
tests/test_categorical.py::TestCatPlot::test_plot_colors …
```

Switch barplot tests from ci to errorbar

---

doc/whatsnew/v0.12.0.rst
seaborn/utils.py
tests/test_distributions.py

This fix prevents margins from increasing when multiple rugplots are
added to the same `ax`, even if `expand_margins` is `False`.
As a minimum reproducible example (which is similar to the added unit test):
```py
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt
values = np.linspace(start=0, stop=1, num=5)
ax = sns.lineplot(x=values, y=values)
sns.rugplot(x=values, ax=ax)
ylim = ax.get_ylim()
for _ in range(4):
sns.rugplot(x=values, ax=ax, expand_margins=False)
if not all(a == b for a, b in zip(ylim, ax.get_ylim())):
print(f'{ylim} != {ax.get_ylim()}')
plt.suptitle("Example showing that multiple rugplots cause issues")
plt.show()
```
Running the above code:
```sh
$ pip install seaborn numpy matplotlib; python3 test.py
(-0.1, 1.1) != (-0.61051, 1.14641) …
```

Fix: shifting margins caused by multiple rugplots

---

doc/api.rst
doc/nextgen/api.rst
doc/nextgen/demo.ipynb
seaborn/_marks/area.py
seaborn/_marks/line.py
seaborn/objects.py
tests/_marks/test_area.py
tests/_marks/test_line.py

- `Band` is more consistent with `err_style="band"` in the existing `lineplot` and is shorter
- `Range` is more about brevity than consistency, but `Interval` could be useful as a stat in the future. I went back and forth on this one a lot, `Span` could also work but I think that will be held in reserve for a bar-type interval mark. FWIW `Range` is consistent with `geom_pointrange`/`geom_linerange`.

Renaming: Ribbon -> Band, Interval -> Range

---

doc/nextgen/demo.ipynb
seaborn/_core/moves.py
seaborn/_core/plot.py
tests/_core/test_moves.py
tests/_core/test_plot.py

Small code change that has fairly large implications for how to think about the specification of a plot layer.
Previously, a layer was defined as a tuple of `(Mark, Stat, Move)`, where `Stat` and/or `Move` were optional. This was extended to allow multiple `Move` operations, by also allowing `(Mark, Stat, List[Move]`). I would also like to support multiple `Stat` operations (e.g., `Bin` then `Agg`).
But the distinction between `Stat`/`Move` is not especially meaningful. I think it can be roughly defined in terms of `Move` only changing the values in the data, not the shape of the data, whereas `Stat` is allowed to change the shape. But both are fundamentally transforms that are applied to the data, in serial, before plotting.
So in the revised API, the distinction is collapsed, and a …

Accept Stat and/or Move(s) as anonymous positional args in Plot.add

---

doc/nextgen/api.rst
doc/nextgen/demo.ipynb
doc/nextgen/index.ipynb
seaborn/_core/plot.py
tests/_core/test_plot.py

A few important API changes here:
- `Plot.configure` has been renamed to `Plot.layout`. It's shorter and better focused on what this method is about.
- The `sharex`/`sharey` parameters have moved out of this method and into a new `Plot.share` method. I expect that this method will eventually generalize to other variables (i.e., allowing different color scales in subplots), but that's currently blocked on having a better story for legend configuration.
- The `figsize` parameter in `Plot.configure`/`Plot.layout` has been shortened to just `size`.
- An `algo` parameter has been added to `Plot.layout`, accepting `"tight"`, `"constrained"`, or `None`.
This PR has an additional tweak to fact that legends are currently not visible in an interactive pyplot window. When calling `Plot.show`, the …

Rename Plot.configure -> Plot.layout, add Plot.share, and modify Plot.layout parameters

---

.github/workflows/ci.yaml

With a semi-recent change in matplotlib, this started flaking at a very high rate,
and it's never turned up an actual issue, so I don't think we need it.

Remove Tk backend build from Github CI

---

seaborn/_core/plot.py
seaborn/_core/typing.py
tests/_core/test_plot.py

Originally, this method would produce a square matrix with all variables, like `PairGrid` (but not even filtering to numeric).
As the interface has developed, this no longer seems like a good behavior to me. Now there's no default pairing.
I would like to add some sort of regex/wildcard matching, and _maybe_ some way to say `x=<all_numeric_cols>` but that will be for post 0.12.0.
Cleanup includes typing and error handling.

Remove default pairing from Plot.pair and clean up interface

---

seaborn/_core/plot.py
seaborn/_core/subplots.py
tests/_core/test_plot.py
tests/_core/test_subplots.py

1. Fix visibility of internal axis labels with `Plot.pair(wrap=...)`  (Closes #2976)
```python
(
so.Plot(mpg, y="mpg")
.pair(["displacement", "weight", "horsepower", "acceleration"], wrap=2)
.add(so.Dots())
)
```
2. Fix (non-)sharing of axes for distinct variables with `Plot.pair(wrap=1)`
```python
(
so.Plot(mpg, x="mpg")
.pair(y=["displacement", "weight"], wrap=1)
.add(so.Dots())
)
```

Fix visibility of internal axis labels with Plot.pair(wrap=...)

---

seaborn/_compat.py
seaborn/_core/plot.py
seaborn/axisgrid.py
seaborn/cm.py
seaborn/matrix.py
seaborn/palettes.py
seaborn/rcmod.py
tests/_core/test_properties.py
tests/test_categorical.py
tests/test_core.py
tests/test_matrix.py
tests/test_palettes.py
tests/test_relational.py
tests/test_utils.py

- No longer reference the deprecated path for `MatplotlibDeprecationWarning` (we actually don't need to silence this warning at all anymore; we only did so before because this would get called as part of `import seaborn.apionly`).
- Relax test against matplotlib labels with scientific notation as they switched from a dash to a unicode minus
- Add compat layer for registering / accessing matplotlib colormaps with new API
- Switch post-hoc axis sharing to new API
- Add compatibility with new layout engine API

Address breakage from matplotlib 3.6.0rc1

---

seaborn/_core/plot.py
tests/_marks/test_area.py
tests/_marks/test_bar.py
tests/_marks/test_dot.py

This means that `"b"`, `"r"`, etc. will produce theme-consistent colors with `Plot` rather than matplotlib's default (and ugly) pure RGB colors.
It's not 100% ideal because it would be nice to be able to set a different seaborn palette as the default cycle and have the single color codes reflect that (as happens with `set_palette`) but we don't have that functionality yet.

Update the single-letter color codes as part of the Plot theme context

---

.github/workflows/ci.yaml
README.md
ci/utils.txt
doc/README.md
doc/requirements.txt
pyproject.toml

So e.g doing a source checkout and then installing with
```
pip install -e .[dev,docs,stats]
```
will get one set up to run the tests and build the docs in one step.

Use pip extras for installation of dev tools

---

doc/whatsnew/v0.12.1.rst
seaborn/_stats/regression.py
tests/_stats/test_regression.py

Fix: Make PolyFit stat robust to missing data

---

tests/test_categorical.py
tests/test_distributions.py
tests/test_regression.py
tests/test_relational.py

- Update approach to asserting absence of warnings
- Ignore expected RuntimeWarning from numpy

Silence various warnings in test suite

---

.github/workflows/ci.yaml

This PR adds schedule that triggers the CI twice a week (on Monday and Thursday 06:00 UTC). This way changes in the GitHub Actions environment or upstream dependencies that results into failures, errors or warnings can be detected and traced back seperately from code changes.
So If the CI fails, with this schedule, there is always an up-to-date reference run from the master branch to compare it to.

CI: Add biweekly scheduled run to detect changes in environment or dependencies

---

seaborn/categorical.py

This change is proposed to make it explicit in the documentation that 'None' can be used to switch off error bar.

errorbar doc patched

---

seaborn/axisgrid.py
seaborn/categorical.py

fixes #3037 (maybe; it's a naive quick attempt at a fix --- I haven't yet examined your minimium supported versions or anything so this may well fail some of your tests)

use .items() instead of .iteritems() (deprecated)

---

tests/_core/test_plot.py
tests/_marks/test_area.py
tests/_marks/test_bar.py
tests/_marks/test_dot.py
tests/_marks/test_line.py
tests/conftest.py
tests/test_core.py
tests/test_rcmod.py

Some tests were relying on global state that might not be set when tests are run concurrently. This gets everything green over several repeated runs with 8 processes on my laptop.

CI: Make tests more robust to concurrency

---

seaborn/categorical.py
seaborn/distributions.py
tests/_stats/test_histogram.py
tests/test_categorical.py

See https://github.com/pandas-dev/pandas/issues/48673 for context

Update pandas syntax to avoid deprecated behavior

---

pyproject.toml
seaborn/_core/data.py
seaborn/_core/groupby.py
seaborn/_core/plot.py
seaborn/_core/rules.py
seaborn/_core/scales.py
seaborn/_core/typing.py
seaborn/_stats/aggregation.py

Most of these are related to not being able to statically type that the internal dataframe will only have strings for column names. I'm not sure if there's a better way to communicate that to mypy.
I'm also surprised to learn that the index values are not typed as "Hashable"; I guess it makes sense that the value of any index *level* are scalars, but our typing was perhaps a bit off with what we accept for variable specifiers. This may need some additional work as I think we want to be narrower than what pandas technically accepts for index values.

Typing: use pandas-type-stubs and address arising issues

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Fixes #3023
This ended up being a simple typo :(

Fix Plot legend with > 2 layers

---

doc/_docstrings/objects.Band.ipynb
doc/_docstrings/objects.Range.ipynb
doc/whatsnew/v0.12.1.rst
seaborn/_marks/area.py
seaborn/_marks/line.py
tests/_marks/test_area.py
tests/_marks/test_line.py

```python
(
seaice
.assign(Year=df["Date"].dt.year)
.pipe(so.Plot, x="Year", y="Extent")
.add(so.Band())
.add(so.Range())
)
```
Closes #3024

Cover full extent of data in Band/Range when not given min/max explicitly

---

doc/whatsnew/v0.12.1.rst
seaborn/distributions.py
seaborn/utils.py
tests/test_distributions.py

Fixes #3058
```python
geyser = sns.load_dataset("geyser")
sns.kdeplot(geyser, x="waiting", y="duration", cmap="viridis")
```

Fix unfilled kdeplot cmap regression

---

doc/whatsnew/v0.12.1.rst
seaborn/_marks/area.py
seaborn/_marks/line.py

Closes #3059. With the example from that issue:
```python
(
so.Plot(x=falseposrate_logistic, y=trueposrate_logistic)
.add(so.Line(marker="o", pointsize=2))
)
```
I wasn't able to cook up a toy example to demonstrate the problem so I haven't added a separate test for it. Would be a great addition if anyone can come up with one (i.e. not involving scikit learn, etc.).

Use a stable algorithm in sorting marks

---

doc/_docstrings/objects.Perc.ipynb
doc/api.rst
doc/whatsnew/v0.12.1.rst
seaborn/_stats/aggregation.py
seaborn/_stats/order.py
seaborn/objects.py
tests/_stats/test_order.py

```python
(
so.Plot(tips, "day", "total_bill")
.add(so.Dot(), so.Perc(11))
.add(so.Range(linewidth=3), so.Perc([10, 90]), so.Shift(x=.1))
)
```

Add Perc stat for computing percentiles

---

doc/_docstrings/objects.Jitter.ipynb
doc/whatsnew/v0.12.1.rst
seaborn/_core/moves.py
seaborn/_core/plot.py
seaborn/_core/typing.py
tests/_core/test_moves.py

This adds a small amount of `width` jitter (i.e., jitter along the orientation axis proportional to the spacing between marks) by default:
```python
(
so.Plot(penguins, "species", "body_mass_g")
.add(so.Dots(), so.Jitter())
)
```
The default jitter is disabled if any of the other jitter parameters (`x` or `y`) are specified.
Additionally, added API examples.

Make Jitter do something by default

---

doc/whatsnew/v0.12.1.rst
seaborn/_core/plot.py
tests/_core/test_plot.py

Closes #2967
Three changes:
- Margins are now an additive 0.5 rather than a multiplicative 0.05
- Grids are disabled
- Y axis is inverted
```python
(
so.Plot(tips, x="total_bill", y="time")
.add(so.Dots(), so.Jitter())
.layout(size=(6, 3))
)
```
Current:
With this change:
We'll want to allow users to override the grid parameterization. I think we'll need an API for that that is separate from `Plot.theme` and I'm not exactly sure where it should be off the top of my head. `Plot.layout` or on the `Nominal` object itself are two ideas.
I'd also still like this to be supported as a first-class operation in matplotlib, but I'm not sure how likely that is.
It feels like a bit of a hack to have this logic live in `Plot._finalize_figure` with an instance check on the Scale. Alternatively, we …

Tweak nominal scale axes akin to categorical axes in classic seaborn

---

doc/_docstrings/objects.Dash.ipynb
doc/api.rst
doc/whatsnew/v0.12.1.rst
seaborn/_marks/line.py
seaborn/objects.py
tests/_marks/test_line.py

This mark doesn't have a direct analogue in the classic interface but it's kind of like a category-specific rug plot:
```python
(
so.Plot(penguins, "species", "body_mass_g", color="sex")
.add(so.Dash())
)
```
One useful application is to denote the central tendency behind a strip or swam plot:
```python
(
so.Plot(penguins, "species", "body_mass_g", color="sex")
.add(so.Dots(), so.Dodge(), so.Jitter())
.add(so.Dash(), so.Agg(), so.Dodge())
)
```

Add Dash mark

---

doc/whatsnew/v0.12.1.rst
seaborn/relational.py
tests/test_relational.py

Fixes #3006. See the issue for context.

Avoid aggregating in lineplot when not necessary

---

doc/whatsnew/v0.12.1.rst
seaborn/_core/scales.py
tests/_core/test_plot.py
tests/_marks/test_line.py

Fix Plot with no variance in orient dimension

---

doc/whatsnew/v0.12.1.rst
seaborn/_core/scales.py
tests/_core/test_scales.py

Simple change to make it possible *not* to use log formatted (scientific notation) ticks with a log transform:
```python
(
so.Plot(diamonds, "carat", "price")
.add(so.Dots())
.scale(y=so.Continuous(trans="log").tick(at=[300, 1000, 3000, 10000]).label(base=None))
)
```

Allow base=None to disable log formatter in Continuous.label

---

doc/_docstrings/objects.Agg.ipynb
doc/_docstrings/objects.Dodge.ipynb
doc/_docstrings/objects.Est.ipynb
doc/_docstrings/objects.Norm.ipynb
doc/_docstrings/objects.Shift.ipynb
doc/_docstrings/objects.Stack.ipynb
seaborn/_core/moves.py
seaborn/_stats/aggregation.py

Ran out of time for these before the v0.12.0 release so this is just filling in some documentation gaps.

Add docstrings and API examples for remaining transform objects

---

Makefile
doc/_docstrings/objects.KDE.ipynb
doc/api.rst
doc/whatsnew/v0.12.2.rst
seaborn/_stats/base.py
seaborn/_stats/counting.py
seaborn/_stats/density.py
seaborn/external/kde.py
seaborn/objects.py
tests/_stats/test_counting.py
tests/_stats/test_density.py

Largely based on the existing `kdeplot` API, although currently only supporting univariate KDE estimation (unlike in the functional interface, there will be separate objects for univariate / bivariate distribution transforms).
```python
so.Plot(penguins, "flipper_length_mm").add(so.Area(), so.KDE())
```
One new trick is that with `gridsize=None`, it will evaluate the KDE at the original datapoints:
```python
so.Plot(tips, "total_bill").add(so.Dots(), so.KDE(gridsize=None))
```
This will probably be more useful with a solution for #3053 so that you could have, e.g., a strip plot with color determined by density.

Add KDE stat

---

doc/whatsnew/v0.12.2.rst
seaborn/utils.py
tests/test_distributions.py

Fixes #3115 
```python
rng = np.random.default_rng(43)
data = rng.random(1000)
ax = sns.histplot(data, label="Random Data", stat="density")
ax.legend()
```

Don't pass label when creating color cycle scout

---

doc/_docstrings/objects.Norm.ipynb
doc/whatsnew/v0.12.2.rst
seaborn/_core/plot.py
seaborn/utils.py
tests/_core/test_plot.py

Motivating example (from #3112):
```python
(
sns.load_dataset("penguins")
.melt(["species"], ["bill_depth_mm", "bill_length_mm"])
.pipe(so.Plot, x="value", color="species")
.facet("variable")
.add(so.Bars(), so.Hist(common_bins=["col"]))
.share(x=False)
)
```
Before:
After:
(This is a little artificial because you could just use `Plot.pair` here but there are other cases where you'd actually want faceting).

Compute spacing/width separately for unshared axes

---

seaborn/axisgrid.py

As the title says, it fixes a copy & paste error in the docstring for `FacetGrid.set_titles` :smiley:.

Fix a copy & paste error in the docstring for FacetGrid.set_titles

---

doc/whatsnew/v0.12.2.rst
seaborn/distributions.py
tests/test_distributions.py

Fixes #3171
```python
x = np.random.lognormal(0, 1, 1000)
ax = sns.histplot(x=x, log_scale=True, kde=True)
```

Fix log scaled histplot kde

---

seaborn/_core/plot.py
seaborn/_oldcore.py
seaborn/categorical.py

pandas 2.0 will enforce the deprecation of the option `use_inf_as_null` in favor of `use_if_as na`, so changing the usages I found in seaborn

COMPAT: Change pandas use_inf_as_null to reflect 2.0 deprecation

---

doc/whatsnew/v0.12.2.rst
seaborn/relational.py
tests/test_relational.py

Fixes #3179 
With (modified) example from that issue:
```
g = sns.relplot(data=iris, x='sepal_length', y='sepal_width', col='species', 
col_wrap=2, height=2.5, facet_kws=dict(sharex=False, sharey=False))
```

Fix inner axis visibility in relplot with unshared axes

---

doc/whatsnew/v0.12.2.rst
seaborn/_core/scales.py
seaborn/utils.py
tests/_core/test_plot.py
tests/test_relational.py

Fixes #3174:
This takes the shortest path solution of simply disabling the offset / scientific notation on a scalar formatter used in the legend. I think it's possible that we'll want to add those as options in `Continuous.label` in which case we may want to figure out how to show the extra information in a legend context (e.g. as a subtitle or extra row at the bottom of the legend). Punting on that as it seems complicated.
Note that if you do want to format legend entries with scientific notation, you can do `Continuous().label(like="{x:.2g}")` (not exactly the same thing, but will help when variables have very large values).

Don't use offset / scientific notation in numeric legends

---

pyproject.toml

A bug in numpy 1.24.0 hard-breaks a number of seaborn functions: https://github.com/numpy/numpy/issues/22826
Marking the whole release as non-compatible to avoid trouble.

Mark numpy 1.24.0 as non-compatible

---

doc/whatsnew/v0.12.2.rst
seaborn/_core/plot.py
seaborn/_core/scales.py
tests/_core/test_plot.py
tests/_core/test_scales.py

Fixes #3186 
With reprex from that issue:

Improve robustness to empty data in Plot and Nominal

---

doc/whatsnew/v0.12.2.rst
seaborn/_core/exceptions.py
seaborn/_core/plot.py
seaborn/_marks/base.py
seaborn/palettes.py
tests/_core/test_plot.py
tests/_core/test_scales.py
tests/test_distributions.py

Because most `so.Plot` methods simply define a spec and defer operations until the time when the plot is compiled, errors caused by bad user inputs (or seaborn edge cases) that cannot be trivially detected may not arise until later and will not be clearly connected to the problem.
In general I'd like to try and be as helpful as possible with what we actually raise to avoid this becoming a pain point for the new interface. This PR represents the first step, defining a `PlotSpecError` exception class that gets raised in an exception chain to provide some additional context that may help diagnose issues. Right now the use is limited to scale setup and scaling operations and the main benefit is that the exception message can call out the plot variable that was being processed when an …

Improve user feedback for errors during plot compilation

---

doc/whatsnew/v0.12.2.rst
seaborn/_core/scales.py
tests/_core/test_scales.py

Fixes #3106 in a narrow way by avoiding a TypeError when sorting out the normalization:
This result isn't ideal, we'd like to propagate the boolean-ness of the data through to the visualization, but this is consistent with other numpy / matplotlib behavior where boolean data are upcast to 0/1 floats in numeric contexts. So boolean data should still get a non-continuous scale by default but contra #3135 I think there should be a separate `Boolean` scale concept rather than default to `Nominal`.

Avoid exception from Continuous scale for normed property with non-float data

---

seaborn/categorical.py
tests/test_categorical.py

Fixes issue #3118, by checking whether `self._hue_palette.levels` is `None` before calling `len` on it.

Fix issue when an empty palette is provided for an empty dataset

---

.github/workflows/ci.yaml
ci/deps_pinned.txt
pyproject.toml
seaborn/_core/rules.py
tests/_core/test_plot.py

These more-or-less follow the guidelines in [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) (we're a little ahead of schedule on numpy 1.20 but I don't expect 0.13.0 to go out before it's inside the window).
Additionally, drops support for Python 3.7 and adds Python 3.11 for the main CI build environment.

Increase minimally-supported versions of Python and dependencies

---

seaborn/_compat.py
seaborn/_core/plot.py
tests/_core/test_plot.py

Fixes #3211 
The intended behavior here was to avoid overriding the user's choice of layout engine when they provide a matplotlib object with `Plot.on`, but `None` was getting passed through to `Figure.set_layout_engine` which unsets the user's choice (and defers to the rc defaults).

Fix layout engine parameterization when using Plot.on

---

doc/_docstrings/objects.Plot.config.ipynb
doc/_docstrings/objects.Plot.theme.ipynb
doc/_templates/autosummary/plot.rst
doc/_tutorial/objects_interface.ipynb
seaborn/_core/plot.py
tests/_core/test_plot.py

This PR introduces a mechanism for changing the appearance of _all_ plots made with `so.Plot`. It adds a configuration interface, accessible through `so.Plot.config` (this is an attribute of the class, not an instance). I expect to add a number of configuration objects; this PR adds `so.Plot.config.theme`, which exposes a dictionary of rcParams that will be used by default in all `Plot` plots, unless overridden by `so.Plot().theme()`. So to change the appearance of all plots, you could put at the top of your notebook:
```python
theme = sns.axes_style("whitegrid") | sns.plotting_context("talk")
so.Plot.config.theme.update(theme)
```
then do
```python
so.Plot()
```
To use the matplotlib globals (whether determined by a `matplotlibrc` file or functions that modify the global state, you'd …

Add default theme configuration to Plot

---

doc/_docstrings/objects.Plot.config.ipynb
seaborn/_core/plot.py
tests/_core/test_plot.py

`Plot` renders images in a Jupyter notebook not through the matplotlib "inline" backend but by returning data through the rich display hooks (e.g. `_repr_png_`). This PR makes that system configurable, with the following new behaviors.
It is now possible to emit svg images, rather than pngs:
```python
so.Plot.config.display["format"] = "svg"
(
so.Plot(penguins, "bill_length_mm", "bill_depth_mm", color="species")
.add(so.Dot(fill=False))
)
```
Well, that's a screenshot .... but trust me it's an svg:
Both png and svg elements (but not the underlying images) are scaled to be equivalent size, and this scaling is configurable:
```python
so.Plot.config.display["scaling"] = 1  # Default is 0.85
```
Additionally, pngs are rendered for HiDPI screens with 2x the "apparent" DPI and then scaled down, …

Add notebook display configuration for Plot, including SVG output

---

seaborn/_core/plot.py
seaborn/_marks/bar.py
tests/_marks/test_bar.py

Fixes #2907:
```python
x = np.random.lognormal(10, 1, 1000)
so.Plot(x).add(so.Bars(edgewidth=0, alpha=.5), so.Hist()).scale(x="log")
```
Contra #3138, the approach here defers the "unscaling" of the width computation to the Mark's drawing logic, rather than adding a new variable to the post-transform data. The reason for this is that we will likely need other kinds of width/spacing-relative properties, such as errorbar or boxplot caps. This approach lets us compute what we need for each mark rather than adding a different "base" variable for each kind of width.
I don't really like needing to access `scales[orient]._matplotlib_scale` within the `Mark`. One alternative would be to pass the `Axes` into `BarBase._make_patches` and access the transform that way. But this may indicate a more …

Fix Bar(s) width on nonlinear scale

---

seaborn/utils.py
tests/test_utils.py

This PR is a fix for https://github.com/mwaskom/seaborn-data/issues/24. It assumes there is a file called `dataset_names.txt` in the `seaborn-data` repository containing all the available dataset names. Each line should contain the name of the file without extension.

Retrieve list of available datasets from a github url with correct CORS headers set.

---

seaborn/distributions.py
seaborn/utils.py
tests/test_distributions.py

Fixes an issue introduced in (#2449) that primarily affects `histplot` (e.g. #3241) because `ax.bar` adds both patches and a container for the patches, but the current code neglects to clean up the container (and it is used in some cases, e.g. by matplotlib's automatic legend code).

Remove container added when inferring default color for bar artist

---

doc/_docstrings/lineplot.ipynb

Currently the [generate docs](https://seaborn.pydata.org/generated/seaborn.lineplot.html) for lineplot raises a `FutureWarning`:
```python
FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
flights_wide = flights.pivot("year", "month", "passengers")
```
This PR removes the warning by passing in the keywords to pandas.

Adds keyword only arguments to pivot in lineplot docs

---

doc/_docstrings/countplot.ipynb
seaborn/categorical.py
seaborn/utils.py
tests/test_categorical.py

Part of #2429 and followup to #3255, routing `countplot` through the new `barplot` backend code.
See #3255 for a thorough description of the default changes / new features and a link to a demonstration. The same behaviors (aside from the statistical estimation) now apply to `countplot` and to `catplot` with `kind="count"`.
This PR also adds a new ([long-desired](https://github.com/mwaskom/seaborn/issues/1027)) feature: normalization of bar heights to represent percentages or proportions:
```python
sns.countplot(diamonds, x="cut", stat="percent")
```
It is not quite as flexible as the normalization in `histplot` (there is no `common_norm` parameter) but should suffice for most usecases.

Refactor countplot to use common infra and add stat parameter for normalization

---

seaborn/axisgrid.py

In the documentation of [`seaborn.jointplot`](https://seaborn.pydata.org/generated/seaborn.jointplot.html) the docstring for the `hue`  parameter is stated twice. This PR removes the manual added text to show only the (identical) text set via [`_docstring.py`](https://github.com/mwaskom/seaborn/blob/master/seaborn/_docstrings.py).

Fix typo in documentation of "seaborn.jointplot"

---

seaborn/rcmod.py

docs: fix typo in docstring

---

seaborn/matrix.py
tests/test_matrix.py

Fix heatmap `norm=None` issue

---

examples/heat_scatter.py
seaborn/_compat.py
seaborn/axisgrid.py
seaborn/utils.py
tests/test_axisgrid.py
tests/test_categorical.py
tests/test_relational.py
tests/test_utils.py

`matplotlib==3.7.0` warns upon accessing the `legend.legendHandles` attribute, which is an undocumented legend attribute (see https://github.com/matplotlib/matplotlib/pull/24538). This PR changes the usage of this attribute to the new documented way of accessing the handles (`legend.legend_handles`).
The fix involves a dedicated function in `seaborn._compat` module.

Avoid matplotlib 3.7.0 warnings

---

doc/_docstrings/heatmap.ipynb

1. Using keyword-arguments on `.pivot` call, to avoid FutureWarning when pivoting only using positional arguments (see current version of [sns.heatmap docs](https://seaborn.pydata.org/generated/seaborn.heatmap.html#seaborn.heatmap#examples) - first example). To verify the validity of the change, this code can be used:
```
import pandas as pd
positional = sns.load_dataset("glue").pivot("Model", "Task", "Score")
kw = sns.load_dataset("glue").pivot(index="Model", columns="Task", values="Score") 
pd.testing.assert_frame_equal(positional, kw)
```
2. Removed empty code cell in the end of the document.

Docs fix - heatmap.ipynb.

---

seaborn/_core/plot.py
seaborn/matrix.py
tests/test_axisgrid.py
tests/test_matrix.py
tests/test_regression.py
tests/test_relational.py

This PR addresses deprecations in the forthcoming numpy 1.25 and also removes some unreachable code paths.

MAINT: address numpy125 deprecations

---

.github/workflows/ci.yaml

Fixes #3318.
As mentioned in the issue, this PR adds top-level read-only permissions to ci.yaml. This helps protect the project from supply-chain attacks.

Add read-only permissions to ci.yaml

---

seaborn/categorical.py
tests/test_categorical.py

This pull request fixes bug #3272. Now, sequential calls to seaborn.pointplot, where the oriented axis is categorical, will display all data properly. As a quick demo, here is the output of my code on the original example:
```
sns.pointplot(
x=pd.Series(["a", "b", "c"], index=[1, 2, 3]),
y=pd.Series([1, 2, 3], index=[1, 2, 3])
)
sns.pointplot(
x=pd.Series(["b", "c", "d"], index=[1, 2, 3]),
y=pd.Series([3, 4, 5], index=[1, 2, 3])
)
```
Inside `categorical.py::plot_points`, the variables `positions` is used to reindex the data about to be plotted, which is needed to include null-values for certain categories. However, `positions` took the explicit list of categorical variables passed in, and assigned them values starting from 0, instead of their correct positions with respect to the …

Fixed mwaskom/seaborn#3272

---

pyproject.toml

Workaround for the issue in #3322

Temporarily restrict sphinx version to unbreak docs build

---

doc/whatsnew/v0.13.0.rst
seaborn/relational.py
tests/test_relational.py

Dear @mwaskom,
I would love to contribute to the amazing project, so I have tried to resolve issue [3230](https://github.com/mwaskom/seaborn/issues/3230).
Issue: The `kws` dict contained a list of tuples of `dashes` instead of single tuple for plotting.
Solution: Revert code partially back to changes made [here](https://github.com/mwaskom/seaborn/pull/2449/files)
Prevention: add an additional test to check for the existing issue

Bugfix issue 3230

---

seaborn/_core/plot.py
seaborn/palettes.py

The `colorConverter.cache` manipulation is not actually doing what appears to be expected.
Since mpl 2.0 (matplotlib/matplotlib#6382), whenever `colorConverter.colors` is updated, `colorConverter.cache` is emptied.
Thus in each location where it is accessed within seaborn, only the last element (`"k"`) actually survives in the cache at all.
Additionally, internal matplotlib usage uses the `("color", alpha)` tuple as the cache keys rather than just the `"color"`, so I don't think that `"k"` will ever be looked up by mpl code even though it is in the cache.
As such, I thought the simplest solution was to simply remove the cache manipulation entirely, since it has no ill effect, and the cache of old values is correctly invalidated regardless.
This was found as I have been running type …

Remove matplotlib cache manipulation

---

seaborn/_core/rules.py
seaborn/_oldcore.py

this shows up in the outputs from https://github.com/mwaskom/seaborn/pull/3340

pandas 2.0 compat: address is_categorical_dtype deprecation

---

seaborn/palettes.py
seaborn/regression.py

The missing second colon prevented the examples for `regplot` and `mpl_palette` from being included in the documentation.

DOC: Fix typo in include directive

---

seaborn/categorical.py
tests/test_categorical.py

Aligns the new/refactored bar plots with features recently added to `boxplot` and `countplot`:
```python
sns.barplot(tips, x="day", y="total_bill", hue="sex", fill=False, gap=.2)
```

Add gap/fill parameters to barplot and countplot

---

tests/_core/test_data.py

`test_index_alignment_between_series` fails on Windows but passes on Linux. The reason is that the indices of the expected Series are created using the default dtype of an integer np.arange which is int64 on Linux but int32 on Windows (see for instance https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine). The DataFrame default RangeIndex is always of dtype int64.  
With this PR, the range is created with an explicit dtype to make the test independent of the default integer type.

TST: Make test_index_alignment_between_series less brittle

---

doc/_tutorial/color_palettes.ipynb
doc/_tutorial/distributions.ipynb
doc/_tutorial/objects_interface.ipynb
doc/_tutorial/properties.ipynb
seaborn/_marks/bar.py

There are also varying spellings for
* program***m***atically/programatically (6 and 2 occurences, repsectively)
* paramet***e***rize/parametrize (6 and 5 occurences, the latter is the version used by `pytest`)
I guess this is an American vs British spelling thing, not sure which version you want to stick with?

DOC: Fix some typos

---

seaborn/_core/rules.py
seaborn/_oldcore.py
tests/_core/test_rules.py

Addresses an issue introduced with the release of numpy 1.25.0
See https://github.com/pandas-dev/pandas/issues/50124 for some more context.

Avoid error when determining type of variable containing pd.NA

---

seaborn/_core/plot.py
seaborn/_core/rules.py
seaborn/_oldcore.py
tests/_core/test_rules.py
tests/test_core.py

A couple small changes together to marginally improve the situation with mathematical operations that don't understand `pd.NA`/nullable pandas types
- Always cast internal `comp_data` columns to float; fixes #2668, maybe others
- Drop nulls when inferring variable type so that object series containing `pd.NA` are treated as numeric (fixes #2686)

Improve handling of edge cases with nullable dtypes

---

seaborn/axisgrid.py
tests/test_axisgrid.py

Fixes #3406 
I'm not 100% sure why these attributes were originally being case to `ndarray` and this fix does induce a minor API break but I can't really imagine a circumstance where someone would have been doing math on them (they were explicitly cast to object-type anyway) so I can live with it.

Fix PairGrid with column multiindex

---

seaborn/_core/plot.py

Fixes the type in accordance with the intention of #2948. Presumably, this was just an autocomplete typo since docs and functionality all specify `Move` rather than `Mark`.

Fix the type of `Plot.add` `transforms` argument to accept `Move`, not `Mark`

---

tests/test_utils.py

I think we probably don't need the function this is testing anymore post py3 but not really worth getting into that as this is a trivial fix.

Update type test to satisfy new flake8

---

.github/workflows/ci.yaml

Fixes #3435.
This PR hash-pins GitHub Actions to protect the project from supply-chain attacks.

Hash-pin GitHub Actions

---

seaborn/_base.py
seaborn/_core/plot.py

Will be deprecated in pandas 2.1 https://pandas.pydata.org/docs/dev/whatsnew/v2.1.0.html#deprecations

Address inf_as_na pandas deprecation

---

seaborn/_base.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/relational.py
tests/test_base.py
tests/test_categorical.py

This PR updates most sns functions to use the transforms set on a pre-existing matplotlib axes such that statistics are computed in the visualized space. Previously, support for transformed axes was a little spotty, at most supporting log scales (but not similar scales, like symlog).
```python
f, axs = plt.subplots(1, 4, figsize=(6, 3), sharey=True, layout="constrained")
plots = [sns.lineplot, sns.pointplot, sns.boxplot, sns.violinplot]
for ax, func in zip(axs.flat, funcs):
ax.set_yscale("symlog")
plot(diamonds, x="color", y="price", ax=ax)
```
This also fixes #3352, a bug introduced in the v0.13 dev series when jumping the gun on this functionality.
Arbitrary scales are also now handled properly on the orient axis of categorical plots:
```
f, ax = plt.subplots()
ax.set_xscale("symlog") …
```

Generalize internal scaling operation

---

seaborn/_base.py
seaborn/_core/data.py
seaborn/_core/plot.py
seaborn/_core/typing.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
tests/_core/test_data.py
tests/_core/test_plot.py
tests/conftest.py
tests/test_axisgrid.py
tests/test_base.py

This PR leverages the [dataframe interchange protocol](https://data-apis.org/dataframe-protocol/latest/index.html) to let seaborn consume objects from other dataframe libraries, such as polars.
Dataframes are converted to pandas objects upon consumption, and that is what is used internally by seaborn, so seaborn's statistical operations don't take advantage of any parallelism / out of core / etc. functionality offered by these libraries. While that would be ideal, I don't see it happening any time soon. 
Nevertheless, this should make it easy to prep data in a library of choice and then pipe it to seaborn without thinking too much about the representation.
For testing, my approach is to use a simple mock object that is not (by inheritance) a pandas DataFrame, but that does "support" the …

Support polars and other data libraries via dataframe interchange

---

seaborn/_base.py
seaborn/categorical.py
seaborn/distributions.py
tests/test_base.py
tests/test_categorical.py

This adds a `log_scale` parameter to all categorical plotting functions.
Setting it to `True` (or passing a base) will scale any numeric axes in the plot.
```python
sns.violinplot(diamonds, x="price", y="cut", log_scale=True)
```
If necessary, a pair (e.g. `(True, False)`) can be provided to control the x/y axes independently:
```python
sns.boxenplot(
tips,
x=10 ** tips["size"],
y=tips["total_bill"],
native_scale=True,
log_scale=(True, False)
)
```
Any statistics / aggregations will be computed in log space when using this functionality. (That behavior was added previously as part of the various categorical plot improvements for v0.13.0; this PR only adds the function-level scale parameterization).

Add log_scale to categorical plots

---

seaborn/matrix.py
tests/_core/test_scales.py
tests/test_distributions.py

This is mostly a generalization of the tests to work with both old and new matplotlib
The only production code change is adding `.flat` to one line in the matrix annotation code, all other changes are test-only.
Mostly the test changes were allowing the collection being found to be a `QuadContourSet`, as well as allowing outputs like colors or coordinates to be sequences instead of singular values, or adding `.flat` to values which now get returned as input-shaped arrays instead of automatically flattened arrays.
I was able to avoid version checking for most things, aside from the minor tick expected value and explicitly checking the expected type in `ax.collections`. Though there are some version-checks by proxy of `isinstance` checks.
I did add a boolean flag to shift the filtering of …

Update tests for matplotlib 3.8.0rc1

---

pyproject.toml
seaborn/_base.py
seaborn/_core/plot.py
seaborn/_core/properties.py
seaborn/_stats/counting.py
seaborn/categorical.py
seaborn/distributions.py
tests/_stats/test_density.py
tests/conftest.py
tests/test_categorical.py
tests/test_distributions.py

Various small edits to:
- Maintain forward compatibility with upcoming changes in dependencies
- Avoid triggering some numpy warnings around missing data and discrete mapping logic
- Silence a couple of innocuous warnings there's no clear way to work around
All that remains here are https://github.com/matplotlib/matplotlib/pull/26300, https://github.com/matplotlib/matplotlib/issues/26596 and ~https://github.com/pytest-dev/pytest-xdist/issues/840~ (decided to ignore the latter in the test config, since there's no apparent movement towards dealing with it upstream despite lots of reports).

Squash a large number of warnings in the tests

---

tests/_marks/test_line.py

There is an upcoming change in Matplotlib that unifies the return of `get_linestyle`. Instead, based on the current tests, one should use `get_dashes`. (Will produce a warning for a few releases and then return the linestyle string as other artists.)
~Also added a test as there is `get_dashes` for lines (now).~ Too long since I did the MPL PR clearly, but there will be a `get_dashes` as part of the PR.
(Couldn't run the tests locally because of issues with pywintypes so please bear with me in case it is not working out of the box...)

Change get_linestyle to get_dashes for Collections

---

seaborn/_base.py
tests/test_base.py

Closes #3450
We don't document ndarray as a valid type for `palette` but it has worked by happenstance previously. Some changes in numpy are causing one of the operations we perform on the palette object to break. This PR (1) works around those numpy changes by catching array types and coercing them to lists, and (2) fires a warning about upcoming removal of support of array-typed palettes.
Note that arrays are already disallowed in the objects interface:
```
TypeError: Scale values for color with a Nominal mapping must be string, list, tuple, or dict; not <class 'numpy.ndarray'>.
```

Deprecate accepting an array-typed palette, which is not intentional

---

seaborn/utils.py
tests/test_utils.py

`move_legend` was not originally expected to also allow changing the labels themselves. Personally I think that doing this is fairly dangerous because you may not always know what order the original labels will appear in. But people try, and due to an odd matplotlib edge case, rather than raising (because labels get passed positionally and as part of the user's keyword arguments), it can produce incorrect legend even when the user's legend would otherwise have been correct.
This PR explicitly handles the case where the user supplies `labels`.
Closes #3079

Allow move_legend to overwrite the labels

---

seaborn/_core/plot.py
tests/_core/test_plot.py

This PR enhances the behavior of `Plot.scale` and `Plot.limit` when using `Plot.pair` such that all paired axes can be configured in one step by passing setting just `x` or `y`. Currently, each `x0`, `x1`, ... must be defined. The common scale/limit is treated as a fallback, so specific variables can still be defined separately:
```python
(
so.Plot(planets, x="year")
.pair(y=["orbital_period", "mass", "distance"])
.scale(y="log", y1="sqrt")
.add(so.Dots())
)
```
Closes #2910

Allow x=/y= to control paired scales and limits

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Follow on to #3458 which didn't cover `Plot.label`. While it probably rarely makes sense to use the exact same label in a paired plot, it may be desired to use a consistent formatting function, e.g.:
```python
(
so.Plot(planets, x="year")
.pair(y=["mass", "distance"])
.label(y=str.capitalize)
.add(so.Dots())
)
```

Also allow Plot.label to control all paired axes

---

seaborn/categorical.py
tests/test_categorical.py

There's a longstanding quirk of the categorical plots where line/edge colors can be specified as `"gray"` which actually triggers an automatic computation of a gray value that complements the main colors in the plot. Since `"gray"` is a valid matplotlib color and it's not very obvious that this is happening, this PR migrates the behavior to `"auto"`, with one release cycle of backwards compatibility and a `FutureWarning`.
```python
sns.boxenplot(tips, x="total_bill", hue="time", linecolor="auto", palette="pastel", gap=.1)
```

Change categorical auto gray parameter to "auto", with warning

---

examples/heat_scatter.py
seaborn/_base.py
seaborn/categorical.py
seaborn/relational.py
seaborn/utils.py
tests/test_axisgrid.py
tests/test_categorical.py
tests/test_relational.py
tests/test_utils.py

This PR does a lot of things (blah) but the main goal is that the legends for relational / categorical plots should better represent additional (non-semantic) properties of the artists in the plot.
Examples:
```python
sns.boxplot(tips, x="total_bill", y="time", hue="sex", gap=.1, fill=False, linewidth=3)
```
```python
sns.scatterplot(tips, x="total_bill", y="tip", hue="sex", size="time", marker="x", linewidth=1)
```
```python
sns.violinplot(tips, x="total_bill", y="day", hue="sex", linewidth=1, linestyle="--")
```
There are some important internal changes, notably that scatter plot legends (including strip/swarm plots) now use a `Line2D` artist for the legend handle.
This was a much requested feature but I think it's not without its downsides. For example the following plot is arguably …

Improve relational/categorical legends to show non-semantic properties

---

seaborn/relational.py
tests/test_relational.py

Matplotlib 3.8 makes `scatter` raise when both long and short forms of arguments are passed (e.g. `edgecolor` and `ec`); previously one was silently ignored (I think?).
This is probably a marginal QOL improvement for matplotlib users but has broken the seaborn tests, as `scatterplot` sets a default edge color using the long-form argument but an example in the docs demonstrates the short-form example
This PR uses keyword argument normalization upstream of where seaborn sets its defaults. The whole situation is kind of a mess and this is just a localized bandaid, but it should get the tests green and marginally improve seaborn usability.

Normalize matplotlib kwargs in scatterplot / lineplot

---

seaborn/_base.py
seaborn/_stats/counting.py
tests/test_distributions.py

Two related updates in one PR:
When handling the `log_scale` option by setting a matplotlib axes scale, use `nonpositive="mask"` so that nonpositive values are dropped rather than set to an arbitrarily small value. This avoids surprises where the small value is aggregated, which are actively wrong.
A consequence is that bar plots on a log value scale no longer magically "work" and require the user to explicitly set a `bottom` value. This is unfortunately but IMO a reasonable tradeoff; bar plots on a log value scale are sort of an anti-pattern anyway IMO and this does require one to be thoughtful about what that means and where the bar should start. Ultimately one is going to be surprised either way and I lean towards the plot being surprisingly empty over the plot having surprisingly …

Mask nonpositive values with log_scale and ignore inf data in histogram range

---

seaborn/_stats/counting.py
tests/test_distributions.py

This PR changes the interpretation of the `binwidth` parameter in `histplot` and `objects.Hist`.
With the previous implementation, floating point errors could cause the largest datapoint(s) to be silently dropped. The solution here is to always honor the bin range (either the explicit as specified through `binrange` or implicit as computed from the data range) and to make the actual bin width only approximately equal to the `binwidth` parameter when `binwidth` does not evenly divide it.
I could not think of a simple + robust solution to detect and handle floating point issues while also reliably honoring expected bin ranges, and I think that the expected violation of expectations will be smaller this way, although it is a minor API change. In most cases it should not be noticeable.
Fixes …

Treat binwidth as approximate to avoid dropping outermost datapoints

---

seaborn/categorical.py
tests/test_categorical.py

Fixes an issue introduced in the categorical plot refactor where the dataframe attached to the FacetGrid returned by catplot only contained columns that were used in the plot.

Fix data attached to catplot FacetGrid

---

examples/wide_form_violinplot.py
seaborn/categorical.py
tests/test_categorical.py

As part of the big categorical plot refactor, a default change was made where plots are no longer implicitly color-mapped.
There is a simple path to restoring the previous default behavior (if desired) when using long-form data: add an explicit redundant hue-mapping. e.g. `boxplot(df, x="grp", y="val") -> boxplot(df, x="grp", y="val", hue="grp")`.
But when using wide-form data, there is no equivalent path. So this PR adds some extra backwards-compatibility hacks so that wide-form plots retain the implicit color map. Additionally, wide-form plots can be coerced to a single color by passing `color=`. There is some additional special-casing around `pointplot`, which has always been an exception in its default behavior.

Restore implicit hue for wide categorical data

---

seaborn/categorical.py

Fix an issue inadvertently introduced in #3496

Fix catplot with kind='point' to avoid color warning

---

seaborn/categorical.py
tests/test_categorical.py

We set `edgecolor` by default in these plots but matplotlib warns about that being ignored since we also have `color`. Not actually a problem for us, but better to avoid the non-actionable warning.

Avoid a matplotlib warning for strip/swarmplot with unfilled marker

---

doc/_tutorial/color_palettes.ipynb

The old link https://matplotlib.org/2.0.2/users/colormaps.html is marked by matplotlib as out of date, so this replaces it with the new link https://matplotlib.org/stable/users/explain/colors/colormaps.html that seems to have basically the same information (although it did get shuffled around a wee bit).

Update old mpl color tutorial link

---

seaborn/categorical.py
tests/test_categorical.py

Fix edgecolor in catplot with kind='bar'

---

seaborn/categorical.py
tests/test_categorical.py

Disable legend in case of redundancy
`sns.catplot(tips, x="day", y="total_bill", hue="day", col="sex", row="smoker", kind="box", height=3)`

FIX #3537 Disabling the legend based on the x-axis and hue values

---

seaborn/_base.py
seaborn/_core/rules.py
tests/_core/test_rules.py
tests/test_base.py

I ran into an issue with Seaborn 0.13.0 that wasn't present in previous versions. The following code works fine in Seaborn 0.12.2 but raises ``numpy.core._exceptions._UFuncInputCastingError`` on 0.13.0.
```
from datetime import timedelta
from matplotlib import pyplot as plt
data = {
'delta': [timedelta(1), timedelta(5), timedelta(3)],
'x': [1, 2, 3]
}
sns.scatterplot(data, x='x', y='delta')
plt.show()
```
The reason are numpy's default casting rules and the fact that the check changed from ``np.isin(vector, [0, 1, np.nan]`` to ``np.isin(vector, [0, 1])`` in the latest release. That means that previously the comparison was with ``0.0`` and ``1.0`` as float dtype, because the ``nan`` made NumPy cast the whole test array to float. Now the comparison is against int …

FIX: handle potential TypeError when determining variable type

---

doc/_docstrings/pointplot.ipynb

This PR aims to fix a few typos in the examples of the documentation of [`pointplot`](https://seaborn.pydata.org/generated/seaborn.pointplot.html).

seaborn.pointplot: Fix typos in examples of documentation

---

doc/_tutorial/data_structure.ipynb

Fix small typo in data structure tutorial.
The doc previously said "a few older functions anre more limited".
I changed it to "a few older functions are more limited".

doc typo fix in data structures tutorial

---

seaborn/categorical.py

Pass bootstrap option to boxplot stat computation 

---

seaborn/_base.py
tests/conftest.py
tests/test_relational.py

Corresponds to the case where grouping_var has None object.
Related issue: https://github.com/mwaskom/seaborn/issues/3511

[Fix issue][#3511]lineplot of empty dataframe with hue in seaborn 0.13.0

---

pyproject.toml
seaborn/_compat.py
seaborn/_core/plot.py
seaborn/_core/scales.py
seaborn/_core/subplots.py
seaborn/_marks/bar.py
tests/_core/test_plot.py
tests/_core/test_properties.py
tests/_core/test_scales.py
tests/test_regression.py

PR #3393 updated the minimally supported matplotlib version to 3.4. This PR removes code handling (and metadata) of matplotlib versions that are < 3.4. Note that prior to this PR, public package metadata of seaborn 0.13 allows matplotlib 3.3 and above as valid dependencies but pinned version for ci is 3.4.

MAINT: remove obsolete matplotlib version compatibility

---

doc/_docstrings/barplot.ipynb

This PR aims to fix a typo in the documentation of `seaborn.barplot`.

seaborn.barplot: Fix typo in docs

---

doc/_docstrings/objects.Est.ipynb
seaborn/_statistics.py
seaborn/_stats/aggregation.py
tests/_stats/test_aggregation.py
tests/test_statistics.py

This PR enhances `seaborn.objects.Est` to support a weighted mean, with confidence intervals:
```python
diamonds = sns.load_dataset("diamonds")
(
so.Plot(diamonds, x="color", y="price")
.add(so.Dot(), so.Est(), weight="carat")
.add(so.Range(), so.Est(), weight="carat")
)
```
(I don't know that this plot makes any particular sense, but it demonstrates how you'd use it...)
It is using `np.average` under the hood.
Currently support is limited to `func="mean", errorbar=("ci", ...)`.  There may be other estimators / error bar methods were it makes sense to compute a weighted version (e.g. weighted median/percentiles) although we would need to implement those in seaborn as I don't believe there's an implementation in our dependencies. I think this is fine and probably satisfies the majority of …

Add support for weights in objects.Est

---

seaborn/_statistics.py
seaborn/_stats/aggregation.py
seaborn/categorical.py
seaborn/relational.py
tests/test_categorical.py
tests/test_relational.py
tests/test_statistics.py

Follow-on to #3580
This adds `weights` as an option in `lineplot`, `barplot`, `pointplot`, along with the corresponding figure-level functions.
Note that we are going to have to live with the unfortunate contrast between `weights=` in the function interface and `weight=` in the object interface. That maintains local consistency (the distribution plot functions already use `weights`, while the objects interface has a strong singular parameter name convention) at the cost of global consistency. Given that the parameter naming scheme already differs between the two interfaces, I suppose that I can live with it.
As in `objects.Est`, the use of `weights` currently limits the statistical options to `estimator="mean", errorbar="ci"`. We'd need to add support for other estimators/errorbars on a …

Add weighted estimation in function interface

---

doc/_docstrings/objects.Plot.layout.ipynb
seaborn/_compat.py
seaborn/_core/plot.py
seaborn/_core/subplots.py
tests/_core/test_plot.py

This PR adds the `extent` parameter to `Plot.layout`.
While part of incremental progress towards full fine-grained layout customization through `Plot` methods, this update also helps ease some temporary pains. Namely, it may be useful for keeping the legend "outside" of the plot when using `Plot.show`. Recall that the legend is set to be interior to the figure boundary when `Plot.show` is called — hence, when `pyplot` is used to display the plot — to avoid extending past the boundaries of the `pyplot` window:
```python
(
so.Plot(tips, x="total_bill", y="tip")
.add(so.Dot(), label="Some dots")
.show()
)
```
Setting the right boundary of the extent to <1 leaves room for the legend:
```python
(
so.Plot(tips, x="total_bill", y="tip")
.add(so.Dot(), label="Some dots")
.layout(extent=(0, 0, .8, …
```

Add extent to Plot.layout configuration

---

seaborn/rcmod.py

Crosslink to aesthetics tutorial from set_context/plotting_context

---

seaborn/distributions.py
seaborn/regression.py
tests/test_distributions.py

I noticed these while working on the stubs at typeshed. They felt small enough to include in a single PR.
1. There is a missing `raise ` before `TypeError(msg)` in `kdeplot`
2. The `data` parameter of `lmplot` is required but it has a default of `None`. 20 lines later there is a check that raises a `TypeError` if `data is None`. Removing the default makes sense here to signal to the user that they must pass this argument. It also has two more advantages. The first is that your IDE will now helpfully yell at you if you don't pass the argument. The second is minor but it will allow us to keep running the stub tests for this function at typeshed where we removed the default which made the stub go out of sync with the runtime implementation so we had to skip its tests to pass CI. Note that …

Add a missing raise in kdeplot and slightly improve lmplot signature

---

.github/workflows/ci.yaml

apt-get installs a very old version (https://github.com/jgm/pandoc/issues/8881) of pandoc
In the CI doc build, we get a number of warning messages related to this, some warning messages that I don't otherwise see when I build docs locally (so, maybe related to this) and increasingly-common flakes.
This PR follows the official pandoc instructions to get a newer version: https://pandoc.org/installing.html
It is a little manual based on the github issue linked above, there may be some progress on updating the version in the linux repositories. We should revisit in the future.

Change how pandoc gets installed in CI

---

seaborn/categorical.py
tests/test_categorical.py

Avoid error when dodge=True, hue=None

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Prior to this change, wrapped faceted plots (with shared axis) are created by deletion of some axes from a larger rectangular grid, so axes that are not on the bottom row lose their tick labels. Current code makes sure that all xtick labels are visible, but doesn't ensure that they're on. The proposed PR makes sure all "bottom" axes have their xticklabels on.  
Fixes #3548 :

FIX: Enable xticklabels for all bottom axes

---

seaborn/_base.py
seaborn/_compat.py
seaborn/_core/plot.py
seaborn/_core/properties.py
seaborn/_statistics.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/relational.py
seaborn/utils.py
tests/_core/test_plot.py
tests/_core/test_properties.py
tests/test_matrix.py

This PR removes compatibility code for features from matplotlib<1.4, numpy<1.20, and Python<3.8 as these versions are now obsolete according to the dependencies listed in pyrpoject.toml. There is one test change that was necessary, please see inline comment for explanation.

Cleanup compat code for obsolete versions of dependencies

---

pyproject.toml
seaborn/_base.py
seaborn/_compat.py
seaborn/_core/plot.py
seaborn/categorical.py
seaborn/relational.py
tests/_stats/test_density.py
tests/test_categorical.py

Adapt to deprecations in pandas 2.2.0

---

doc/_docstrings/boxenplot.ipynb

"percentie" -> "percentile"
Hope this is helpful! Thanks for the library.

Fix minor boxenplot docs misspelling

---

tests/test_distributions.py

For numpy 2.0 compatibility; see #3683

Remove reference to deprecated numpy error class in tests

---

seaborn/_core/plot.py

Long-term it might help to look at more of the specific types in annotations and adjust them, but I'd prefer to remain incremental for now.
Fixes #3682

Relax typing strictness for Plot.theme

---

ci/deps_pinned.txt

Seems like they added numpy 2 compatibility but broke compatibility with older numpys.

Try pinning pillow to fix ci

---

tests/_core/test_plot.py

Matplotlib fixed a weird inconsistency in the tick params dict that tests were relying on.

Fix tick visibility introspection on matplotlib 3.10

---

seaborn/_compat.py
seaborn/categorical.py
tests/test_base.py
tests/test_categorical.py

- Address deprecation of `vert=` in `plt.bxp` (used in `sns.boxplot`; closes #3804, closes #3819)
- Address deprecation of the `.converter` attribute on matplotlib `Axis` objects (only used in tests)
- Address deprecation of `np.in1d` (only used in tests)
- Address deprecation of `pytest.mark` + `pytest.parameterize` (only used in tests)
- Prevent tests from tripping internal deprecation warning

Address some upcoming deprecations

---

seaborn/matrix.py
tests/test_matrix.py

Besides `np.ndarray` and `pd.DataFrame` objects, I think it would also be nice to support [array-like objects](https://numpy.org/doc/stable/user/basics.interoperability.html#the-array-method) (PyTorch, Jax, PyArrow arrays, etc.) as the heatmap `mask`.

Support array-like mask in heatmaps

---

tests/test_matrix.py

Addresses a backwards compatibility bug introduced in #3803

Fix mock __array__ interface
