mwaskom/seaborn

seaborn/distributions.py
seaborn/linearmodels.py
seaborn/tests/test_distributions.py
seaborn/tests/test_linearmodels.py

This is intended to address https://github.com/statsmodels/statsmodels/issues/2184, an issue that is breaking the tests and causing problems for people.
This closes #418.
It also should make imports faster in the future, because importing
all of statmodels was overkill for most purposes. Closes #287.

Import selectively from statsmodels

---

seaborn/palettes.py

Show a proper colorbar when as_cmap is True in the palette widgets

---

doc/tutorial/axis_grids.ipynb

Hey -- here's that documentation about writing custom mappable functions. Curious what you think about a) its content, b) its placement in the existing `FacetGrid` notebook (well, I guess that's everything).
Also, you're working some weird voodoo on the notebooks with the `In[null]` and whatnot. I need to figure that out.

WIP: Add docs, examples re: mappable functions

---

seaborn/tests/test_utils.py
seaborn/utils.py

Was exploring functionality and realized that couldn't figure out what datasets you have available for demos.
I guess ideally you should just provide some .json or whatever file which would list all the .csv with descriptions or may be even proper dataset descriptors if you really like to.

NF: get_dataset_names (overdo: test_load_datasets)

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

Cf #560 (don't close the root issue there though)

Fix bug in boxplot where some level had only missing data

---

seaborn/tests/test_utils.py
seaborn/utils.py

Fix spine trimming with inverted axes or empty ticks

---

seaborn/axisgrid.py
seaborn/categorical.py
seaborn/tests/test_axisgrid.py

Fix issues in FacetGrid and factorplot

---

seaborn/categorical.py

Fixed a typo

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

Fixes https://github.com/mwaskom/seaborn/issues/649

Divide by standard dev instead of variance for z-score

---

seaborn/matrix.py
seaborn/tests/test_matrix.py

This fixes #681. I didn't add an extra test, I think the changes are small enough.

changed handling of annot_kws so that standard values can be overwritten

---

seaborn/timeseries.py

Saw a small typo when reading the doc, so here is a fix.

Fixed typo

---

seaborn/matrix.py

Addresses https://github.com/mwaskom/seaborn/issues/750

Remove color_list from dendrogram call

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

This pull request adds the `_LVPlotter` class, `lettervalueplot` function, documentation, and usage examples.
-----------

Letter Value Plots

---

seaborn/rcmod.py
seaborn/tests/test_rcmod.py

AxesStyle & PlottingContext as contextdecorators.

---

seaborn/categorical.py
seaborn/distributions.py
seaborn/linearmodels.py
seaborn/timeseries.py

This is a workaround the random behavior with python 3.4 as described in bug #756

Use facecolor instead color keyword argument to avoid random behaviour

---

seaborn/distributions.py

Fixed a couple typos and inconsistencies in the distribution docs

Fix typos and improve documentation consistency

---

seaborn/tests/test_matrix.py

Remove color_list from dendrogram call in tests

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_utils.py
seaborn/utils.py

These commits fix the Unicode-related issue #719 (see the commit messages for details). It may be possible that there are still more places in the code in which a conversion to Unicode is necessary.

Fix #719: UnicodeEncodingError in FacetGrid

---

doc/releases/v0.7.1.txt
seaborn/__init__.py
seaborn/rcmod.py

Capture original rcparams at import time and use to reset

---

doc/sphinxext/plot_generator.py
examples/many_pairwise_correlations.py
seaborn/external/six.py

Python 3-compliant generators.
Closes #947

Python 3 compatibility for generation of docs

---

doc/releases/v0.8.0.txt
seaborn/distributions.py

Put a cap on the default number of bins for hex jointplot

---

doc/api.rst
doc/conf.py
doc/releases/v0.8.0.txt
seaborn/matrix.py

Turn dendrogram axes off instead of using white background

---

doc/releases/v0.8.0.txt
seaborn/tests/test_utils.py
seaborn/utils.py

Allow side-specific offsets in despine

---

Makefile
seaborn/external/six.py

Update internally packaged six version

---

seaborn/tests/test_categorical.py

Ensure that array size is an int

---

doc/installing.rst
doc/tutorial/distributions.ipynb
seaborn/palettes.py

Fixes availible typo

---

seaborn/categorical.py
seaborn/tests/test_categorical.py

Closes #1122.
See originally #678, this was missed in #782.

Specify violin facecolor not color

---

seaborn/matrix.py

Restore clustermap label rotation

---

doc/releases/v0.8.0.txt
seaborn/palettes.py

Handle new qualitative matplotlib palettes

---

seaborn/distributions.py

added `np.asarray` for input if it is a list. works with 1d and 2d lists , fixes #1186

added list input support for kdeplot

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Validate inputs to JointGrid when using data

---

seaborn/categorical.py

Account for DPI in swarmplot spacing (closes #1008)

---

seaborn/distributions.py

added warning to matrix input for kdeplot.

---

doc/whatsnew.rst
seaborn/matrix.py
seaborn/tests/test_matrix.py

Fix error in clustermap with no yticklabels

---

seaborn/categorical.py

Title is self-explanatory.
Closes #1240.

Remove usage of pandas remove_na function

---

seaborn/matrix.py

- Fix annotations + side colors (closes #1150)
- Fix rotation of yticklabels to avoid overlap

Two small clustermap fixes

---

examples/multiple_regression.py

comments were about the tips dataset, but the examples users iris.

update comments in regression example

---

README.md
doc/releases/v0.9.0.txt
seaborn/regression.py

These were deprecated a while ago, and have not been part of the public API for several releases.

Final removal of coefplot and interactplot

---

setup.py

Include colors submodule

---

doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/matrix.py
seaborn/tests/test_axisgrid.py

Supersedes #1358 and closes #1352

Make JointGrid/jointplot accept lists as data input

---

seaborn/matrix.py

I think this brief comment may help users even conceive of the idea that rows and columns need not cluster with the same metric.

DOC different metrics for axes in clustermap

---

seaborn/distributions.py

Avoid turning off kde axes autoscaling

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Apply ticklabels kwargs to inner FacetGrid axes

---

seaborn/axisgrid.py

Don't fail when function does not have __module__ attribute

---

doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fix FacetGrid bug with single facet level

---

doc/releases/v0.9.0.txt
seaborn/regression.py
seaborn/tests/test_regression.py

Accept list inputs in regplot

---

.gitignore
doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/matrix.py
seaborn/regression.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_regression.py

Small changes addressing various issues; see commit texts.

Assorted compatability fixes

---

doc/releases/v0.9.0.txt
seaborn/axisgrid.py
seaborn/matrix.py

Avoid error when backend has no canvas renderer

---

seaborn/miscplot.py
seaborn/tests/test_miscplot.py

Add catplot companian

---

seaborn/categorical.py
seaborn/matrix.py
seaborn/palettes.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_distributions.py
seaborn/tests/test_matrix.py
seaborn/tests/test_regression.py
seaborn/utils.py

Also touches a few related issues in the tests

Get travis running cleanly again

---

LICENSE
examples/different_scatter_variables.py
examples/distplot_options.py
examples/heatmap_annotation.py
examples/logistic_regression.py
examples/many_pairwise_correlations.py
examples/multiple_regression.py
examples/scatterplot_sizes.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/regression.py
seaborn/relational.py

Pulling in a lot of PRs with small typo fixes and merging them into the v0.9 branch instead of directly into master.

Omnibus typo fixes

---

seaborn/rcmod.py

Closes https://github.com/mwaskom/seaborn/issues/1642

Catch and discard MatplotlibDeprecationWarning in reset_orig()

---

.travis.yml
seaborn/tests/test_axisgrid.py

Trying the solution from here: https://docs.travis-ci.com/user/gui-and-headless-browsers/

Declare xvfb as a Travis service (fixes #1798) and fix other travis issues

---

doc/releases/v0.9.1.txt
examples/jitter_stripplot.py
seaborn/algorithms.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/distributions.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_utils.py
seaborn/utils.py

Merging several PRs onto v0.9
- https://github.com/mwaskom/seaborn/pull/1796
- https://github.com/mwaskom/seaborn/pull/1795
- https://github.com/mwaskom/seaborn/pull/1794
- https://github.com/mwaskom/seaborn/pull/1772/
- https://github.com/mwaskom/seaborn/pull/1762
- https://github.com/mwaskom/seaborn/pull/1736
- https://github.com/mwaskom/seaborn/pull/1728
- https://github.com/mwaskom/seaborn/pull/1716

Small fix onnibus

---

seaborn/axisgrid.py

This will fix #1502, at least the case I reported.

remove hue from pairplot variables (fix #1502)

---

doc/releases/v0.9.1.txt
seaborn/matrix.py
seaborn/tests/test_matrix.py

Exclude norm from clustermap color kwargs

---

doc/releases/v0.9.1.txt
seaborn/palettes.py
seaborn/rcmod.py
seaborn/tests/test_rcmod.py

Avoid error when calling set() with list of colors

---

seaborn/regression.py

Fix simple typo: weidness -> weirdness

---

seaborn/axisgrid.py

Varaible -> Variable
subets -> subsets
paramter -> parameter

Spelling Corrections

---

doc/releases/v0.9.1.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Adapts to a recent change in matplotlib.
Closes #1737
Closes #1602

Fix exception on missing hue levels in pointplot

---

doc/releases/v0.9.1.txt
examples/logistic_regression.py
examples/multiple_regression.py
examples/regression_marginals.py
seaborn/regression.py
seaborn/tests/test_regression.py

Prevent multiple regplots from adding expanding x margins to the plot

---

doc/releases/v0.9.1.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Improve pandas index-based alignment

---

doc/releases/v0.9.1.txt
seaborn/relational.py
seaborn/tests/test_relational.py
setup.py
testing/deps_pinned.txt

Avoid errors with numeric data stored as strings

---

doc/releases/v0.9.1.txt
seaborn/axisgrid.py
seaborn/relational.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_relational.py

Allow FacetGrid legend to work with nested labels

---

doc/releases/v0.9.1.txt
seaborn/palettes.py
seaborn/tests/test_palettes.py

- Address upcoming numpy type-check strictness (fixes #1907)
- Standardize output of color palette functions as rgb tuples

Improve color palette robustness

---

doc/releases/v0.9.1.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #1908 
Closes #1910 
Also improves general test coverage of distribution plots

Improve robustness to missing data in distribution plots

---

doc/releases/v0.9.1.txt
seaborn/relational.py
seaborn/tests/test_relational.py

Avoid error/warning in lineplot when x is categorical with empty levels

---

doc/releases/v0.9.1.txt
seaborn/matrix.py
seaborn/tests/test_matrix.py

Builds on #1426 with some nomenclature changes and tests.
Closes #1426

Control dendrogram properties in clustergrid

---

seaborn/algorithms.py

Follow-up to #1952 that uses the correct dtype

Use numpy's indexing dtype in bootstrap

---

doc/releases/v0.10.1.txt
seaborn/regression.py
seaborn/tests/test_regression.py

Follow up to #1958 
cc @MaozGelbart

Don't fail in regplot on singletons, don't fit regression either

---

seaborn/tests/test_utils.py

Since the `sig_stars()` function in utils.py doesn't have tests. I added the tests to increase the coverage test.

added tests for sig_stars() function

---

README.md
doc/_templates/layout.html
doc/conf.py
doc/installing.rst
doc/introduction.ipynb
doc/tutorial/color_palettes.ipynb

Related to #1984
PS: For colorbrewer2 https is not yet available, so I raised awareness upstream at https://github.com/axismaps/colorbrewer/issues/28 .

Make all links possible use https://

---

seaborn/palettes.py
seaborn/tests/test_palettes.py

Incorporates and closes #1998 
Fixes #1994

Avoid floating point error with maximum husl sat/lum

---

doc/releases/v0.10.1.txt
seaborn/categorical.py

Autoscale in swarmplot to get valid transform

---

doc/releases/v0.10.1.txt
seaborn/regression.py
seaborn/relational.py
seaborn/tests/test_relational.py
seaborn/tests/test_utils.py
seaborn/utils.py

- Deprecates several `utils` functions that have no internal use (`sig_stars`, `percentiles`, `pmf_hist`, `sort_df`)
- Improves some docstrings
Closes #2034

Housekeeping in utilities module

---

seaborn/axisgrid.py

Following discussion in issue https://github.com/mwaskom/seaborn/issues/2028

Examples of ways to have the same mapping between facets

---

doc/api.rst
doc/whatsnew.rst
examples/horizontal_boxplot.py
seaborn/utils.py

Document functions supporting example data
Add v0.10.1 release notes to whatsnew page
Avoid matplotlib deprecation warning in boxplot example

Handle some small housekeeping items prior to releasing v0.10.1

---

Makefile
seaborn/__init__.py
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/colors/__init__.py
seaborn/distributions.py
seaborn/palettes.py
seaborn/rcmod.py
seaborn/regression.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_categorical.py
seaborn/tests/test_palettes.py
seaborn/widgets.py
setup.cfg

- Define fewer PEP8 exceptions
- Define flake8 config centrally
- Fix existing issues

Stricter code linting

---

seaborn/_core.py
seaborn/conftest.py

Fix typo and dud test

---

seaborn/_core.py
seaborn/relational.py
seaborn/tests/test_relational.py

Dont add null columns in plot_data for unassigned semantics

---

.travis.yml
setup.py

This PR updates the pypi trove classifiers list to improve package discoverability. This includes adding the new matplotlib framework classifier and OS-independent classifier (since no OS-specific code or extension is used directly by seaborn).

Improve seaborn discoverability

---

seaborn/categorical.py

Grammatical correction the inline documentation of `seaborn/categorical.py`

grammatical correction

---

doc/installing.rst
seaborn/matrix.py

This PR adds intersphinx links to `heatmap` and `clustermap`. It also updates a url in the installation guide to its most recent version.

Improve matrix functions docstrings

---

seaborn/tests/test_miscplot.py
seaborn/tests/test_utils.py
seaborn/utils.py

Previously, this function involved an (optional) dependency on BeautifulSoup, but the HTML is trivial to parse with a regular expression, so let's just do that.

Use only stdlib in get_dataset_names

---

ci/deps_latest.txt
ci/deps_minimal.txt

xref #2194, matplotlib/matplotlib#18254

Don't test on matplotlib 3.3.1 to avoid scatter bug

---

doc/api.rst
doc/index.rst
doc/tutorial.rst
seaborn/_docstrings.py
seaborn/axisgrid.py
seaborn/relational.py
seaborn/tests/test_relational.py

Fixes #2145, Fixes #2065, Fixes #2187

Fix and modernize aspects of relational plot docs

---

seaborn/_core.py
seaborn/matrix.py

Supersedes and closes #2193 (rebased on master and merge conflict fixed)

Handle matplotlib 3.3 deprecations

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Always set private despine variable in PairGrid

---

seaborn/distributions.py

Avoid kde when variance is almost 0

---

doc/_static/style.css
doc/introduction.ipynb
doc/releases/v0.11.0.txt
doc/tutorial.rst
doc/tutorial/data_structure.ipynb
doc/tutorial/function_overview.ipynb
examples/scatterplot_matrix.py
examples/scatterplot_sizes.py
seaborn/matrix.py
seaborn/tests/test_utils.py
seaborn/utils.py

Expands the tutorial to include longer discussions of:
- seaborn function types (the modular organization, and especially the figure-level/axes-level distinction)
- data structure (defining long-form, wide-form, and messy data, and giving overview of flexible options for how to pass both long and wide data
Both points were briefly covered in the introduction previously; that text has been removed.

Add user guide documentation on plotting functions and data structures

---

seaborn/_core.py
seaborn/tests/test_core.py

Use decreasing values for categorical size mapping

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Don't try to set attributes on removed axes

---

doc/docstrings/scatterplot.ipynb
doc/introduction.ipynb
doc/tutorial/axis_grids.ipynb
doc/tutorial/function_overview.ipynb
doc/tutorial/relational.ipynb

This PR fixes an internal broken link in the tutorial and a typo. It's great to see 0.11 RC!

DOC: minor fixes

---

doc/docstrings/FacetGrid.ipynb
seaborn/axisgrid.py

Subsumes, builds on, and closes #2246.

Better documentation of FacetGrid's access to underlying matplotlib objects

---

seaborn/axisgrid.py

- Track the layout_pad parameter and use whenever tight_layout is called
- Call tight_layout at the end of pairplot
Closes #2251

Improve PairGrid tight_layout

---

seaborn/distributions.py

Pass `col_order` and `row_order` to FacetGrid in displot

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fix `adjust_subtitles` when `legend_out=False`.

---

.github/workflows/ci.yaml

Relevant matplotlib issue https://github.com/matplotlib/matplotlib/issues/18718

Force doc CI to use Python 3.8

---

seaborn/_testing.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_distributions.py

TST: FIX: Consider array length in artist arrays comparison

---

seaborn/axisgrid.py
seaborn/tests/test_axisgrid.py

Fixes #2307
Working reprex from original issue:

Fix pairgrid

---

seaborn/distributions.py
seaborn/tests/test_distributions.py

Fix faceted bivariate KDE normalization

---

doc/releases/v0.11.0.txt
doc/releases/v0.11.1.txt
doc/whatsnew.rst
examples/pairgrid_dotplot.py
seaborn/axisgrid.py
seaborn/distributions.py
seaborn/palettes.py
seaborn/tests/test_axisgrid.py

Addressing a number of minor issues on the v0.11.1 tag. See commit log for details.

Assorted fixes for small problems

---

.github/workflows/ci.yaml

Can't parallelize over notebooks/html steps without breaking things

Reduce doc CI parallelization

---

seaborn/axisgrid.py
seaborn/matrix.py

Use modern canonical way of drawing the figure

---

seaborn/axisgrid.py
seaborn/matrix.py
seaborn/tests/test_utils.py
seaborn/utils.py

See https://github.com/matplotlib/matplotlib/issues/19197 for context
Fixes #2343

Abstract logic of forcing figure draw with matplotlib backcompat

---

seaborn/_core.py

This should avoid subtle bugs that could crop up when comparing against
the wrong form (e.g. "category" instead of "categorical").
There might be a built-in way to do this, but I couldn't find it...

Restrict comparison values for variable type strings

---

doc/releases/v0.12.0.txt
seaborn/categorical.py
seaborn/tests/test_categorical.py

Prior to a full refactor of `swarmplot`, this PR makes some targeted improvements to the implementation of the beeswarm itself:
- The function now overwrites the `draw` method on the matplotlib artists representing the swarms, meaning that points will be repositioned at draw time and always reflect the latest data transform. This makes the swarm layout robust to future changes in axes scaling or figure layout.
- The underlying data are no longer sorted, so the arrays in the matplotlib artists will match the order in the input dataframe.
- The algorithm now uses pointwise size information, so beeswarms can be drawn with points of varying sizes.

Improve swarmplot algorithm

---

seaborn/relational.py
seaborn/tests/test_utils.py
seaborn/utils.py

Handle deprecation of ci=None in lineplot

---

doc/releases/v0.12.0.txt
seaborn/_statistics.py
seaborn/_testing.py
seaborn/distributions.py
seaborn/tests/test_axisgrid.py
seaborn/tests/test_distributions.py

Set alpha properly on unfilled hist/kde plots

---

seaborn/distributions.py
seaborn/tests/test_distributions.py

Fix faceted bivariate histogram normalization at displot

---

seaborn/distributions.py
seaborn/tests/test_distributions.py

Fixes #2502 
This is a huge development footgun; see #2409 for thoughts on how this can be made automatic to reduce the risk of such bugs

Fix log scaling in distribution plots

---

doc/docstrings/axes_style.ipynb
doc/docstrings/plotting_context.ipynb
doc/docstrings/set_context.ipynb
doc/docstrings/set_style.ipynb
doc/docstrings/set_theme.ipynb
doc/introduction.ipynb
doc/releases/v0.12.0.txt
doc/tools/nb_to_doc.py
seaborn/rcmod.py

Improve docstrings for theme-related functions

---

seaborn/_core.py
seaborn/categorical.py

Followup to #2577; this removes some unecessary tracking of x/y levels

Clean up categorical plot logic a bit

---

seaborn/regression.py

Fix typo: singeton --> singleton

---

doc/releases/v0.11.2.txt
seaborn/distributions.py
seaborn/tests/test_distributions.py

Fix error from bivariate displot with common_bins=False

---

doc/_templates/autosummary/class.rst
doc/api.rst
doc/conf.py
doc/releases/v0.11.2.txt

Make autoclass generate pages for all methods

---

seaborn/tests/test_matrix.py

Fixes numeric issue that popped up in #2727

Test approximate equality on correlation matrix diagonal

---

doc/releases/v0.12.0.txt
seaborn/_core.py
seaborn/tests/test_core.py

Avoid stall/crash on duplicate index in comp_data

---

seaborn/_core/plot.py
seaborn/tests/_core/test_plot.py

Fix multiple moves with pairing

---

seaborn/_core/plot.py
tests/_core/test_plot.py

I would like to add additional legend flexibility, but this is some low-hanging API fruit that doesn't box us in anywhere else.

Allow suppression of legend for individual layers

---

doc/releases/v0.12.0.txt
seaborn/axisgrid.py
seaborn/categorical.py
seaborn/regression.py
tests/test_categorical.py

Closes #2207 (see that issue for details).
Closes #2832

Final removals of previously deprecated features

---

doc/releases/v0.12.0.txt
seaborn/distributions.py
tests/test_distributions.py

Improve robustness to numerical errors in kdeplot

---

doc/docstrings/barplot.ipynb
doc/docstrings/pointplot.ipynb
doc/releases/v0.12.0.txt
doc/tutorial/categorical.ipynb
doc/tutorial/error_bars.ipynb
seaborn/_statistics.py
seaborn/categorical.py
tests/test_categorical.py

Follow on to #2407; see also #2403 for extensive discussion.

Add new errorbar options to bar/pointplot

---

doc/introduction.ipynb
doc/releases/v0.12.0.txt
doc/tutorial/color_palettes.ipynb
doc/tutorial/data_structure.ipynb
doc/tutorial/error_bars.ipynb
seaborn/_core/scales.py
seaborn/_oldcore.py
seaborn/algorithms.py
seaborn/axisgrid.py
seaborn/distributions.py

docs: fix typos

---

seaborn/utils.py

Avoiding unnecessary dataset name checks

Minor fix in utils.py

---

tests/test_matrix.py

Added new test in `test_matrix.py` for different shapes in heatmap's annotation. And fixed typo in test name.

Added new test for heatmap

---

seaborn/_core/plot.py
tests/_core/test_plot.py

Don't apply layout algorithm by default after Plot.on

---

doc/_docstrings/objects.Plot.add.ipynb
doc/_docstrings/objects.Plot.facet.ipynb
doc/_docstrings/objects.Plot.label.ipynb
doc/_docstrings/objects.Plot.layout.ipynb
doc/_docstrings/objects.Plot.limit.ipynb
doc/_docstrings/objects.Plot.on.ipynb
doc/_docstrings/objects.Plot.pair.ipynb
doc/_docstrings/objects.Plot.scale.ipynb
doc/_docstrings/objects.Plot.share.ipynb
doc/_docstrings/objects.Plot.theme.ipynb
doc/_templates/autosummary/plot.rst
doc/api.rst
doc/index.rst
doc/installing.rst
seaborn/_core/moves.py
seaborn/_core/plot.py
seaborn/_core/scales.py
seaborn/_marks/base.py
seaborn/_stats/base.py
seaborn/objects.py
tests/_core/test_scales.py

Add API examples for Plot methods

---

doc/_tutorial/properties.ipynb
doc/conf.py
doc/tutorial.rst
seaborn/_core/plot.py
seaborn/_marks/area.py
seaborn/_marks/bar.py
seaborn/_marks/base.py
seaborn/_marks/dot.py
seaborn/_marks/line.py

Add tutorial page for Mark properties with cross-referencing from relevant docstrings

---

doc/_docstrings/objects.Hist.ipynb
seaborn/_statistics.py
seaborn/_stats/base.py
seaborn/_stats/histogram.py
seaborn/distributions.py
tests/_stats/test_histogram.py
tests/test_axisgrid.py
tests/test_distributions.py

- Refactor univariate `histplot` to use the `Hist` stat object for computation
- Simplify the (internal) `Hist` API
- Add docstring with examples to `Hist`
- Add some parameter validation to `Hist`

Histogram refactoring and improvements

---

pyproject.toml

See https://github.com/matplotlib/matplotlib/issues/24127 for details

Mark as non-compatible with matplotlib 3.6.1

---

seaborn/categorical.py

this is a minor update to the `stripplot` docstring closing #3104

include note in stripplot docstring about edgecolor depending on linewidth

---

doc/installing.rst

Fix a typo in the installing doc

---

doc/_docstrings/pointplot.ipynb
seaborn/_core/typing.py
seaborn/_oldcore.py
seaborn/categorical.py
seaborn/relational.py
seaborn/utils.py
tests/test_categorical.py

This PR refactors the internals of `pointplot` to use the common infrastructure, as described in https://github.com/mwaskom/seaborn/issues/2429 and demonstrated for `barplot` (which is internally very similar) in https://github.com/mwaskom/seaborn/pull/3255.
Most of the changes to the default behavior / API are shared with the other categorical functions, so I won't recite them here. Instead I'll call attention to an important internal change. This change has implications for user code that customizes plots by modifying artists added by seaborn:
**`pointplot` now draws both points and lines with a single `mpl.lines.Line2D`, as opposed to adding a line and then layering a `mpl.collections.PathCollection` (i.e. via `ax.scatter`) on top of it.**
The main user benefit of this change is that …

Modernize pointplot and increase its flexibility

---

doc/_tutorial/objects_interface.ipynb

Fixes small inconsistency in seaborn.objects tutorial

---

seaborn/_oldcore.py
seaborn/categorical.py
seaborn/utils.py
tests/test_core.py
tests/test_utils.py

Eliminates some complexity previously introduced as part of #2429

Refactor to simplify desaturation in categorical plots

---

seaborn/categorical.py
seaborn/utils.py
tests/test_categorical.py

Clean up some duplicated code related to coordinate management

Refactor new categorical internals

---

doc/_docstrings/ecdfplot.ipynb
seaborn/_statistics.py
tests/test_statistics.py

I propose this PR to solve #3334

ecdfplot stat parameter manage percent

---

seaborn/regression.py

Statsmodels 0.14.0 changes the behavior of GLM models with perfect separation to warn instead of error (https://github.com/statsmodels/statsmodels/pull/8552), which breaks seaborn tests and causes some very noisy output in the context of bootstrapping. This PR converts the warning to an error to preserve existing seaborn behavior of not drawing a regression fit when the parameters are undefined.

Handle statsmodels PerfectSeparationWarning on 0.14.0+

---

seaborn/relational.py
tests/test_relational.py

Ignore units= in relplot with kind='scatter'

---

seaborn/regression.py
tests/test_regression.py

Fail early with a nice message when statsmodels is needed

---

examples/horizontal_boxplot.py
examples/jitter_stripplot.py
examples/large_distributions.py
examples/paired_pointplots.py
examples/palette_choices.py
examples/simple_violinplots.py
examples/wide_form_violinplot.py

A few old code patterns were missed in the examples post categorical updates.

Update examples that use deprecated/changed parameters in gallery

---

seaborn/categorical.py

Fix pointplot dodge calculation

---

seaborn/distributions.py

No harm in keeping these around for another cycle and this will speed up the v0.13.0 release.

Postpone some removals of deprecated features

---

doc/_docstrings/catplot.ipynb
seaborn/_core/groupby.py
seaborn/axisgrid.py

Address a couple of warnings that turned up only in the docs

---

doc/_templates/layout.html
doc/_tutorial/categorical.ipynb
doc/_tutorial/data_structure.ipynb
doc/faq.rst
doc/whatsnew/v0.13.0.rst
examples/grouped_violinplots.py

Assorted small doc updates

---

README.md

Update README.md to fix 404 link to license

---

seaborn/_statistics.py
seaborn/categorical.py

Link to error bar tutorial from parameter documentation

---

seaborn/categorical.py

appears here: https://seaborn.pydata.org/generated/seaborn.swarmplot.html

microscopic typofix: "swaarms"

---

seaborn/categorical.py
seaborn/regression.py

This PR adds missing arguments to categorical and regression plots docstrings and fixes a few parameter formatting issues causing misinterpretation by sphinx.

DOC: update categorical and regression docstrings

---

doc/_tutorial/distributions.ipynb

DOC: fix typo
